export type UiLocale = 'zh' | 'en';

const categories = {
  all: ['全部类别', 'All categories'],
  '1': ['影视动画', 'Film & animation'],
  '2': ['汽车', 'Autos & vehicles'],
  '15': ['宠物动物', 'Pets & animals'],
  '17': ['体育', 'Sports'],
  '19': ['旅行', 'Travel & events'],
  '20': ['游戏', 'Gaming'],
  '22': ['人物生活', 'People & blogs'],
  '23': ['喜剧', 'Comedy'],
  '24': ['娱乐', 'Entertainment'],
  '25': ['新闻政治', 'News & politics'],
  '26': ['生活技巧', 'Howto & style'],
  '27': ['教育', 'Education'],
  '28': ['科技', 'Science & technology'],
  '29': ['公益', 'Nonprofits & activism'],
} as const;

const markets = {
  US: ['美国', 'United States'],
  GB: ['英国', 'United Kingdom'],
  JP: ['日本', 'Japan'],
  BR: ['巴西', 'Brazil'],
  MX: ['墨西哥', 'Mexico'],
  IN: ['印度', 'India'],
  ID: ['印度尼西亚', 'Indonesia'],
} as const;

const interfaceLanguage = {
  all: ['全部语言', 'All languages'],
  '英语': ['英语', 'English'],
  '西班牙语': ['西班牙语', 'Spanish'],
  '葡萄牙语': ['葡萄牙语', 'Portuguese'],
} as const;

export const localizedCategory = (value: string, locale: UiLocale) =>
  categories[value as keyof typeof categories]?.[locale === 'zh' ? 0 : 1] ?? value;

export const localizedMarket = (value: string, locale: UiLocale) =>
  markets[value as keyof typeof markets]?.[locale === 'zh' ? 0 : 1] ?? value;

export const localizedContentLanguage = (value: string, locale: UiLocale) =>
  interfaceLanguage[value as keyof typeof interfaceLanguage]?.[locale === 'zh' ? 0 : 1] ?? value;

export const localizedTopic = (value: string, locale: UiLocale) => {
  const match = Object.values(categories).find(([label]) => label === value);
  return match?.[locale === 'zh' ? 0 : 1] ?? value;
};

export const formatCompactNumber = (value: number, locale: UiLocale) =>
  new Intl.NumberFormat(locale === 'zh' ? 'zh-CN' : 'en-US', {
    notation: 'compact',
    maximumFractionDigits: 1,
  }).format(value);

export const languageCopy = {
  zh: {
    nav: ['发现', '排行榜', '机会雷达', '频道诊断', '定价'],
    studioNav: ['指挥台', '深度检索', '选题实验室'],
    theme: '切换颜色模式',
    backHome: '返回首页',
    enterStudio: '进入工作室',
    publicDiscovery: '公开发现',
    signIn: 'Google 登录 · 12次/日',
    signInTitle: '登录后每天可查询 12 次',
    signOut: '退出当前账号',
    interfaceLanguage: '界面语言',
    ranking: {
      filterAria: '排行榜筛选',
      filterEyebrow: '榜单筛选',
      filterTitle: '先定范围，再看排名',
      fixedRule: '固定排除音乐和标记为儿童制作的内容；影视、娱乐、游戏等其他公开类别都会保留。',
      format: '内容形态',
      allFormats: '短 + 长视频',
      short: '只看短视频',
      long: '只看长视频',
      publishWindow: '发布时间范围',
      market: '市场',
      category: '内容类别',
      subscribers: '订阅规模',
      max100k: '10 万以内',
      max50k: '5 万以内',
      unlimited: '不限',
      contentLanguage: '内容语言',
      boundary: '时间范围指视频发布时间；“昨天播放最多”需要持续采集播放快照，不能用单次 API 请求伪造。',
      introLabel: '排行榜',
      introTitle: '全站近期趋势榜单',
      introBody: '无需搜索关键词；按发布时间、频道规模和内容形态筛出值得研究的公开视频。',
      found: '找到',
      publicSamples: '个公开样本',
      collected: '当前 YouTube 公开数据 · 刚刚读取的排名快照',
      loadingSamples: '正在加载公开样本',
      updating: '正在更新榜单…',
      refresh: '更新排行榜',
      copyLink: '复制筛选链接',
      note: '每次读取会合并当前市场多个允许类别的 YouTube 公开候选；“加载更多”继续显示同一快照中的后续排名。音乐与儿童制作内容固定排除。',
      corpus: 'LIVE PUBLIC RANKING · PAGED',
      videoTop: '热门视频排名',
      relativeTop: '低粉高播排名',
      channelTop: '热门样本中的频道榜',
      videoTopBody: '按当前市场多个允许类别的公开候选播放量排列；点击可打开原视频。',
      relativeTopBody: '按播放 / 订阅排列，用于发现公开样本中的相对异常表现；它不是频道历史 outlier 结论。',
      channelTopBody: '基于当前公开候选视频聚合，不是 YouTube 的全球频道总榜。',
      rankObject: '排行榜对象',
      channelBoard: '样本频道榜',
      dailyMax: '当前公开排名快照，可继续加载至无更多结果',
      rankMethod: '视频排序方式',
      lens: '研究视角',
      absolute: '绝对播放',
      relative: '低粉高播',
      relativeBoundary: '“低粉高播”仅使用当前公开视频播放/订阅，不伪造频道历史基线。',
      views: '播放',
      viewsPerSubscriber: '播放 / 订阅',
      avgPerHour: '平均 / 小时',
      research: '研究 ↗',
      noVideos: '当前筛选范围没有公开视频样本。调整市场或内容形态后重试。',
      channelTitle: '查看 {channel} 的样本',
      channelSamples: '样本中有 {count} 条热门视频 · {subs} 订阅',
      accumulatedViews: '样本累计播放',
      averageViews: '样本均值播放',
      samples: '条',
      viewSamples: '查看样本 ↗',
      noChannels: '当前样本中没有可排名的公开频道。',
    },
    home: {
      headline: '每天知道什么正在起势，',
      headlineEmphasis: '以及下一步该做什么。',
      body: 'SignalCraft 将 YouTube 公开信号、可解释评分和行动工作流连接起来。3 分钟找到值得研究的赛道与样本。',
      dailySignals: '查看每日公开信号',
      methodology: '了解评分方法 →',
      snapshot: 'YouTube 公开快照',
      scoreDimensions: '可解释评分维度',
      multiMarket: '地区与语言筛选',
      dataStatus: '数据状态',
      collectionOpen: '每日公开采集已开启',
      daily: '每日',
      panelBody: '按市场、时间和频道规模筛选已采集的公开样本',
      openCurrent: '打开公开发现，查看当前市场样本',
      listTitle: '公开榜单与机会雷达',
      viewAll: '查看全部 →',
      discovery: '自动发现',
      discoveryBody: '无需关键词，按当前市场取样',
      radar: '机会雷达',
      radarBody: '按类别与可行动性聚合公开样本',
      open: '打开 →',
      stepOne: '公开发现',
      stepOneBody: '按时间、语言、市场、频道规模和表现快速筛选。',
      stepTwo: '判断证据',
      stepTwoBody: '看到增速、相对表现、置信度与风险提示。',
      stepThree: '形成行动',
      stepThreeBody: '保存、对标、创建选题并回看结果。',
      cta: '发现不是终点，形成决策才是。',
      studio: '打开我的工作室',
    },
  },
  en: {
    nav: ['Discover', 'Rankings', 'Opportunity radar', 'Channel doctor', 'Pricing'],
    studioNav: ['Command center', 'Deep research', 'Idea lab'],
    theme: 'Toggle color theme',
    backHome: 'Back to home',
    enterStudio: 'Open studio',
    publicDiscovery: 'Public discovery',
    signIn: 'Sign in with Google · 12/day',
    signInTitle: 'Sign in for 12 searches per day',
    signOut: 'Sign out',
    interfaceLanguage: 'Interface language',
    ranking: {
      filterAria: 'Ranking filters',
      filterEyebrow: 'Ranking filters',
      filterTitle: 'Set the scope, then read the ranking',
      fixedRule: 'Music and made-for-kids content are always excluded. Film, entertainment, gaming, and other public categories remain available.',
      format: 'Format',
      allFormats: 'Shorts + long-form',
      short: 'Shorts only',
      long: 'Long-form only',
      publishWindow: 'Published',
      market: 'Market',
      category: 'Category',
      subscribers: 'Channel size',
      max100k: 'Up to 100K',
      max50k: 'Up to 50K',
      unlimited: 'Any size',
      contentLanguage: 'Content language',
      boundary: 'The time window is based on publish time. “Most viewed yesterday” requires ongoing view snapshots and cannot be inferred from one API call.',
      introLabel: 'Rankings',
      introTitle: 'Recent trend rankings',
      introBody: 'No keywords needed. Filter public videos worth studying by publish time, channel size, and format.',
      found: 'Found',
      publicSamples: 'public samples',
      collected: 'Current YouTube public data · ranking snapshot just read',
      loadingSamples: 'Loading public samples',
      updating: 'Refreshing rankings…',
      refresh: 'Refresh rankings',
      copyLink: 'Copy filter link',
      note: 'Each read merges public candidates from several allowed categories in the selected market. Load more shows later ranks from the same snapshot. Music and made-for-kids videos stay excluded.',
      corpus: 'LIVE PUBLIC RANKING · PAGED',
      videoTop: 'Popular video ranking',
      relativeTop: 'High-views / low-subs ranking',
      channelTop: 'Top channels in the sample',
      videoTopBody: 'Ranked by views among public candidates from several allowed categories in the current market. Open a row to view the original video.',
      relativeTopBody: 'Ranked by views per subscriber to surface unusual public samples. This is not a historical channel-outlier conclusion.',
      channelTopBody: 'Aggregated from the current public candidate set. This is not a global YouTube channel ranking.',
      rankObject: 'Ranking entity',
      channelBoard: 'Sample channels',
      dailyMax: 'Current public ranking snapshot · load until no more results',
      rankMethod: 'Video ranking method',
      lens: 'Research lens',
      absolute: 'Views',
      relative: 'High views / low subs',
      relativeBoundary: 'This uses only the current public views-per-subscriber ratio; it does not invent a channel history baseline.',
      views: 'views',
      viewsPerSubscriber: 'views / subscriber',
      avgPerHour: 'avg. / hour',
      research: 'Research ↗',
      noVideos: 'No public video samples match this scope. Change the market or format and try again.',
      channelTitle: 'View samples from {channel}',
      channelSamples: '{count} popular videos in the sample · {subs} subscribers',
      accumulatedViews: 'sample views',
      averageViews: 'avg. sample views',
      samples: 'videos',
      viewSamples: 'View samples ↗',
      noChannels: 'There are no public channels to rank in this sample.',
    },
    home: {
      headline: 'Know what is gaining momentum today,',
      headlineEmphasis: 'and what to do next.',
      body: 'SignalCraft connects public YouTube signals, explainable scoring, and an action workflow. Find a niche or sample worth studying in three minutes.',
      dailySignals: 'View daily public signals',
      methodology: 'How scoring works →',
      snapshot: 'public YouTube snapshot',
      scoreDimensions: 'explainable score dimensions',
      multiMarket: 'market and language scopes',
      dataStatus: 'Data status',
      collectionOpen: 'Daily public collection is active',
      daily: 'Daily',
      panelBody: 'Filter collected public samples by market, time, and channel size',
      openCurrent: 'Open public discovery for the current market',
      listTitle: 'Public rankings and opportunity radar',
      viewAll: 'View all →',
      discovery: 'Auto discovery',
      discoveryBody: 'No keywords needed; sample the current market',
      radar: 'Opportunity radar',
      radarBody: 'Group public samples by category and actionability',
      open: 'Open →',
      stepOne: 'Discover publicly',
      stepOneBody: 'Filter quickly by time, language, market, channel size, and performance.',
      stepTwo: 'Assess evidence',
      stepTwoBody: 'See velocity, relative performance, confidence, and risk notes.',
      stepThree: 'Take action',
      stepThreeBody: 'Save, benchmark, create an idea, and review the outcome.',
      cta: 'Discovery is not the finish line. A decision is.',
      studio: 'Open my studio',
    },
  },
} as const;

export const interpolate = (template: string, values: Record<string, string | number>) =>
  template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
