export type ViralCaseCorpusCard = {
  sourceCaseId: string;
  sourceUrl: string;
  title: string;
  dateKey: string;
  bucket: string;
  summary: string;
  metrics: string;
  formula: string;
  emotion: string;
};

/**
 * Compact, source-linked index distilled from the public cases listing.
 * It intentionally keeps the listing's analysis signals, not the source site's scripts or media.
 */
export const viralCaseCorpus: readonly ViralCaseCorpusCard[] = [
  {
    "sourceCaseId": "04170030",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170030",
    "title": "当有人在利用你时",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "Reid Olson · 这条视频不是字面意义上的桥上救援，而是一条把“被人利用却舍不得放手”做成强视觉隐喻的关系短剧。开头就把 metaphor 拍得非常狠：一个男人挂...",
    "metrics": "播放量：2795W  点赞：65W  评论：5435",
    "formula": "【先把抽象关系问题拍成极端但一眼能懂的危险场景】+【让被依赖者明确表现出被拖累】+【再安排一个旁观者替观众把关系逻辑说破】+【最后留下“我知道，但我还是舍不得”作为情感真结】= 关系隐...",
    "emotion": "情绪曲线：危险、荒唐、被点破、现实代入、认知清醒、情感不舍"
  },
  {
    "sourceCaseId": "04170019",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170019",
    "title": "当你不得不公平对待兄弟姐妹",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "MiniMoochi · 这条视频不是简单的兄妹吵架，而是一条把“父母要公平”这件事拍成永远无解的家庭短剧。开头妈妈端着两只鸡腿上桌，嘴上明明说是一人一个，结果镜头立刻放...",
    "metrics": "播放量：2551W  点赞：35W  评论：1966",
    "formula": "【先用一个最常见的家庭资源分配开场】+【立刻让孩子开始比较份量】+【再切到第二种资源分配把矛盾加码】+【结尾不解决，只放大家庭喊冤状态】= 兄妹公平无解型",
    "emotion": "情绪曲线：正常分配、立刻比较、第一轮抱怨、第二轮争夺、双方同时喊冤、无解收尾"
  },
  {
    "sourceCaseId": "04170018",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170018",
    "title": "最搞笑的模仿",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "Daily Funny.06 · 这条视频不是传统有因果的短剧情节，而是一条用“看到一个动作 / 物体，就立刻说我也会”驱动的物理模仿挑战。开头先给一个非常抓眼的外部参考动作，无...",
    "metrics": "播放量：3248W  点赞：15W  评论：46",
    "formula": "【先给一个一眼能看懂的奇怪动作或物体状态】+【立刻切到表演者说“我也会”】+【连续把人体塞进不同动作模板】+【最后用最圆满、最荒唐的身体模仿收尾】= 身体模仿挑战型",
    "emotion": "情绪曲线：好奇、看懂规则、第一次笑点命中、动作越来越离谱、最终以滚动梗收口"
  },
  {
    "sourceCaseId": "04170013",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170013",
    "title": "学会分享与关爱",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "H&T Official · 这条视频不是现实主义救助故事，而是一条把“得到好运之后，你会不会分给别人”拍成童话 moral skit 的假情境短剧。开头先给出非常简单直接的...",
    "metrics": "播放量：2914W  点赞：66W  评论：2W",
    "formula": "【先让主角处在明显匮乏状态】+【用神迹或超现实手段快速给她好运】+【再抛出一个需要被帮助的人】+【最后用非常直接的好坏标签盖章】= 假情境善意考题型",
    "emotion": "情绪曲线：匮乏、被眷顾、兴奋与满足、面临选择、犹豫、分享后的道德确认"
  },
  {
    "sourceCaseId": "04170012",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170012",
    "title": "她知道得太多了",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "Liatelia · 这条视频不是认真的宠物训练教程，而是一条把“狗狗懂规则但故意钻空子”拍成精准喜剧的小型宠物短剧。开头主人非常认真地在客厅地板上铺好一大片尿垫，画...",
    "metrics": "播放量：3228W  点赞：35W  评论：1028",
    "formula": "【先把主人做足准备的规则系统拍清楚】+【再让宠物表现出像是在研究规则漏洞的状态】+【中段留出主人不在场的悬念】+【最后用微妙事故点位和宠物表情完成 punchline】= 宠物漏洞喜剧...",
    "emotion": "情绪曲线：认真布置、观察试探、预感不妙、回来发现翻车、无语、被狗表情击中"
  },
  {
    "sourceCaseId": "04170003",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04170003",
    "title": "顾客用惊喜换掉了坏掉的自行车",
    "dateKey": "0417",
    "bucket": "B",
    "summary": "VIRUM · 这条视频不是普通的外卖事故记录，而是一条把“预期中的投诉”硬生生翻成“实物善意”的微型 kindness 短剧。开头黑人外卖员骑着一辆破旧自行车...",
    "metrics": "播放量：4126W  点赞：42W  评论：2322",
    "formula": "【先把打工人的真实窘境摆到观众面前】+【再放一个看起来很像会发火的对手位】+【让用户先预判责怪或冲突】+【最后直接给出具体实物帮助】= 陌生人善意反转型",
    "emotion": "情绪曲线：事故尴尬、顾客压迫感、预期会被责怪、惊喜礼物出现、释然与尊重"
  },
  {
    "sourceCaseId": "04150005",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04150005",
    "title": "婆媳大战",
    "dateKey": "0415",
    "bucket": "B",
    "summary": "Shreemani Tripathi · 这条视频不是普通厨房吵架，而是一条把家庭矛盾和“催订阅”直接绑在一起的高概念家族短剧。开头年轻女人站在厨房台面上，一边做介绍一边俯视下方的长辈角...",
    "metrics": "播放量：4511W  点赞：92W  评论：911",
    "formula": "【先用家庭矛盾做强冲突开场】+【立刻让受害方在下一场景完成权力反转】+【把惩罚装置和创作者订阅目标绑在一起】+【让观众的点击动作决定最终机关落下】= 家庭大战 + 订阅互动机关型",
    "emotion": "情绪曲线：挑衅出手、长辈受害、户外报复升级、订阅数倒计时、巨型按钮压顶、互动式收尾"
  },
  {
    "sourceCaseId": "04140043",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04140043",
    "title": "普通人 vs 我｜第24集",
    "dateKey": "0414",
    "bucket": "C",
    "summary": "Mr DegrEE · 这条视频不是完整剧情短剧，而是一条典型的 caption-driven meme，拿“普通人”和“我”在同一情境下的不同反应做夸张对比。开头先把...",
    "metrics": "播放量：1529W  点赞：10W  评论：100",
    "formula": "【先用 Normal People / Me 系列标题让用户秒懂模板】+【给普通版一个极简正常反应】+【把 Me 版本推向连续焦虑和过度确认】+【最后用通话记录或体力透支做收尾】= c...",
    "emotion": "情绪曲线：秒懂对照、正常 vs 慌张、电量焦虑升级、通话记录刷屏、精疲力尽睡着"
  },
  {
    "sourceCaseId": "04140039",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04140039",
    "title": "卡布奇诺女孩的爱情",
    "dateKey": "0414",
    "bucket": "A",
    "summary": "TTINY BOY · 这条视频不是现实恋爱短剧，而是一条用“卡布奇诺杯女孩 + 卷心酥男孩”做拟物恋爱的小型超现实短片。开头先让杯头女孩和卷心酥男孩并排坐着分享零食，...",
    "metrics": "播放量：5562W  点赞：26W  评论：68",
    "formula": "【先用超少见的拟物情侣造型吸引停留】+【中段突然引入会伤害该角色本体的危险道具】+【把甜蜜情绪立刻推成脆弱】+【最后用非现实画面收掉逻辑】= 食物拟人童话反差型",
    "emotion": "情绪曲线：甜蜜约会、危险预感、受伤 / 害怕、陪伴安抚、童话式收尾"
  },
  {
    "sourceCaseId": "04140028",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04140028",
    "title": "小丑大战小狗",
    "dateKey": "0414",
    "bucket": "A",
    "summary": "BlackAngel · 这条视频拍的不是现实宠物护理，而是一条靠“公主更爱狗，红衣小丑吃醋反被自己整翻车”成立的宠物反差短剧。开头先用红衣角色张嘴等投喂、白色小狗也一起...",
    "metrics": "播放量：5396W  点赞：34W  评论：239",
    "formula": "【先把人和宠物放进同一份偏爱关系里】+【明确展示主人更爱宠物】+【让吃醋角色准备报复道具】+【最后把报复反弹到自己身上】= 宠物争宠反噬型",
    "emotion": "情绪曲线：抢食开局、偏爱确认、暗房报复、药水升级、自己翻车、喜剧收尾"
  },
  {
    "sourceCaseId": "04140027",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04140027",
    "title": "见不到你我就心慌｜搞笑家庭爱情故事",
    "dateKey": "0414",
    "bucket": "B",
    "summary": "Vlogger Ayaan Vlogs · 这条视频不是常规爱情对视，而是一条“全家准备骑摩托出门，结果谁坐哪、谁带谁一路乱套”的家庭关系短剧。开头先让绿衣女人牵着男孩从家门里出来，长发男...",
    "metrics": "播放量：2096W  点赞：12W  评论：12",
    "formula": "【先拍成一个再普通不过的家庭出门场景】+【把所有人物都引到同一辆有限座位的交通工具前】+【不断增加想上车的人和要带的东西】+【最后让原本最该掌控局面的人失去位置】= 家庭关系拥挤翻车型",
    "emotion": "情绪曲线：正常出门预期、黄衣少女插入、包袱角色加入、座位分配失控、男人被挤下车、荒诞定格"
  },
  {
    "sourceCaseId": "04130046",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04130046",
    "title": "她把掉地上的食物放回盘里，先被三秒规则抓包，最后却靠祝酒词把场子扳回来",
    "dateKey": "0413",
    "bucket": "C",
    "summary": "Maven-Edits · 这条视频不是单纯的“掉地上还能不能吃”冷笑话，而是一段把社交出丑和机智翻盘压缩在同一场宴会里的影视剪辑。开头 Miss Evans 弯腰把掉在地...",
    "metrics": "播放量：1486W  点赞：—  评论：1597",
    "formula": "【先给一个在正式场合明显失礼的小动作】+【立刻让旁人当场抓包】+【用一轮 witty banter 把尴尬推公开】+【再给主角一次更高层级的社交发言机会】+【最后用一句漂亮台词完成翻盘...",
    "emotion": "情绪曲线：被抓包、尴尬辩解、全桌调侃、第二次社交考验、祝酒词翻盘、被认可收尾"
  },
  {
    "sourceCaseId": "04130035",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04130035",
    "title": "看似只是埋伏在水里的摄影师，最后一秒才亮出翠鸟叼鱼画面",
    "dateKey": "0413",
    "bucket": "C",
    "summary": "SK.Photography 2.0 · 这条视频不是传统剧情短剧，而是一条非常标准的“先给埋伏者，再给战果”的 wildlife reveal。开头直接把 `AFTER 10 SECO...",
    "metrics": "播放量：1603W  点赞：17W  评论：98",
    "formula": "【先用倒计时文案承诺结果】+【把摄影师藏进环境里制造“他在等什么”】+【用极静画面延长期待】+【最后给真正罕见的动物瞬间】= 野生动物等待兑现型",
    "emotion": "情绪曲线：结果承诺、猜摄影师在等什么、平静观察、等待被拉长、翠鸟捕食爆发、一秒回本"
  },
  {
    "sourceCaseId": "04130025",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04130025",
    "title": "护士半脸变装一路切到素颜女孩和条纹角色，爆点是同一半张脸被连续改写",
    "dateKey": "0413",
    "bucket": "A",
    "summary": "Nurse & the Loony · 这条视频不是剧情短剧，而是一条靠“同一张脸被中轴线拆成两个角色”成立的纯视觉变装 short。开头先给完整的粉色护士 cosplay 角色贴脸靠...",
    "metrics": "播放量：5496W  点赞：29W  评论：403",
    "formula": "【先用完整 cosplay 角色贴脸出场】+【把画面中轴线固定成切换缝】+【只替换其中一半脸和衣着】+【继续升级到更搞怪的表情和角色】+【最后用高亮闪白收尾】= 半脸变装反差型",
    "emotion": "情绪曲线：完整护士亮相、第一轮半脸切换、发现不是一次性变装、搞怪角色接管右半边、表情反差继续升级、闪白收尾"
  },
  {
    "sourceCaseId": "04110041",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04110041",
    "title": "人人都夸她长发好看，靠近后才发现真正的梗点是掉屑和卫生反差",
    "dateKey": "0411",
    "bucket": "B",
    "summary": "Fiza khan Spn · 这条视频不是单纯夸“长发女孩好看”，而是一条先立羡慕、再立卫生反差的校园 relatable 短剧。开头同学一上来就摸着她的头发感叹“头发也太长...",
    "metrics": "播放量：3606W  点赞：29W  评论：669",
    "formula": "【先把外貌标签拍成值得羡慕的人设】+【立刻补出别人实际承受的麻烦】+【让老师或公共空间介入把问题公开化】+【最后用身体不适级别的反应做收尾】= 校园外貌反差翻车型",
    "emotion": "情绪曲线：先羡慕长发、发现同桌受影响、老师介入、继续围观、近距离翻车、恶心 payoff"
  },
  {
    "sourceCaseId": "04110018",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04110018",
    "title": "女孩情绪崩溃时，外卖小哥留下的一张纸条把整条视频反转成温柔一击",
    "dateKey": "0411",
    "bucket": "B",
    "summary": "Nikachu · 这条视频本质上是一条“普通送货流程里突然出现的人情味”的情绪短剧。开头先给女孩开门时明显不在状态的表情，再给门外背着包、戴着帽子的送货小哥，观众...",
    "metrics": "播放量：2148W  点赞：43W  评论：1282",
    "formula": "【先给明显低气压的收货对象】+【再放进最日常的配送职业角色】+【用安静交接持续压情绪】+【最后用一个极小的善意道具做反转】= 服务职业温情一击型",
    "emotion": "情绪曲线：低气压开门、尴尬交接、情绪压抑、小哥默默处理、纸条落地、眼泪释放"
  },
  {
    "sourceCaseId": "04110015",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04110015",
    "title": "老师连问基础题，秃头学生把课堂直接答成宇宙数据流",
    "dateKey": "0411",
    "bucket": "B",
    "summary": "UNKNOWN SID · 这条视频本质上是一个“老师问常规题，学生却用完全错位的知识体系把课堂答偏”的教室反差短剧。开头先把老师正坐在讲台前、一本正经提问的状态立起来，观...",
    "metrics": "播放量：3021W  点赞：37W  评论：1332",
    "formula": "【先立一个严肃课堂规则】+【给出外形或气质自带违和感的学生】+【老师持续认真追问】+【学生用完全不对频的回答不断拆规则】+【最后升级成信息量过载的离谱终极回答】= 课堂问答反差型",
    "emotion": "情绪曲线：正常课堂、第一轮违和、老师继续追问、反差越滚越大、数据流爆发、老师震住"
  },
  {
    "sourceCaseId": "04100021",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04100021",
    "title": "Sigma 女孩冷脸出场，把整条梗拍成超现实反击",
    "dateKey": "0410",
    "bucket": "B",
    "summary": "CRAZY GREAPA · 这条视频不是现实逻辑短剧，而是一条彻底按 meme 和超现实升级来运作的 sigma girl 反击梗。开头先把冷脸女生、桌上的钞票和旁边试图逗...",
    "metrics": "播放量：4533W  点赞：30W  评论：211",
    "formula": "【先给冷脸角色和廉价挑衅】+【再引入超现实道具立规则】+【把场景切到更大的惩罚空间】+【最后用夸张视觉反击和得意表情收尾】= sigma 女王超现实反杀型",
    "emotion": "情绪曲线：先看她冷脸、等她什么时候出手、被超现实升级逗到、在最终得意脸里获得回报"
  },
  {
    "sourceCaseId": "04100011",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04100011",
    "title": "他绕过整排盛装女生，把玫瑰送给轮椅女孩",
    "dateKey": "0410",
    "bucket": "B",
    "summary": "love vibes 💕 · 这条视频更像一条童话式浪漫 montage，而不是严格按现实逻辑推进的完整短剧。开头先让男生手拿一束玫瑰站到一排盛装女生面前，观众天然会预判他会...",
    "metrics": "播放量：2778W  点赞：—  评论：148",
    "formula": "【先让男生站到一排高预期对象前】+【再反常地把花送给最容易被忽视的人】+【后半段切进泳池甜感 montage】+【最后用接吻收尾】= 浪漫选择反差型微短剧",
    "emotion": "情绪曲线：先猜他会选谁、在送花反差里被击中、开始沉浸泳池甜感、在接吻收尾里吃满情绪奖励"
  },
  {
    "sourceCaseId": "04100004",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04100004",
    "title": "旧牛仔裤三步改成单肩包",
    "dateKey": "0410",
    "bucket": "B",
    "summary": "Kate done · 这条视频本质上不是讲故事，而是把“旧牛仔裤还能怎么改”压成一个极高效率的 DIY 变形过程。开头最强钩子不是成品，而是创作者直接在自己穿着的牛仔...",
    "metrics": "播放量：4572W  点赞：10W  评论：302",
    "formula": "【先在旧衣服上做不可逆动作】+【把布料迅速拆成可用平面】+【连续展示缝制和配件安装】+【最后上身展示成品】= 旧衣改包型 DIY",
    "emotion": "情绪曲线：先替裤子紧张、看懂改造路径、对工艺细节上头、在成品试背里获得满足"
  },
  {
    "sourceCaseId": "04100002",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04100002",
    "title": "纸杯放地上后，路人开始疯狂塞钱",
    "dateKey": "0410",
    "bucket": "A",
    "summary": "aruzhanm.z · 这条视频不是靠对白推进的短剧，而是一个“日常喝饮料突然变成街头收钱装置”的视觉段子。开头女生先正常喝着纸杯饮料往前走，观众会以为只是普通街拍；紧...",
    "metrics": "播放量：6146W  点赞：29W  评论：2262",
    "formula": "【先把日常动作拍正常】+【再突然把纸杯放地上】+【让路人一张张往里塞钱】+【主角全程维持怪姿收尾】= 纸杯收钱反差型视觉段子",
    "emotion": "情绪曲线：先觉得正常、开始疑惑她要干嘛、第一次投钱时笑出来、看着越来越多人继续塞钱"
  },
  {
    "sourceCaseId": "04090045",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090045",
    "title": "关灯挑战！🤣",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Joe Albanese · 这条视频把最简单的客厅挑战拍成了“关灯一次，站位就变一次”的视觉游戏。开头先让男生站在两位女生面前宣布挑战，观众先知道规则是 lights of...",
    "metrics": "播放量：2610W  点赞：18W  评论：725",
    "formula": "【先把挑战规则讲清】+【每次黑场都给更夸张的 reveal】+【最后用最离谱的一帧收尾】= challenge reveal 型爆款",
    "emotion": "情绪曲线：先理解规则、等第一次变化、开始猜下一次会多夸张、在最终定格里收尾"
  },
  {
    "sourceCaseId": "04090043",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090043",
    "title": "西装大哥被吓到了。#shorts #funny",
    "dateKey": "0409",
    "bucket": "C",
    "summary": "西装兄弟在农村 · 这条视频是非常典型的“车内第一视角 + 车外怪人突然贴脸”的短促惊吓梗。开头先让西装男正常坐在 SUV 里开车，观众会以为只是普通出行；但镜头突...",
    "metrics": "播放量：1863W  点赞：8W  评论：20",
    "formula": "【先给正常第一视角】+【再让异常形象突然贴脸】+【最后用滤镜或逃跑做二次放大】= 惊吓 prank 型爆款",
    "emotion": "情绪曲线：先放松、被突然吓到、因滤镜变得更荒诞、在逃跑反应里收尾"
  },
  {
    "sourceCaseId": "04090041",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090041",
    "title": "哈奴曼信徒把断头恶鬼痛揍了一顿 😱 #hanumanji #hanuman #shorts",
    "dateKey": "0409",
    "bucket": "C",
    "summary": "Lord Creation · 这条视频把 devotional 题材和低成本夜戏鬼怪打斗揉成了一条很直给的 fantasy 短片。开头先让红衣面具角色和男主同框，再把骷髅脸、...",
    "metrics": "播放量：1611W  点赞：—  评论：86",
    "formula": "【先给夜路鬼怪开局】+【再让信徒获得神力加持】+【最后把惊吓源头反过来打跑】= devotional fantasy 反打型爆款",
    "emotion": "情绪曲线：先怕、等神力出现、看局势翻转、在追打里满足"
  },
  {
    "sourceCaseId": "04090017",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090017",
    "title": "The Voice Kids 翻唱 Top 5 排名 🥹❤️",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "VIBE MUSIK MIX · 这条视频本质上是把 `The Voice Kids` 的经典高光时刻重新包装成一个“边看边等名次揭晓”的榜单剪辑。开头先把 `Ranking T...",
    "metrics": "播放量：3956W  点赞：63W  评论：3264",
    "formula": "【先立 Top 榜单框架】+【再连续投放多个高光片段】+【用导师反应和名次 suspense 把比较感维持到最后】= 选秀 ranking 型爆款",
    "emotion": "情绪曲线：先被榜单吸住、被歌手高光打中、开始内心重新排名、在最终名次里收尾"
  },
  {
    "sourceCaseId": "04090016",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090016",
    "title": "秦宇在担心什么？！#Sonic#shorts",
    "dateKey": "0409",
    "bucket": "A",
    "summary": "阿卡姆疯人院 · 这条视频不是线性短剧，而是把一个睡衣男主的“担心链条”拍成连续升级的荒诞拼贴。开头先给他抱着被子直接坐在路中央，后面甚至顶着 SUV 的威胁，这...",
    "metrics": "播放量：6559W  点赞：40W  评论：226",
    "formula": "【先丢一个完全离谱的起始画面】+【再不断切换更怪的空间和道具】+【让人物只负责承受荒诞】= surreal 拼贴型爆款",
    "emotion": "情绪曲线：先惊到、觉得离谱、开始等下一个怪段子、在拼贴升级里收尾"
  },
  {
    "sourceCaseId": "04090012",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090012",
    "title": "一个罗摩信徒的故事 🚩🙏🏼 / / Ritu 最后得到了什么😲 / / जय श्री राम / / 罗摩主题短片 #shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "AbhinavSwag · 这条视频走的是很典型的印度 devotional wish-fulfillment 小短剧。开头一家三口坐在屋顶上，女人和孩子先抬头看天，把“他...",
    "metrics": "播放量：2568W  点赞：14W  评论：0",
    "formula": "【先让普通家庭抬头等待】+【再用天空或神迹特效给出回应】+【最后让祝福真正落到人物手里】= devotional 愿望实现型爆款",
    "emotion": "情绪曲线：先好奇、等回应、被夸张特效拉高、在“真的得到了”里收尾"
  },
  {
    "sourceCaseId": "04090011",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090011",
    "title": "GuguGaga 出现了吗！#shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Stationery Pal · 这条视频把普通填色过程包装成了一次 `GuguGaga` 主题 reveal。开头先给线稿企鹅和屏幕上的数字 / 颜色提示，让观众马上知道这是“...",
    "metrics": "播放量：3058W  点赞：39W  评论：993",
    "formula": "【先给未完成线稿】+【再用数字或颜色提示持续推进】+【最后补完整成品和额外 reveal】= 文具填色型爆款",
    "emotion": "情绪曲线：先好奇成品、跟着颜色变化、等最后 reveal、在完整成品里收尾"
  },
  {
    "sourceCaseId": "04090010",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090010",
    "title": "骗局等级 1 ❌ 骗局等级 100 ✅ #funnyshorts #shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Viishu Bhandari · 这条视频的核心不是“有人被骗”本身，而是把骗局拍成了一个夸张升级实验。开头先用屏幕上的 `Scam Level 1` 和 `Scam Level...",
    "metrics": "播放量：4821W  点赞：70W  评论：802",
    "formula": "【先把同一骗局拆成 `Level 1 / Level 100`】+【先演最基础版本】+【再让电话、亲友和门外人物全部加入】+【最后证明整条动线都是骗局的一部分】= 等级升级型多角色骗局",
    "emotion": "情绪曲线：先看懂玩法、觉得基础版已经够直接、发现升级版越来越离谱、在全员配合收尾里笑出来"
  },
  {
    "sourceCaseId": "04090009",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090009",
    "title": "不看球也能打中的一击 🏏 // Tata IPL 仅在 @StarSportsIndia @JioHotstar",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Funcho Shorts · 这条视频走的是“儿子本来想炫耀自己见到了球星，结果妈妈直接越过他和球星聊起来”的家庭体育喜剧。开头男生在 IPL 场地和妈妈视频通话，先抛出 `...",
    "metrics": "播放量：3062W  点赞：63W  评论：1262",
    "formula": "【先让普通人炫耀自己见到明星】+【再让长辈直接越过他和明星聊正题】+【最后把明星 advice 反噬回家里】= 球星 cameo 家庭喜剧型爆款",
    "emotion": "情绪曲线：先羡慕球星 surprise、看妈妈越聊越投入、被技巧问答逗到、在回家反噬里收尾"
  },
  {
    "sourceCaseId": "04090008",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090008",
    "title": "新汽车还是老火车？🚂🚜🤖",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Construction Site · 这条视频不是传统剧情短剧，而是把“不同年代的交通工具想象”做成了一条非常直给的年代表演。开头先用 `2026` 的大字和机器人狗、现代小车把未来...",
    "metrics": "播放量：2481W  点赞：12W  评论：43",
    "formula": "【先给超大年份标签】+【再让同一场景被不同年代版本接管】+【最后把时间线拉到最远】= 年代对比型爆款",
    "emotion": "情绪曲线：先被年份钩住、等下一次切换、开始比较哪个更好玩、在完整时代链里收尾"
  },
  {
    "sourceCaseId": "04090007",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090007",
    "title": "千万别说威尔士语，又新增奇怪知识了！ / Horrible Histories #shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Mina Islam · 这条视频是 `Horrible Histories` 风格最典型的“把历史惩罚制度拍成连锁误伤笑话”的课堂短剧。开头先由学生提问“如果被听到说威...",
    "metrics": "播放量：3550W  点赞：63W  评论：7032",
    "formula": "【先抛一个离谱历史规则】+【让角色按规则互相告密】+【最后让解释规则的人也被规则反噬】= 历史制度喜剧型爆款",
    "emotion": "情绪曲线：先好奇规则、被学生互坑逗到、意识到老师也危险、在反噬收尾里爆笑"
  },
  {
    "sourceCaseId": "04090004",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090004",
    "title": "笑吧……笑吧……！！！ #viral #funny #duet #dance",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Minh Fun TV · 这条视频本质上是“强装镇定的人身体先绷不住”的尴尬反应短片。上层原视频里，一男一女站在门口，女生已经带着明显看热闹的状态，男生一开始还努力维持手...",
    "metrics": "播放量：4668W  点赞：47W  评论：5215",
    "formula": "【先让人物强装镇定】+【再让身体反应一步步背叛他】+【最后用 reaction 视角把尴尬放大】= duet 尴尬反应型爆款",
    "emotion": "情绪曲线：先观察、觉得要崩、看他一步步塌下去、在最终抱头姿势里爆笑"
  },
  {
    "sourceCaseId": "04090002",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090002",
    "title": "订阅就有 7 年好运！🍀😅 #dance #funny #couple #shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Cadel and Mia · 这条视频是极短的情侣贪吃反应梗。开头先让两个人在泳池边轻松吃面，气氛看起来像普通 couple 日常；中段女孩手机掉地，她弯下去捡的这一下立刻把...",
    "metrics": "播放量：4600W  点赞：26W  评论：670",
    "formula": "【先给关系日常】+【制造一个极短空档】+【让另一方做出最不体面的反应】+【再回放一次】= couple visual punchline 型爆款",
    "emotion": "情绪曲线：先觉得轻松、意识到要出事、被偷吃动作逗到、在回放里再笑一次"
  },
  {
    "sourceCaseId": "04090001",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04090001",
    "title": "芭比和肯家庭套装拆箱超解压，ASMR 视频 #shorts",
    "dateKey": "0409",
    "bucket": "B",
    "summary": "Pinky Joy · 这条视频本质上是把 Barbie/Ken 玩具生活压缩成一条超亮色的 toy roleplay satisfying 短片。开头先给粉色别墅和敞...",
    "metrics": "播放量：4883W  点赞：22W  评论：100",
    "formula": "【先给高饱和玩具世界】+【再让角色进入场景】+【最后用换装或细节 reveal 收尾】= Barbie / toy roleplay 型爆款",
    "emotion": "情绪曲线：先被颜色吸住、看 Ken 进入剧情、盯卧室细节、被礼服 reveal 满足"
  },
  {
    "sourceCaseId": "04080114",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080114",
    "title": "巴迪霍纳盖亚电话莱内🥲#siblings #trendingshorts #funny #relatable #apachho",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Apachho Singh · 这条视频是极短的姐妹互怼 relatable skit。开头先让穿黑衬衫的姐姐带着强势情绪出场，观众马上知道这是要吵；随后另一位女孩出镜对着她回...",
    "metrics": "播放量：2152W  点赞：15W  评论：315",
    "formula": "【先让家里更强势的人发难】+【再让另一方用一句大实话回怼】+【最后把表情停顿留给观众】= siblings 互怼型爆款",
    "emotion": "情绪曲线：先紧张、等反击、被回怼 punchline 戳中、在表情停顿里收尾"
  },
  {
    "sourceCaseId": "04080109",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080109",
    "title": "不是金钱……善良是最珍贵的愿望🎂💖#zunizuni",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "Zuni Zuni · 这条视频走的是非常标准的暖心价值观叙事。开头先是生日蛋糕和许愿氛围，像是普通庆生；随后镜头把女孩带到户外，她看见需要帮助的人，故事主轴从“为自己...",
    "metrics": "播放量：1803W  点赞：58W  评论：1034",
    "formula": "【先给一个属于主角自己的快乐场景】+【中段让主角看见别人的需要】+【最后把快乐转成善意行动】= 暖心 kindness 型爆款",
    "emotion": "情绪曲线：先觉得甜、察觉转向、被善意打动、在群体认同里收尾"
  },
  {
    "sourceCaseId": "04080094",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080094",
    "title": "奇怪的是令人满意的 1000 °C 热铁与 Thermocol 的比较。 #短裤#asmr #实验",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "Hot Ball Asmr · 这条视频是典型的 destruct / ASMR 实验短片。开头直接把热铁和层叠 thermocol 结构摆好，观众马上知道要看“热东西碰泡沫”...",
    "metrics": "播放量：1805W  点赞：7W  评论：25",
    "formula": "【先摆出极简实验规则】+【让材料变化连续可见】+【最后停在最满足的一帧】= destruct ASMR 型爆款",
    "emotion": "情绪曲线：先好奇、盯第一层、等连续穿透、在结果里得到满足"
  },
  {
    "sourceCaseId": "04080090",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080090",
    "title": "[ Poppy Playtime ] 着装给 MEMES 留下深刻印象 🤣 玩家#shorts",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "IdrawithMouse · 这条视频不是完整叙事，而是把 Poppy Playtime 和 Dress to Impress 两个熟悉 IP 做成快速 meme 拼盘。开头...",
    "metrics": "播放量：2222W  点赞：15W  评论：1040",
    "formula": "【先拿一个熟悉角色开门】+【中段连续堆更多 recognizable IP】+【最后让换装结果越来越离谱】= 游戏 crossover meme 型爆款",
    "emotion": "情绪曲线：先认出 IP、等更多角色出现、被离谱造型逗到、在连续梗里结束"
  },
  {
    "sourceCaseId": "04080089",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080089",
    "title": "有史以来最好的小吃",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Nick DiGiovanni · 这条视频是标准的“先抛一个秘密零食结论，再用小故事把你说服”的 food narration。开头 Nick 直接说这是全世界他最爱的零食，结论...",
    "metrics": "播放量：2420W  点赞：46W  评论：2658",
    "formula": "【先抛一个极强主观看法】+【再讲产品来历或故事】+【最后用现实囤货行为做证明】= food recommendation 型爆款",
    "emotion": "情绪曲线：先被结论抓住、听由来、看细节、被囤货行为彻底说服"
  },
  {
    "sourceCaseId": "04080084",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080084",
    "title": "英雄猫为小弟弟遮风挡雨！ 🍳",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "もこまるファミリー【赤ちゃんと猫2匹との暮らし】 · 这条视频把“猫替弟弟收拾烂摊子”拍成了极短的家庭童话。开头猫咪先从门后偷看，像是在监视弟弟做了什么；随后地上的鸡蛋碎开，观众瞬间知道小事故已经发...",
    "metrics": "播放量：1951W  点赞：9W  评论：130",
    "formula": "【先让宠物像人一样察觉异常】+【中段给一个宝宝小事故】+【最后让宠物完成拟人化救场】= hero pet 温情型爆款",
    "emotion": "情绪曲线：先觉得萌、看到事故、期待猫怎么救、在温柔 payoff 里被治愈"
  },
  {
    "sourceCaseId": "04080081",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080081",
    "title": "从 D 学生到“数学天才”……Grac#trending #viralvideo #shorts",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "LA VOZ DE PELICULA · 这条视频是典型的长旁白故事型 Shorts。开头先交代男主因为代数拿 D，被父亲禁掉游戏机；随后他谎称去朋友家参加学习小组，实际上是去一个坐轮椅...",
    "metrics": "播放量：1539W  点赞：41W  评论：584",
    "formula": "【先给一个坏成绩困境】+【再让主角用小谎言保住兴趣爱好】+【最后把谎言滚成更大的身份误会】= 长旁白反转故事型爆款",
    "emotion": "情绪曲线：先替他紧张、跟着他撒谎、看误会越滚越大、在最终身份错位里得到笑点"
  },
  {
    "sourceCaseId": "04080077",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080077",
    "title": "海洛伊西在错误的时间让她笑了🤣🤣🤣",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "Heloisy Bello · 这条视频的笑点来自“偏偏在嘴里有饮料的时候把你逗笑”。开头先给女孩喝汽水，观众天然知道这时最怕被逗；随后 Heloisy 和另一位夸张角色入场，...",
    "metrics": "播放量：1512W  点赞：12W  评论：473",
    "formula": "【先给一个最不能笑的瞬间】+【再让整活角色逼近】+【最后用喷饮料失控做 payoff】= laugh trap 型爆款",
    "emotion": "情绪曲线：先预判、等她失守、被喷饮料逗笑、看全员反应收尾"
  },
  {
    "sourceCaseId": "04080075",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080075",
    "title": "柠檬把戏没人谈论#survival #camping #campfire",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Outdoors Creators · 这条视频把户外 survival 标签和身体惊悚感绑在了一起。开头先用一条夸张的软体生物缠在脖子上的画面把观众吓住，后面再切到背部泛红、发痒和柠...",
    "metrics": "播放量：2363W  点赞：16W  评论：142",
    "formula": "【先给强生理不适画面】+【再给简单处理过程】+【最后拍出缓解结果】= 户外惊悚 remedy 型爆款",
    "emotion": "情绪曲线：先被吓住、跟着难受、等解决办法、被简单 payoff 安抚"
  },
  {
    "sourceCaseId": "04080062",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080062",
    "title": "爸爸不是它的对手💀😂#comedy",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "MrTalalaa · 这条视频走的是最经典的“孩子怕怪物，爸爸嘴硬去证明，结果自己先破防”的反转喜剧。开头儿子急着把爸爸叫来，先把 closet monster 设定...",
    "metrics": "播放量：1972W  点赞：11W  评论：461",
    "formula": "【先让孩子抛出怪物问题】+【再让家长强势否定】+【最后让最嘴硬的人先翻车】= 家庭反转喜剧型爆款",
    "emotion": "情绪曲线：先好奇、被爸爸嘴硬逗到、等他翻车、在强装镇定里爆笑"
  },
  {
    "sourceCaseId": "04080046",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080046",
    "title": "2,200 卡路里的垃圾食品❌ vs 2,200 卡路里的全食 ✅ #fatloss #losingweight #diet",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Nurse Jahmel · 这条视频把“同样 2200 卡路里，食物体积差多少”拍成了最直接的减脂视觉对照。左边固定写着垃圾食品 2200 Cal，右边则从 0 Cal 开...",
    "metrics": "播放量：2629W  点赞：58W  评论：1W",
    "formula": "【先给明确比较规则】+【持续堆高对照差异】+【最后在同一数字上完成结论】= 热量对照型爆款",
    "emotion": "情绪曲线：先理解规则、期待差距拉开、被体积对比说服、得到明确饮食结论"
  },
  {
    "sourceCaseId": "04080042",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080042",
    "title": "生存技巧：实用又聪明",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "Funny Club TV · 这条视频不是传统意义上的 survival 教程，而是一个靠“标题骗进来、画面吓一下”的超短 WTF 奇观。开头先给男人拿着石头，观众会以为真要...",
    "metrics": "播放量：1495W  点赞：—  评论：16",
    "formula": "【先伪装成正常教程】+【中段突然切成诡异奇观】+【不解释直接结束】= 超短 WTF 型爆款",
    "emotion": "情绪曲线：先信了标题、突然看懵、被猎奇特写留住"
  },
  {
    "sourceCaseId": "04080036",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080036",
    "title": "本周不同的天气阶段",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "MiniMoochi · 这条视频把一周七天拍成一个开门盲盒式天气 meme。开头从 Monday 到 Friday 依次开门，天气看起来还算正常；中后段突然跳到暴风雪、...",
    "metrics": "播放量：1985W  点赞：14W  评论：1017",
    "formula": "【先建立重复规则】+【让每一次 reveal 更离谱】+【最后用最共鸣的标签句收尾】= 一周情绪 meme 型爆款",
    "emotion": "情绪曲线：先觉得有趣、等更离谱变化、被周末梗击中、对 Monday 再次破防"
  },
  {
    "sourceCaseId": "04080029",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080029",
    "title": "一条有秘密的鳄鱼🐊🤔完美的伪装！ ＃短裤",
    "dateKey": "0408",
    "bucket": "C",
    "summary": "Miracle Animal Rescues · 这条视频一上来先把观众扔进满是鳄鱼的危险场景里，再在最后 5 秒揭示“其中一只鳄鱼其实藏着秘密”。前半段女人在水里穿行、周围鳄鱼张嘴，观众会先以...",
    "metrics": "播放量：1733W  点赞：17W  评论：395",
    "formula": "【先立高压危险场景】+【中段持续加压】+【最后用一个装置 reveal 改写观众理解】= camouflage 奇观型爆款",
    "emotion": "情绪曲线：先紧张、更紧张、察觉异常、被 reveal 击中"
  },
  {
    "sourceCaseId": "04080022",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080022",
    "title": "兄弟姐妹要像🤣",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Speed McQueen · 这条视频是极简版兄弟姐妹抢饮料搞笑短剧。开头先把三个人围着同一杯饮料坐好，标题“兄弟姐妹就是这样”已经把共鸣主题抛清楚；中段他们同时抢吸管、越凑...",
    "metrics": "播放量：2942W  点赞：21W  评论：1291",
    "formula": "【先给一个所有兄弟姐妹都懂的小冲突】+【把冲突动作逐步夸大】+【最后拍出最离谱的一帧】= siblings 共鸣型爆款",
    "emotion": "情绪曲线：先觉得熟悉、看谁先抢、被越挤越离谱逗笑、在荒诞画面里收尾"
  },
  {
    "sourceCaseId": "04080020",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080020",
    "title": "我想要一个像你这样的女人#funny #dance #shortvideo #shortsvideo #shorts #short",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "El Chocua1.1 · 这条视频卖的是很直接的气场反差。开头先给一位穿蓝色运动服的女孩和一位桃红造型角色，前者明显没有被打动；随后更高、更有气场的同风格角色入场，同样的...",
    "metrics": "播放量：4451W  点赞：28W  评论：373",
    "formula": "【先给一版明显不成立的搭配】+【再让更强气场角色后入场】+【最后用选择结果拍实】= flirt-dance 反差型爆款",
    "emotion": "情绪曲线：先替人尴尬、等新角色出场、被反差逗到、看翻盘收尾"
  },
  {
    "sourceCaseId": "04080019",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080019",
    "title": "穷BF vs 富GF要饭🙏🥺",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Andrey Grechka · 这条视频走的是“穷男友 vs 富女友”的食物反差搞笑线。开头先让男友露出饿肚子和求食物的状态，观众很快能看懂阶层反差的设定；随后富女友给出的却是...",
    "metrics": "播放量：3689W  点赞：53W  评论：4581",
    "formula": "【先立穷富关系】+【给出不符合期待的食物】+【最后再用真正 payoff 收尾】= 穷富食物反差型爆款",
    "emotion": "情绪曲线：先可怜他、被小份食物逗笑、等他翻盘、被最终食物满足"
  },
  {
    "sourceCaseId": "04080018",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080018",
    "title": "小狗带她找到秘密宝藏",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "xAiSlop · 这条视频是典型的 AI 童话式寻宝短片。前半段先用矿洞、金狗和神秘女性把“有秘密财富”这个感觉抛出来，后半段再切到老妇人和黑色小狗，通过洗净、带...",
    "metrics": "播放量：2101W  点赞：—  评论：83",
    "formula": "【先抛神秘财宝线索】+【再让宠物成为带路角色】+【最后用开箱结果完成回报】= AI 寻宝童话型爆款",
    "emotion": "情绪曲线：先被神秘画面吸住、接受寻宝任务、等挖掘结果、被宝箱 payoff 满足"
  },
  {
    "sourceCaseId": "04080016",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080016",
    "title": "最奇怪的黑客，但它确实有效......🫣 #cat #viralcats #hack #lifehacks",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "_de_alina · 这条视频卖的不是严格教程，而是“这看起来也太离谱了，但猫居然真的买账”的反差。开头先给男人把保鲜膜包在头上，这一步已经足够古怪；随后镜头切到女孩...",
    "metrics": "播放量：4067W  点赞：17W  评论：168",
    "formula": "【先抛一个看起来很离谱的 setup】+【让宠物先保持冷淡】+【最后给出意外有效的反应证明】= 宠物 hack 型爆款",
    "emotion": "情绪曲线：先看懵、保持怀疑、等猫反应、被反差说服"
  },
  {
    "sourceCaseId": "04080013",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080013",
    "title": "难以置信的事情刚刚发生了！#shorts #fyp #funny #illusion #plottwist",
    "dateKey": "0408",
    "bucket": "A",
    "summary": "Happy Camp · 这条视频的传播逻辑非常简单，就是把“黑色液体洒在屏幕里的人脸上了”拍成一个一眼会误判的 illusion prank。开头先给女孩往画面上泼东西...",
    "metrics": "播放量：6534W  点赞：27W  评论：376",
    "formula": "【先制造一眼会误判的画面】+【再给一个急着补救的反应角色】+【最后在极短时间内揭示真相】= illusion prank 型爆款",
    "emotion": "情绪曲线：先看懵、跟着紧张、等真相、被小反转释放"
  },
  {
    "sourceCaseId": "04080008",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080008",
    "title": "书呆子打破了盖子，女孩们尖叫😈😱",
    "dateKey": "0408",
    "bucket": "B",
    "summary": "Tommy WORKOUT · 这条视频走的是公共场景 embarrassment prank 路线。开头先把一个看起来有点木讷的男生和两个风格强烈的女孩放在同一画面里，观众天...",
    "metrics": "播放量：3720W  点赞：50W  评论：1733",
    "formula": "【先立尴尬关系】+【让主角靠近并做出冒失动作】+【事故发生后再拍善后】= 公共社死型爆款",
    "emotion": "情绪曲线：先替他尴尬、等事故发生、被尖叫反应击中、看他收场"
  },
  {
    "sourceCaseId": "04080006",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080006",
    "title": "现在是我在家的规则🤣🤌🏻#shorts",
    "dateKey": "0408",
    "bucket": "A",
    "summary": "Kratika Moyal · 这条视频是很典型的“一个人在家时会怎样放飞自我”的 relatable 短剧。开头先给女孩确认家里没人、环境安全，观众马上懂主题；后面连续切成她...",
    "metrics": "播放量：7022W  点赞：68W  评论：1236",
    "formula": "【先确认独处状态】+【连续堆熟悉又夸张的小动作】+【最后维持轻松放飞感收尾】= relatable home-alone 型爆款",
    "emotion": "情绪曲线：先确认安全、开始放飞、越玩越上头、轻松收尾"
  },
  {
    "sourceCaseId": "04080002",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080002",
    "title": "帮助 Heloisy 达到 800 万订阅者❤️❤️",
    "dateKey": "0408",
    "bucket": "A",
    "summary": "Heloisy Bello · 这条视频把“800 万订阅里程碑”做成了一个极短的 celebration short。开头先给主角和蛋糕，观众立刻知道这是 milestone...",
    "metrics": "播放量：6583W  点赞：171W  评论：3217",
    "formula": "【先立 milestone 目标】+【中段给一次小打断】+【最后把数字达成拍实】= creator 庆祝型爆款",
    "emotion": "情绪曲线：先期待、被打断、盯数字、终于达标"
  },
  {
    "sourceCaseId": "04080001",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04080001",
    "title": "便携式、功能强大的智能铅笔式 Borewell 钻机投入使用",
    "dateKey": "0408",
    "bucket": "A",
    "summary": "Picture Culture · 这条视频本质上是把原本看不见的钻井过程，压缩成一个谁都能秒懂的工程 satisfying 演示。开头先给便携式钻机和地面操作，观众先知道“它在打...",
    "metrics": "播放量：8160W  点赞：69W  评论：808",
    "formula": "【先给设备动作】+【把隐藏过程做成剖面可视化】+【最后给明确结果验证】= 工程演示型爆款",
    "emotion": "情绪曲线：先看设备、盯地下推进、等含水层、被出水结果满足"
  },
  {
    "sourceCaseId": "04070168",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070168",
    "title": "经理惹错人了",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "EchoLab · 这条视频是很成熟的“服务行业歧视翻车”爽剧模板。开头经理站在豪华酒店前台，说话礼貌但明显带着上对下的审视；等到 Eleanor Young 报出...",
    "metrics": "播放量：1384W  点赞：31W  评论：4208",
    "formula": "【先给一个高端服务场景】+【用歧视性拒绝把情绪压低】+【再用真正的身份关系一把翻盘】+【最后补一句羞辱式点题】= 身份反杀爽剧型",
    "emotion": "情绪曲线：先礼貌、感到冒犯、压抑生气、翻盘过瘾"
  },
  {
    "sourceCaseId": "04070146",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070146",
    "title": "诚实工人的爆火视频",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "up wala aryan · 这条视频是典型的“底层劳动者 honesty 测试”短剧。开头先给洗手、擦桌、清洁键盘这些勤快动作，把工人的工作状态立得很扎实；随后老板坐在奖杯...",
    "metrics": "播放量：1337W  点赞：33W  评论：901",
    "formula": "【先给劳动者真实工作的镜头】+【再给出金钱诱惑】+【让角色主动退回不属于自己的部分】+【用监控 / 围观确认】= honesty respect 型",
    "emotion": "情绪曲线：先建立信任、担心他被诱惑、看到他退钱、被 honesty 打中"
  },
  {
    "sourceCaseId": "04070116",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070116",
    "title": "多做善事，愿真主更好地保护我们",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "mutlubakk · 这条视频是典型的“先制造误解，再用一个善意动作翻回来”的街头善举短片。开头男人先弯腰、停步、视线往地上和长椅方向走，观众第一秒未必能判断他要做什...",
    "metrics": "播放量：4278W  点赞：39W  评论：3955",
    "formula": "【先给一个容易被误解的停步动作】+【再露出真正需要帮助的人】+【用一个安静善举完成反转】+【做完就走】= 街头善意微反转型",
    "emotion": "情绪曲线：疑惑、看清对象、被善举击中、温情收尾"
  },
  {
    "sourceCaseId": "04070109",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070109",
    "title": "那个最会毁气氛的人",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "Soopar Show · 这条视频卖的是一个人人都见过的社交 archetype：每次大家想开心，他总能立刻说出一句扫兴的话。开头直接把 `That one person...",
    "metrics": "播放量：2141W  点赞：13W  评论：927",
    "formula": "【先用一句人物标签立 archetype】+【再把这个 archetype 扔进最容易兴奋的公共场景】+【每到一个点都用同一类扫兴句式回收】= archetype 喜剧型",
    "emotion": "情绪曲线：先认出这种人、开始替分享者心累、越看越熟悉、archetype 成立"
  },
  {
    "sourceCaseId": "04070095",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070095",
    "title": "我和妈妈的对决",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "Kratika Moyal EXTRA · 这条视频抓的是家庭里最稳定的一种双标体验：同样是犯错，轮到孩子和轮到妈妈，家庭里的叙事规则完全不一样。开头大字直接打 `When it's yo...",
    "metrics": "播放量：1367W  点赞：18W  评论：569",
    "formula": "【一句大字文案先抛出家庭双标主题】+【前半段先让孩子吃亏】+【后半段把家长版本规则切出来】= 家庭 relatable 对比型",
    "emotion": "情绪曲线：代入被训、开始不服、发现双标、熟悉到想笑"
  },
  {
    "sourceCaseId": "04070085",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070085",
    "title": "善意背后的真相",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "HuntrixTales520 · 这条视频是典型的“你以为看懂了现场，结果只看到了表面”微反转短剧。开头先给高处掉物和楼下两名女孩的混乱瞬间，观众根本来不及判断谁受伤、谁在帮忙；...",
    "metrics": "播放量：1386W  点赞：13W  评论：646",
    "formula": "【先给一个看不全的突发事故】+【再让某个角色率先站队】+【最后用受伤证据推翻前面判断】= 善意误读型 micro-drama",
    "emotion": "情绪曲线：先慌、站队、冲突升级、被反转打回去"
  },
  {
    "sourceCaseId": "04070068",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070068",
    "title": "和闺蜜两分钟视频聊成超长唠嗑",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "Brianna Guidryy · 这条视频是典型的“POV 情境 + 时间失控升级”短 skit。开头先抛一个大家都懂的日常：闺蜜说只聊两分钟，观众一秒就能代入；接着镜头不靠换场...",
    "metrics": "播放量：1643W  点赞：15W  评论：1862",
    "formula": "【先抛一个所有人都懂的通话场景】+【让八卦对白越滚越大】+【同机位不断升级造型表现时间流逝】= relatable 闺蜜 skit 型",
    "emotion": "情绪曲线：生活共鸣、开始吃瓜、越聊越久、夸张爆点"
  },
  {
    "sourceCaseId": "04070054",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070054",
    "title": "捉迷藏换位特效",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "CEO MASTERPIECE · 这条视频卖点非常纯粹，就是一个“真人和墙上剪影不断换位”的街头 VFX 捉迷藏梗。开头第一眼就给出一个贴在墙上的人物轮廓和一名红衣角色，观众马上...",
    "metrics": "播放量：2438W  点赞：16W  评论：68",
    "formula": "【先给真人和墙影同框的谜面】+【在固定背景里反复切换】+【加入追捕者把特效变成游戏】= 街头换位 VFX 型",
    "emotion": "情绪曲线：看懵、开始盯细节、被切换骗到、接受规则并继续看"
  },
  {
    "sourceCaseId": "04070046",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070046",
    "title": "有时候我们会故意把事情搞砸",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "ashmalikupcop · 这条视频表面看像“警察把鞋弄脏了”，实际卖点是“为了帮路边手艺人开张，故意给自己制造麻烦”。开头警察先盯着自己的皮鞋和手里那瓶液体，观众第一反应...",
    "metrics": "播放量：4030W  点赞：86W  评论：7782",
    "formula": "【先用一个像在搞砸事情的动作制造误解】+【再露出真正需要这份工作的手艺人】+【让善意通过职业服务完成】= respect 反转型",
    "emotion": "情绪曲线：先误会、看见手艺人、理解动机、温和落地"
  },
  {
    "sourceCaseId": "04070042",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070042",
    "title": "搞笑版《大力女子都奉顺》",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "Binoy's Talk · 这条视频本质上是“反差型超能力女孩”喜剧，不靠复杂剧情，而靠一个看上去很温柔的女生不断做出超规格动作。前半段她在草地和露营区像普通女孩一样出现，...",
    "metrics": "播放量：1856W  点赞：28W  评论：292",
    "formula": "【先给一个温柔普通的人设】+【逐步抬出超规格道具】+【连续展示不合常理的力量动作】+【用轻松表情收尾】= 反差超能力型",
    "emotion": "情绪曲线：看起来普通、开始怀疑、见到超强动作、反差确认"
  },
  {
    "sourceCaseId": "04070034",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070034",
    "title": "OMG 憋笑挑战",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "comedy_creator · 这条视频不是单线剧情，而是“主持人 reaction 条 + 楼下街头喜剧现场”双层结构。上半条一直挂着 `COMEDY CREATOR` 和主...",
    "metrics": "播放量：2342W  点赞：—  评论：1465",
    "formula": "【上半屏先给 reaction 定调】+【下半屏用街头人群慢慢聚热】+【中后段把最意想不到的人也卷进狂欢】= reaction 群体闹剧型",
    "emotion": "情绪曲线：先围观、开始热闹、越看越乱、集体失控收尾"
  },
  {
    "sourceCaseId": "04070031",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070031",
    "title": "不同收入律师的类型",
    "dateKey": "0407",
    "bucket": "C",
    "summary": "Content Machine · 这条视频是非常标准的“收入梯度 + 同一角色模板递进”短喜剧。开头先从 `your lawyer when you make $25,000` ...",
    "metrics": "播放量：1963W  点赞：50W  评论：2084",
    "formula": "【先给最低配职业版本立笑点】+【同场景逐档升级预算】+【每一档都同步升级台词和结果】= 分层职业 parody",
    "emotion": "情绪曲线：先笑最低配、看见升级、开始期待下一档、被顶配阵容收割"
  },
  {
    "sourceCaseId": "04070028",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070028",
    "title": "时代变了",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "Ruslan & Olya · 这条视频的传播点不是单一事件，而是“把夫妻家务分工按年代切开看”的时代对比梗。开头直接打 `1980s`，男人甩手离开、女人留在厨房和地面劳动区...",
    "metrics": "播放量：3871W  点赞：42W  评论：6030",
    "formula": "【年代标签先给坐标】+【同一类家庭动作反复出现】+【每一段都重新分配角色】+【最后一段给出现代反差】= 年代对比型家庭",
    "emotion": "情绪曲线：识别年代、看懂分工、开始比较、反差落地"
  },
  {
    "sourceCaseId": "04070019",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070019",
    "title": "不是人人都适合理发",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "Immortal A.S · 这条视频不是现实短剧，而是一条带黑色幽默的动画微恐短片。开头先把“Barber not for all”打到脸上，再用蓝发理发师、燃烧头顶、怪物...",
    "metrics": "播放量：2764W  点赞：87W  评论：3467",
    "formula": "【一句反常识标题先下结论】+【日常理发店场景快速异化】+【客人一轮比一轮更离谱】+【夜间招牌收尾】= 动画怪谈型",
    "emotion": "情绪曲线：看懂梗、开始不对劲、越来越猎奇、黑色幽默落地"
  },
  {
    "sourceCaseId": "04070017",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070017",
    "title": "这个女孩也太狠心了",
    "dateKey": "0407",
    "bucket": "S",
    "summary": "STRONG MAN · 这条视频是很标准的“先让观众对一个角色产生负面判断，再用英雄式善举把情绪拉满”的公益感短片。开头轮椅男孩停在长楼梯顶端，女孩站在旁边却没有帮忙，...",
    "metrics": "播放量：1.1亿  点赞：68W  评论：1013",
    "formula": "【先给一个一眼可懂的困境】+【再给一个冷漠对照】+【最后用最直接的身体帮助解决问题】= respect hero 型",
    "emotion": "情绪曲线：先不爽、期待有人出手、被英雄动作击中、respect 收尾"
  },
  {
    "sourceCaseId": "04070016",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070016",
    "title": "坐等《Dhurandhar 2》上线",
    "dateKey": "0407",
    "bucket": "B",
    "summary": "Veer and Vaishali · 这条视频抓的不是复杂剧情，而是情侣 / 夫妻之间极其高共鸣的一个瞬间：有人说“我马上就好”，另一个人从期待出门看到怀疑人生。开头女人穿着睡衣在门...",
    "metrics": "播放量：4737W  点赞：79W  评论：463",
    "formula": "【先抛一句所有人都懂的“马上好”】+【把等待者留在同一空间里不断升级消磨方式】+【中途插时间牌】+【最后用完整造型反证前面的拖延】= 夫妻日常共鸣型",
    "emotion": "情绪曲线：先相信、开始怀疑、等到崩溃、被最终出场笑到"
  },
  {
    "sourceCaseId": "04070005",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070005",
    "title": "转发给你的同学",
    "dateKey": "0407",
    "bucket": "A",
    "summary": "Dean prin · 这条视频本质上是把“诚实的樵夫”寓言改写成校园语境的 moral-comedy。开头不是普通学生日常，而是一个拿着金色板子的神话角色从水里冒出来...",
    "metrics": "播放量：5520W  点赞：96W  评论：1057",
    "formula": "【先把经典寓言角色拍进现实】+【再把寓言道具换成学生熟悉物品】+【靠重复问答做诚实测试】+【最后切结果日做正向 payoff】= 校园寓言改写型",
    "emotion": "情绪曲线：先看懵、认出寓言、期待奖励、结果日满足"
  },
  {
    "sourceCaseId": "04070001",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04070001",
    "title": "和Chef Rush挑战超辣拉面",
    "dateKey": "0407",
    "bucket": "S",
    "summary": "albert_cancook · 这条视频把“监狱情境短剧”和“超辣拉面挑战”绑在一起，形成了非常高效的 food-comedy hook。开头先是铁栏杆、囚服和 Chef Ru...",
    "metrics": "播放量：1.8亿  点赞：302W  评论：2555",
    "formula": "【先给监狱栏杆这种高概念场景】+【马上切进食材和热板】+【用强势角色压迫感把辣度挑战做成对抗】= 食物短剧型爆款",
    "emotion": "情绪曲线：看懵设定、盯材料、辣度升级、反应收尾"
  },
  {
    "sourceCaseId": "04060164",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060164",
    "title": "对胜熙太过分了：OH MY GIRL 指定席的秘密",
    "dateKey": "0406",
    "bucket": "C",
    "summary": "패션탐정냥 · 这条视频不是剧情短剧，而是一条标准的 K-pop 观点短视频：先下判断，再用多个片段去证明。开头大字直接打出‘意图性推人站位’之类的指控性标题，...",
    "metrics": "播放量：1224W  点赞：10W  评论：1179",
    "formula": "【先下一个足够狠的偏爱 / 不公判断】+【连续拼接多个偶像片段】+【每一段都回扣同一个结论】= K-pop 观点争议型",
    "emotion": "情绪曲线：被标题刺到、看证据、开始站队、情绪确认"
  },
  {
    "sourceCaseId": "04060163",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060163",
    "title": "因为一点小贪心，错过了大鱼",
    "dateKey": "0406",
    "bucket": "C",
    "summary": "osomartyn · 这条视频的核心，是把一句老式寓言‘贪小失大’压缩成 13 秒身体喜剧。开头男人扛着一条巨大鱼走在路上，视觉上先把‘大收获’做得特别夸张。随后一个...",
    "metrics": "播放量：1178W  点赞：2W  评论：28",
    "formula": "【先给主角已经拿到的大收获】+【再用一个小诱饵把他注意力拉走】+【趁分神完成调包】= 贪小失大型",
    "emotion": "情绪曲线：看大鱼、起贪心、被调包、看懂寓言"
  },
  {
    "sourceCaseId": "04060076",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060076",
    "title": "生存技巧：实用又聪明",
    "dateKey": "0406",
    "bucket": "C",
    "summary": "Funny Club TV · 这条视频是一个特别短的 CGI 反转笑点。开头先给一个穿超人 T 恤、拄拐走路的男人，观众会自然把注意力放到他的伤脚上。接着一只蓝色小外星人突然...",
    "metrics": "播放量：1596W  点赞：—  评论：31",
    "formula": "【先给一个明显带伤的人类】+【插入一个离谱的小外星人】+【用最后一镜交换受伤身份】= CGI 反转型",
    "emotion": "情绪曲线：同情、惊吓、荒谬、反转"
  },
  {
    "sourceCaseId": "04060070",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060070",
    "title": "迟到进教室计划 [BEN EAGLE]",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "BEN EAGLE · 这条视频的核心，是把最普通的‘上课迟到’改写成一次夸张潜入。开头老师正在黑板前写字，教室秩序是稳定的；这时迟到学生出现在门窗边缘，观众马上知道他...",
    "metrics": "播放量：4569W  点赞：34W  评论：229",
    "formula": "【先给老师在场的高风险教室】+【把主角放到迟到不能进门的状态】+【再给一个离谱伪装和潜入路线】= 校园潜行喜剧型",
    "emotion": "情绪曲线：高风险、潜入、险些被抓、混过去了"
  },
  {
    "sourceCaseId": "04060048",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060048",
    "title": "Ronaldo是我朋友😎",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "The Savage Siblings · 这条视频的笑点非常直接：主角把电视里的 Ronaldo 当成了现实里的朋友。开头先让男生站在大电视旁边，屏幕里正好是 Ronaldo 的采访画面...",
    "metrics": "播放量：2934W  点赞：28W  评论：2070",
    "formula": "【先让真人和名人屏幕同框】+【再把单向电视画面当双向社交】+【最后给主角一个自我满足收口】= 名人熟人梗",
    "emotion": "情绪曲线：认脸、错愕、接受设定、满足收口"
  },
  {
    "sourceCaseId": "04060036",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060036",
    "title": "用隐形颜色疯狂作画 😱",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "Paintellectual PriyA · 这条视频是很标准的手作教程爆款结构：先抛出一个违背直觉的材料概念，再用连续演示把观众带到最后的 reveal。开头创作者直接举起颜料罐，说这是 ...",
    "metrics": "播放量：2085W  点赞：23W  评论：1955",
    "formula": "【先给违背直觉的材料名】+【展示看不清但隐约存在的过程】+【用高对比颜色慢慢显形】+【最后落到一句完整 reveal 文案】= 手作揭晓型",
    "emotion": "情绪曲线：好奇材料、盯过程、开始显形、成品满足"
  },
  {
    "sourceCaseId": "04060032",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060032",
    "title": "生存技巧：实用又聪明",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "Tony Outdoors · 这条视频的标题挂着 survival skills，但实际卖点完全不是技巧，而是‘你以为是户外日常，结果坑里冲出怪物’的假求生惊吓。开头镜头故意...",
    "metrics": "播放量：2332W  点赞：8W  评论：68",
    "formula": "【先假装是户外 / 求生视频】+【把危险点埋在人物屁股下】+【怪物突然冲出来】+【再升级成群怪】= 标题错位惊吓型",
    "emotion": "情绪曲线：不适、受惊、看反应、升级逃跑"
  },
  {
    "sourceCaseId": "04060028",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060028",
    "title": "我一大早就给我的小狗洗澡了 😱😍",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "Kitem AI Dogs Oficial · 这条视频是非常标准的萌宠 before / after 内容，只不过把‘洗澡’这件小事缩进了玩具屋一样的微型浴室。开头先给一只超小白狗站在地板上...",
    "metrics": "播放量：3916W  点赞：17W  评论：1089",
    "formula": "【先给超小萌宠本体】+【再给迷你浴室和泡泡】+【最后做 towel reveal】= 萌宠 grooming 型",
    "emotion": "情绪曲线：可爱、好奇、盯细节、被萌到"
  },
  {
    "sourceCaseId": "04060010",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060010",
    "title": "Alibaba 精选百万播放片段 p1981",
    "dateKey": "0406",
    "bucket": "S",
    "summary": "alibaba short · 这条视频不是正常故事，而是一种专门卖‘你根本猜不到下一帧会切去哪’的迷惑混剪。开头先给直升机里张牙舞爪的摔角明星，视觉强度已经够高；下一秒却突然...",
    "metrics": "播放量：1.1亿  点赞：37W  评论：94",
    "formula": "【先给高刺激画面】+【立刻切到低日常场景】+【再塞入比例错位特效】+【最后回到高刺激画面】= 迷惑混剪型",
    "emotion": "情绪曲线：炸一下、愣一下、再迷惑、接受乱切"
  },
  {
    "sourceCaseId": "04060004",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060004",
    "title": "妈妈的祈祷🙏☪️",
    "dateKey": "0406",
    "bucket": "A",
    "summary": "Islamic 24 Edit · 这条视频本质上是一个‘孩子心不在焉走向危险，最后靠母亲祈祷被护住’的宗教 moral short。开头先让男孩一边打电话一边在树边闲走，画面上直...",
    "metrics": "播放量：5159W  点赞：—  评论：3576",
    "formula": "【先给孩子分心状态】+【埋一个观众先看到的危险】+【再把母亲祈祷和守护意象叠上去】= 宗教情感教育型",
    "emotion": "情绪曲线：分心、预警、替他紧张、被护住"
  },
  {
    "sourceCaseId": "04060003",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060003",
    "title": "疯狂电池挑战🚀",
    "dateKey": "0406",
    "bucket": "B",
    "summary": "Renan Strong · 这条视频本质上是一个把‘电量高低’拟人化成体力差的街头 challenge。开头先在画面顶端挂出 1000% 和 10% 两个电池条，再把蓝线和...",
    "metrics": "播放量：4749W  点赞：80W  评论：1053",
    "formula": "【先给所有人都懂的电池图标】+【把高低电量改写成真人体力差】+【用 POV 绳线持续折腾挑战者】+【最后加关注口播和庆祝收口】= 街头互动挑战型",
    "emotion": "情绪曲线：读规则、看折腾、越玩越离谱、庆祝收口"
  },
  {
    "sourceCaseId": "04060001",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04060001",
    "title": "MS Dhoni 对决 Pollard🥶",
    "dateKey": "0406",
    "bucket": "A",
    "summary": "Rahul Munmun 2.0 · 这条视频本质上是一个“拿板球明星标签做人物模仿”的轻短剧。开头直接把黄衣角色标成 Dhoni、蓝衣角色标成 Pollard，观众不用猜就能立刻进...",
    "metrics": "播放量：5984W  点赞：33W  评论：345",
    "formula": "【先把人物直接标成球星】+【用几句对位口角立住赛场张力】+【再塞进第三个熟脸角色】= 板球明星模仿型",
    "emotion": "情绪曲线：认梗、对位、加人、收梗"
  },
  {
    "sourceCaseId": "04050029",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050029",
    "title": "MashAllah 🥰 神秘英雄的超神扑救 💕😘",
    "dateKey": "0405",
    "bucket": "B",
    "summary": "Israr Info Tv · 这条视频是非常典型的 CCTV respect 二创超短片，核心不靠故事铺垫，而是靠“一个看起来差点出事的瞬间，被旁边的人猛地一把救回来”。画面...",
    "metrics": "播放量：4740W  点赞：25W  评论：1025",
    "formula": "【先给 CCTV 真实视角】+【让危险在第一秒被看见】+【用一个极快救援动作解决问题】+【再用 respect 文案盖章】= 监控救援型爆款",
    "emotion": "情绪曲线：看见危险、屏住气、出手成功、松一口气、给予尊敬"
  },
  {
    "sourceCaseId": "04050028",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050028",
    "title": "洋大人给恶棍上了一课",
    "dateKey": "0405",
    "bucket": "B",
    "summary": "Angrej babu · 这条视频是典型的印度乡村公路“路霸找茬，最后反被教育”短剧。开头先给三个人在乡间路中央摆大石头，这种动作一看就知道不是在帮忙，而是在故意设障碍。...",
    "metrics": "播放量：3387W  点赞：28W  评论：93",
    "formula": "【先让反派做一个人人看得懂的坏动作】+【再给他们几秒钟嚣张 pose】+【后半段不用解释太多，直接把局势翻过去】+【最后用狼狈姿态收口】= 乡村路霸反杀型爆款",
    "emotion": "情绪曲线：看见找茬、反派得意、等待翻盘、反被教育、解气收尾"
  },
  {
    "sourceCaseId": "04050027",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050027",
    "title": "😱 白色沙发沾上辣椒油怎么清理？",
    "dateKey": "0405",
    "bucket": "B",
    "summary": "Vitalle · 这条视频表面上是“白色沙发沾到辣椒油怎么处理”的生活技巧题，实际上走的是“闯祸后先自救、再求生”的对话喜剧路线。开头先给一袋红油被撕开、男生脸色...",
    "metrics": "播放量：2664W  点赞：29W  评论：338",
    "formula": "【先给一个家庭灾难级的高反差问题】+【让主角徒劳补救几秒】+【主角承认自己完了】+【把解决方案从“清洁”切到“先哄房主”】= 闯祸求生型爆款",
    "emotion": "情绪曲线：出事、慌张擦拭、绝望承认、启动求生话术、暂时过关"
  },
  {
    "sourceCaseId": "04050020",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050020",
    "title": "#kpop #kpopdemonhunters #huntrix",
    "dateKey": "0405",
    "bucket": "B",
    "summary": "Rumi Siri · 这条视频是非常典型的 IP 角色 montage，不追求一条清晰因果线，而是让同一个紫发角色不断闯进新的小场景里，用快速切换维持存在感。开头先用...",
    "metrics": "播放量：2786W  点赞：75W  评论：391",
    "formula": "【先用 reveal 把主角亮出来】+【连续切几个风格不同的小场景】+【每段只保留最容易记住的人物动作】+【最后再给一个主角位收尾】= K-pop fan montage 型爆款",
    "emotion": "情绪曲线：亮相、轻松互动、可爱加码、视觉高潮、主角式收尾"
  },
  {
    "sourceCaseId": "04050018",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050018",
    "title": "猫咪Nika没能骗到我😉",
    "dateKey": "0405",
    "bucket": "B",
    "summary": "Princess Nika cat · 这条视频是很标准的“宠物不公平小剧场 + 智能设备补刀”，核心笑点不是猫咪多可爱，而是橘猫明明一直在搞小动作，却还想装得像自己什么都没做。开头先...",
    "metrics": "播放量：3682W  点赞：27W  评论：796",
    "formula": "【先给一眼看懂的不公平宠物关系】+【让主人像侦探一样开始怀疑】+【用设备和证据把坏行为坐实】+【最后给受委屈的一方一个明确解决方案】= 宠物轻破案型爆款",
    "emotion": "情绪曲线：先替白猫委屈、看主人怀疑、看证据坐实、等设备出手、终于放心"
  },
  {
    "sourceCaseId": "04050012",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050012",
    "title": "那个女孩为他改变了一切 🥺❤️",
    "dateKey": "0405",
    "bucket": "S",
    "summary": "Mert Boo · 这条视频本质上是一个泳池边的 costume-gag 视觉段子，真正卖点不是标题里的感情线，而是“一个普通泳池场景，怎么被一步步玩成大型 inf...",
    "metrics": "播放量：1亿  点赞：51W  评论：142",
    "formula": "【先给一个普通又稍微危险的现实起点】+【插入一个会打断现实的人物】+【连续用 costume / VFX 升级荒唐度】+【最后用最夸张的一幕收口】= 泳池视觉段子型爆款",
    "emotion": "情绪曲线：先担心、被打断、开始发疯、继续升级、荒唐收尾"
  },
  {
    "sourceCaseId": "04050011",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050011",
    "title": "零食 vs 电影片头 - 第9部分",
    "dateKey": "0405",
    "bucket": "A",
    "summary": "Bayashi TV · 这条视频是 Bayashi 非常擅长的“食物工艺 + 童年电影记忆”融合玩法。开头先给出一台正在播放 20th Century Fox 片头的电...",
    "metrics": "播放量：6046W  点赞：69W  评论：2979",
    "formula": "【先给一个人人都认识的文化符号】+【立刻摆出零食材料】+【把制作过程压成连续的质感段落】+【最后一定咬碎或切开】= Bayashi 式手作零食爆款",
    "emotion": "情绪曲线：熟悉感、好奇怎么做、期待成型、成品出现、爽快咬碎"
  },
  {
    "sourceCaseId": "04050009",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050009",
    "title": "在评判我之前：是我救了他的命",
    "dateKey": "0405",
    "bucket": "A",
    "summary": "The Gabriels · 这条视频是非常典型的欧美情侣 / 路边 prank 反转段子，但它的聪明点在于把“女生下手太重”重新包装成“其实她是在救你”。开头先用屏幕文案 ...",
    "metrics": "播放量：5639W  点赞：50W  评论：4176",
    "formula": "【开头先用一句文案把观众带偏】+【安排一个突然扑上来的外部威胁】+【让主角用过猛动作制造误会】+【最后用一句感谢翻回真实动机】= 欧美对白反转型爆款",
    "emotion": "情绪曲线：先入为主、事态升级、觉得她太狠、对方逃跑、真相翻回"
  },
  {
    "sourceCaseId": "04050005",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050005",
    "title": "我的小狗又来放松享福啦 🐶✨",
    "dateKey": "0405",
    "bucket": "A",
    "summary": "PetsGoodis · 这条视频属于非常标准的“宠物护理沉浸流”，不靠剧情反转，而是靠护理步骤一个接一个往上堆，把“小狗被宠上天”的感觉做到极致。开头先给一只毛茸茸的小...",
    "metrics": "播放量：8592W  点赞：132W  评论：5823",
    "formula": "【先给一只足够乖又足够软萌的宠物正脸】+【把护理动作拆成很多很细的小步骤】+【持续换工具但不换情绪】+【最后回到更干净更蓬松的成品状态】= 沉浸式萌宠护理型爆款",
    "emotion": "情绪曲线：被萌到、进入照料、越看越放松、觉得它太幸福了、满足收尾"
  },
  {
    "sourceCaseId": "04050003",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050003",
    "title": "#kpop #kpopdemonhunters #huntrix",
    "dateKey": "0405",
    "bucket": "S",
    "summary": "猎魔女团-欢乐组合 · 这条视频不是强剧情短剧，而是典型的 fan-cosplay 角色反差段子。它把一个最普通的电梯进出场景，改造成“紫发怪咖乱入 + 花裙主角稳住场...",
    "metrics": "播放量：1.4亿  点赞：104W  评论：518",
    "formula": "【先给一个极普通的现实场景】+【让一个最不属于这个场景的角色突然闯入】+【继续追加一个新角色放大 awkward 感】+【最后用同框 pose 收口】= fan cosplay 角色乱...",
    "emotion": "情绪曲线：正常、突然乱入、尴尬好笑、继续加人、轻松合影"
  },
  {
    "sourceCaseId": "04050002",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04050002",
    "title": "真的假的恶作剧",
    "dateKey": "0405",
    "bucket": "S",
    "summary": "leo2 · 这条视频本质上是一个“名媛派对场景里的真假伤害恶作剧”，靠的是先制造一秒真出事的错觉，再立刻用更夸张的反击把节奏翻过去。开头先让金色亮片裙女生拿...",
    "metrics": "播放量：1.1亿  点赞：41W  评论：174",
    "formula": "【先给一个像真出事的恶作剧动作】+【把受害者放在最怕脏、最怕毁的白净场景里】+【旁观者立刻嫌弃这招太低级】+【再用更狠的反击把整人者反杀】= 闺蜜高反差 prank 爆款",
    "emotion": "情绪曲线：预感搞事、真被吓到、看热闹、轮到反击、爽点收口"
  },
  {
    "sourceCaseId": "04040016",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040016",
    "title": "全网爆火挑战！谁能赢？",
    "dateKey": "0404",
    "bucket": "B",
    "summary": "Kosar Skills · 这条视频是极短挑战类 Shorts 的标准形态：开头先把规则做成一眼能懂的分数面板，再把气球和泡沫球放到镜头最前面，让观众立刻进入“这一轮谁赢”...",
    "metrics": "播放量：3396W  点赞：11W  评论：289",
    "formula": "【顶部先给输赢问题】+【前景放可形变道具】+【第一人称双手立刻上手】+【用计分条持续推进】+【结尾补 Subscribe/Like】= 极短挑战类 Shorts 模板",
    "emotion": "情绪曲线：看规则、站队、等结果、分数推进、快速收口"
  },
  {
    "sourceCaseId": "04040014",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040014",
    "title": "美国女孩第一次吃拉面",
    "dateKey": "0404",
    "bucket": "B",
    "summary": "PixelWave · 这条视频并不是简单的“第一次吃拉面”试吃反应，更像是一段带电影感的小情绪片段：雨夜里，一个情绪崩溃的金发女孩闯进小店，先问“这里有人吗”，接着哭...",
    "metrics": "播放量：2204W  点赞：94W  评论：3592",
    "formula": "【先给一个在雨夜里崩溃求助的人】+【让陌生店铺提供热食和最小善意】+【用吃面过程完成情绪缓和】+【最后再加一个“我想回报这份善意”的动作】= 治愈向影视剪辑爆款",
    "emotion": "情绪曲线：无助闯入、崩溃倾诉、被喂饱、慢慢平静、想回应善意、关系升温"
  },
  {
    "sourceCaseId": "04040011",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040011",
    "title": "体贴的老公是每个女孩的愿望",
    "dateKey": "0404",
    "bucket": "B",
    "summary": "Aswathy & Amarnath · 这条视频是典型的印度家庭情感向短剧，不靠对白，而靠“一个人把所有家务扛完”到“另一个人默默接手”的情绪反差收口。前半段先把妻子的疲惫感铺得很满：...",
    "metrics": "播放量：2470W  点赞：40W  评论：993",
    "formula": "【先连续展示一个人扛完所有家务】+【让观众明确感知到她真的撑不住】+【不要立刻给甜】+【等到她睡着后再让伴侣默默接手】= 家庭情感反差型爆款短剧",
    "emotion": "情绪曲线：忙碌、更累、被家务包围、撑不住、短暂停滞、温柔接手"
  },
  {
    "sourceCaseId": "04040009",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040009",
    "title": "生存技能：实用又聪明",
    "dateKey": "0404",
    "bucket": "A",
    "summary": "Tony Outdoors · 这条视频是非常典型的 bushcraft / survival Shorts：先用一个让人头皮发麻的痛点开场，再用一个极简“户外小技巧”把问题解...",
    "metrics": "播放量：6175W  点赞：27W  评论：365",
    "formula": "【先给极强不适痛点】+【让人物明确意识到问题】+【用一个简洁动作进入处理】+【留下足够强的 before/after 对比】= 户外生存技巧型爆款",
    "emotion": "情绪曲线：不适冲击、想赶走、期待办法、开始处理、对比收口"
  },
  {
    "sourceCaseId": "04040005",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040005",
    "title": "Harley Quinn's balloon球",
    "dateKey": "0404",
    "bucket": "B",
    "summary": "Untitled Joker · 这条视频本质上是一个靠妆造和道具撑起来的 cosplay 轻剧情短片。开头先把观众拉进车内，让哈莉风格的女孩、脸上有涂鸦妆的白西装男，以及车外戴...",
    "metrics": "播放量：3249W  点赞：26W  评论：267",
    "formula": "【先在车内近景亮妆造】+【用便宜但显眼的气球道具制造互动】+【再把人物拉到停车场外全身亮相】+【补第二组角色扩阵容】= cosplay 氛围型爆款",
    "emotion": "情绪曲线：认角色、看互动、气氛升高、下车亮相、阵容扩张、pose 收口"
  },
  {
    "sourceCaseId": "04040004",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040004",
    "title": "蜡笔小新和朋友玩具ASMR",
    "dateKey": "0404",
    "bucket": "B",
    "summary": "Shin.chan6996 · 这条视频属于典型的玩具 ASMR 玩法，但它没有直接从“清洗玩具”开始，而是先丢出一个有点恶搞的脏污设定：蜡笔小新站在粉色浴室前，旁边先出现一坨...",
    "metrics": "播放量：3481W  点赞：15W  评论：55",
    "formula": "【熟悉卡通玩具】+【先给一点脏污恶搞设定】+【立刻推进泡泡清洗】+【连续捞出隐藏部件】+【最后还原完整形态】= 儿童向玩具 ASMR 爆款",
    "emotion": "情绪曲线：猎奇、进入泡泡、好奇揭示、连续满足、完整还原"
  },
  {
    "sourceCaseId": "04040002",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04040002",
    "title": "捉迷藏抓捕",
    "dateKey": "0404",
    "bucket": "A",
    "summary": "CEO MASTERPIECE · 这条视频的核心不是剧情对白，而是一个非常直给的低成本 VFX 藏身点子。开头先让条纹衣男站在墙边，观众会以为这只是普通 pose；下一秒他整个人...",
    "metrics": "播放量：8991W  点赞：52W  评论：237",
    "formula": "【一堵容易合成的墙】+【先让角色站得不自然】+【快速揭露贴墙规则】+【让追捕者进入验证】+【再换第二个人复制玩法】= 低成本 VFX 躲藏型爆款",
    "emotion": "情绪曲线：好奇站位、规则揭露、紧张搜查、连续躲过、再次复制、爽感闭环"
  },
  {
    "sourceCaseId": "hard-water-joint-family-hair-ad",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030024",
    "title": "大家庭我能适应🤣 但硬水不行💁‍♀️ 用Clinic Plus蛋白护发",
    "dateKey": "0403",
    "bucket": "B",
    "summary": "Dolly Pathak · 这条视频是非常典型的印度本土生活流广告短剧：前半段先用“新媳妇嫁进 joint family”的密集日常，把观众拉进大家庭共鸣语境；后半段再把真...",
    "metrics": "播放量：2793W  点赞：34W  评论：313",
    "formula": "【本土女性熟悉的生活情境】+【先让角色手忙脚乱】+【把真正痛点说成 hard water 伤发】+【更懂生活的人递出产品】+【洗发功效镜头 + 口播背书】= 本土 personal c...",
    "emotion": "情绪曲线：生活共鸣、手忙脚乱、痛点爆发、找到原因、接受解法、看到效果、记住产品"
  },
  {
    "sourceCaseId": "quinoa-food-shoot-bts",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030020",
    "title": "连藜麦也能抢镜✨😅",
    "dateKey": "0403",
    "bucket": "A",
    "summary": "Food for shot · 这条视频不是菜谱教学，而是一条 food cinematography 的幕后炫技短片。开头直接用一大团藜麦在镜头前炸开，把这种本来很朴素的食材...",
    "metrics": "播放量：6805W  点赞：87W  评论：2508",
    "formula": "【普通食材先来一个视觉奇观】+【马上露出相机与布景】+【创作者认真操作幕后过程】+【微距颗粒质感放大】+【成品碗 + 包装露出收尾】= food cinematography 幕后型爆...",
    "emotion": "情绪曲线：视觉惊艳、好奇幕后、看到搭景、质感升级、成片兑现、满足收尾"
  },
  {
    "sourceCaseId": "dog-tiger-happiness-bodypaint",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030016",
    "title": "幸福的秘密只是家人和狗吗？",
    "dateKey": "0403",
    "bucket": "A",
    "summary": "Carlos Reig · 这条视频不是写实家庭短剧，而是一条超现实 body-paint 动物寓言。开头男主赤膊站在花园里，胸前直接画着狗脸和哭泣婴儿脸，手里还拿着牵引器...",
    "metrics": "播放量：6002W  点赞：24W  评论：149",
    "formula": "【幸福命题先抛出】+【狗/家庭等符号一次性摆上身】+【更野的动物幻想突然闯入】+【中段情绪反复横跳】+【最后用混种变装造型收尾】= 超现实 body-paint 爆款 Shorts",
    "emotion": "情绪曲线：命题抛出、荒诞闯入、兴奋上头、结果摇摆、情绪崩塌、混种收尾"
  },
  {
    "sourceCaseId": "when-luggage-gets-loaded-on-plane",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030015",
    "title": "行李被塞进飞机时🧳✈️ #shorts",
    "dateKey": "0403",
    "bucket": "B",
    "summary": "Pedro Palencia · 这条视频不是讲一个完整机场故事，而是把几乎所有坐过飞机的人都想过的一个念头直接视觉化：托运行李是不是在下面被乱扔。开头先用飞机舷窗视角和西语标题...",
    "metrics": "播放量：4596W  点赞：30W  评论：733",
    "formula": "【飞机窗边 POV】+【所有人都懂的托运行李焦虑】+【外景粗暴装卸具象化】+【内景乘客逐渐石化】+【周围人若无其事的反差】= 旅行共鸣型爆款 reaction Shorts",
    "emotion": "情绪曲线：情境识别、共鸣担心、看到实锤、情绪绷紧、表情失控、反差收尾"
  },
  {
    "sourceCaseId": "shrimp-vs-hair-dryer",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030013",
    "title": "虾 vs 吹风机",
    "dateKey": "0403",
    "bucket": "B",
    "summary": "DoubleBite · 这条视频不是传统做菜教程，而是一条极简猎奇实验型 Shorts。开头直接把一只整虾竖起来，同时把吹风机和 `1m / 3m / 10m / 1h...",
    "metrics": "播放量：3699W  点赞：56W  评论：1389",
    "formula": "【反常识家电实验题目】+【整只食材直接入镜】+【1m/3m/10m/1h 时间阶梯】+【颜色与熟度逐步变化】+【最终真人试吃验证】= 猎奇验证型爆款 Shorts",
    "emotion": "情绪曲线：荒唐好奇、观察变化、半信半疑、继续加码、首次验证、明显惊讶、终极确认、满足收尾"
  },
  {
    "sourceCaseId": "parkour-football-balloon-pov",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030010",
    "title": "新款跑酷足球⚽️+气球🎈爆掉了 #parkour #football #pov",
    "dateKey": "0403",
    "bucket": "B",
    "summary": "Hemant Kushwah parkour · 这条视频本质上不是人物对白短剧，而是一条第一人称 POV parkour 球类挑战。开头先把足球、彩球和粉色气球围着一个地洞摆开，直接制造出“这...",
    "metrics": "播放量：3912W  点赞：18W  评论：75",
    "formula": "【地洞 + 一圈道具的视觉奇观】+【第一人称双手入镜】+【静态摆阵快速切入跑酷追球】+【楼梯/走廊/平台连续过关】+【结尾双道具回收】= POV 动作挑战型爆款 Shorts",
    "emotion": "情绪曲线：视觉好奇、洞口悬念、准备开玩、任务启动、快速追击、空间风险上升、双道具回收、完成感收尾"
  },
  {
    "sourceCaseId": "school-magic-trick-boy",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030009",
    "title": "嘿给你变个魔术😅🌀!! #shorts #viral #funny",
    "dateKey": "0403",
    "bucket": "B",
    "summary": "Aryan S07 · 这条视频本质上不是复杂反转剧情，而是一个“学校里总有那么一个爱变魔术的男生”的人物型短剧。开头直接用口播和屏幕文案把 archetype 立住：...",
    "metrics": "播放量：4468W  点赞：38W  评论：582",
    "formula": "【学校里熟悉的人物 archetype】+【口播先立角色】+【同学围观接球】+【低成本小把戏连续展示】+【主角极度自信的表演状态】= 校园人物记忆型 Shorts",
    "emotion": "情绪曲线：标签识别、好奇围观、听他吹、盯手看、轻微震惊、更多人加入、继续表演、熟悉感收尾"
  },
  {
    "sourceCaseId": "schoolboy-bike-showoff-backfires",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/04030005",
    "title": "结局😂😂  /  印度家庭",
    "dateKey": "0403",
    "bucket": "S",
    "summary": "PR PRESENTS · 这条视频本质上是一个“上学路先被恶作剧拖慢，最后差点迟到并被老师公开训斥”的校园短剧。开头男孩刚准备骑车上学，就被后方一名男生拿着水袋砸中，节奏...",
    "metrics": "播放量：1.1亿  点赞：74W  评论：411",
    "formula": "【上学路突然被恶作剧偷袭】+【主角怕迟到、急着追老师】+【关键时刻掉链子】+【老师接管】+【课堂公开训斥】= 校园迟到压力升级型 Shorts",
    "emotion": "情绪曲线：平静上学、突然受击、赶路焦虑、旁人目击、机械失控、追老师、公开尴尬"
  },
  {
    "sourceCaseId": "when-he-realized-the-level-of-his-dad",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/03280001",
    "title": "他终于意识到爸爸的段位了",
    "dateKey": "0328",
    "bucket": "A",
    "summary": "RiseUp Shorts HQ · 男孩一开始只是站在路边轻松等待，随后被一辆黑色超跑吸引，注意力越来越集中，表情从开心变成震惊。真正的反转在后半段发生——他意识到这辆极具压迫感和...",
    "metrics": "播放量：7667W  点赞：121W  评论：4544",
    "formula": "【普通孩子等待场景】+【高价值资源突然出现】+【主角认知升级反应】+【亲属身份反转确认】= 身份反差型爆款 Shorts",
    "emotion": "情绪曲线：轻松、注意、惊讶、震撼、确认、温暖收束"
  },
  {
    "sourceCaseId": "03240012",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/03240012",
    "title": "妹妹简直是头号克星",
    "dateKey": "0324",
    "bucket": "B",
    "summary": "Paras valecha · 这条视频是非常典型的印度家庭短喜剧，靠一句屏幕文案和“妹妹就是天敌”这个关系梗完成整个笑点。开头先在屏幕上写出 `Kuch nhi bs Nav...",
    "metrics": "播放量：4536W  点赞：31W  评论：533",
    "formula": "【一句屏幕文案先交代规矩】+【妹妹立刻出现拆台】+【从口头坚持推进到真实诱惑】+【在最熟的人面前迅速失守】= 本土兄妹关系喜剧",
    "emotion": "情绪曲线：立规矩、被盯上、继续硬撑、诱惑加重、关系压制、笑点落地"
  },
  {
    "sourceCaseId": "retro-ai-cat",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/03240011",
    "title": "好心人补送掉落甜点",
    "dateKey": "0324",
    "bucket": "B",
    "summary": "VIRUM · 视频讲的是一个极其简单但极容易打动人的小事件：母亲带着孩子在路边冰淇淋车买了甜筒，结果甜筒刚到手就掉到地上，孩子情绪瞬间崩塌。母亲虽然在安慰，但...",
    "metrics": "播放量：2825W  点赞：17W  评论：195",
    "formula": "【日常小确幸】+【瞬间失去】+【孩子的真实失落】+【陌生人的超预期补偿】= 暖心型爆款短视频",
    "emotion": "情绪曲线：轻松、意外、停滞、委屈、被看见、被补偿、被治愈"
  },
  {
    "sourceCaseId": "03240006",
    "sourceUrl": "https://lulujai.com/zh-CN/shorts/viral/03240006",
    "title": "被开了1000卢比罚单",
    "dateKey": "0324",
    "bucket": "A",
    "summary": "Loveneet Valecha · 这条视频是非常典型的印度家庭生活流搞笑短剧。开头先让年轻男生拎着袋子回家，脸上的表情就像出了事；镜头马上切到爸爸追问、妈妈补刀，观众很快知道真正...",
    "metrics": "播放量：5062W  点赞：92W  评论：2086",
    "formula": "【回家先露出闯祸表情】+【父母立刻追问】+【把错误具体化成一张罚单】+【厨房日常继续推进】+【最后把成本算到一盘家常饭上】= 印度本土家庭生活流搞笑短剧",
    "emotion": "情绪曲线：心虚回家、被追问、罚单曝光、父母补刀、厨房继续日常、笑点收口"
  }
]

export function getViralCaseCorpusCard(id: string | null | undefined): ViralCaseCorpusCard | null {
  return viralCaseCorpus.find(card => card.sourceCaseId === id) || null;
}

