import test from 'node:test';
import assert from 'node:assert/strict';
import {
  ADAPTER_VERSION,
  PROVIDER_ADAPTERS,
  PROVIDER_ROUTING_ALGORITHM_VERSION,
  PROVIDER_ROUTING_REGISTRY,
  buildProviderRouting,
  buildProviderRoutingReport,
  extractProviderRequirements,
} from '../src/lib/provider-routing.ts';

const capabilityKeys = ['TEXT_TO_IMAGE', 'REFERENCE_IMAGE', 'IMAGE_EDIT', 'MULTI_REFERENCE', 'TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO', 'VIDEO_CONTINUATION', 'START_FRAME', 'END_FRAME', 'REFERENCE_VIDEO', 'IDENTITY_REFERENCE', 'STYLE_REFERENCE', 'EXACT_TEXT', 'TRANSPARENT_BACKGROUND', 'AUDIO'];
const model = (modelId, overrides = {}) => ({ modelId, providerId: overrides.providerId || 'minimax', displayName: modelId, availability: overrides.availability || 'AVAILABLE', verification: overrides.verification || 'VERIFIED', capabilities: capabilityKeys.map(key => ({ key, support: 'UNSUPPORTED', verification: 'VERIFIED', source: 'MANUAL_CONFIG', capabilityVersion: 'provider-capability-v1', ...(overrides.capabilities?.[key] || {}) })), adapterId: overrides.adapterId || ADAPTER_VERSION.minimax, configurationVersion: 'fixture-v1', telemetry: { priceDataState: 'UNKNOWN', qualityDataState: 'UNKNOWN', speedDataState: 'UNKNOWN' } });
const spec = (overrides = {}) => ({ specificationId: 'vgs:fixture', specificationVersion: 'visual-generation-specification-v1', storyboardId: 'storyboard-1', sceneId: 'scene-1', shotId: 'shot-1', generationRoute: 'TEXT_TO_IMAGE', purpose: 'SHOW_SUBJECT', inputState: 'TEXT_ONLY', startState: { subjects: ['a host'], assetIds: [], environment: 'studio', time: null, objectStates: [], positions: [], expressions: [], actionsAtState: [], evidenceContent: [], composition: null, styleReferenceIds: [] }, desiredChange: [], stateDelta: [], endState: null, preserveUnchanged: [], continuityLocks: [], referenceDependencies: [], negativeConstraints: [], composition: { framing: 'MEDIUM', subjectPlacement: null, aspectRatio: null, source: 'UNAVAILABLE' }, camera: { motion: 'STATIC', direction: null, source: 'DERIVED' }, motion: null, duration: { minSeconds: 4, maxSeconds: 8, source: 'SHOT_REQUIREMENT', calibrationStatus: 'CALIBRATION_REQUIRED' }, aspectRatio: { value: null, source: 'USER_INPUT_REQUIRED' }, complexity: { state: 'STATIC', independentActors: 0, sequentialActions: 0, objectStateTransitions: 0, environmentChanges: 0, requiresEndState: false, rationale: [], calibrationStatus: 'CALIBRATION_REQUIRED' }, units: [{ unitId: 'vgs:fixture:unit:1', index: 1, route: 'TEXT_TO_IMAGE', inputState: 'TEXT_ONLY', startState: { subjects: ['a host'], assetIds: [], environment: 'studio', time: null, objectStates: [], positions: [], expressions: [], actionsAtState: [], evidenceContent: [], composition: null, styleReferenceIds: [] }, desiredChange: [], endState: null, intermediateStateId: null, dependsOnUnitIds: [], requiredAssetIds: [], referenceDependencyIds: [], readiness: 'READY_FOR_MODEL_ADAPTATION', provenance: { specificationId: 'vgs:fixture', shotId: 'shot-1', sceneId: 'scene-1' } }], evidenceSemantics: { mode: 'ILLUSTRATIVE_ONLY', claimIds: [], evidenceIds: [], requiredSourceAssetIds: [], note: '' }, confidence: 'HIGH', reasons: [], risks: [], blockers: [], readiness: 'READY_FOR_MODEL_ADAPTATION', dataAvailability: {}, provenance: { specificationId: 'vgs:fixture', storyboardId: 'storyboard-1', sceneId: 'scene-1', shotId: 'shot-1', scriptId: 'script-1', assetPackageId: 'asset-package-1', assetIds: [], referencePackIds: [], claimIds: [], evidenceIds: [], algorithmVersions: [], capturedAt: null, snapshotId: null, calibrationStatus: 'CALIBRATION_REQUIRED' }, ...overrides });
const registry = (...models) => ({ registryVersion: 'fixture-registry-v1', capabilityVersion: 'provider-capability-v1', providers: models.map(item => ({ providerId: item.providerId, displayName: item.providerId, generationDomains: ['IMAGE', 'VIDEO'], availability: 'AVAILABLE', verification: 'VERIFIED', modelIds: [item.modelId], adapterId: item.adapterId, configurationVersion: 'fixture-v1' })), models });
const withCaps = (keys, overrides = {}) => Object.fromEntries(keys.map(key => [key, { support: 'SUPPORTED', verification: 'VERIFIED', source: 'MANUAL_CONFIG', ...overrides[key] }]));

test('simple text-to-image yields a compatible set and deterministic AUTO recommendation', () => { const a = model('fixture:minimax:h3', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const b = model('fixture:seedance:2', { providerId: 'seedance', adapterId: ADAPTER_VERSION.seedance, capabilities: withCaps(['TEXT_TO_IMAGE']) }); const result = buildProviderRouting({ specification: spec(), registry: registry(a, b), capturedAt: '2026-09-02T00:00:00.000Z' }); assert.equal(result.decisions[0].recommendedModelId, a.modelId); assert.deepEqual(result.decisions[0].compatibleModels.map(item => item.modelId), [a.modelId, b.modelId]); });
test('reference image and hard END state become explicit requirements', () => { const item = spec({ generationRoute: 'IMAGE_TO_VIDEO', inputState: 'REFERENCE_IMAGE', endState: { subjects: [], assetIds: ['start'], environment: null, time: null, objectStates: [], positions: [], expressions: [], actionsAtState: ['done'], evidenceContent: [], composition: null, styleReferenceIds: [] }, referenceDependencies: [{ dependencyId: 'dep-1', assetId: 'start', referencePackId: null, referenceIds: ['ref-1'], required: true, role: 'IDENTITY', state: 'AVAILABLE' }], complexity: { ...spec().complexity, state: 'SIMPLE', requiresEndState: true } }); const requirements = extractProviderRequirements(item); assert.ok(requirements.requirements.some(req => req.key === 'REFERENCE_INPUT' && req.hard)); assert.ok(requirements.requirements.some(req => req.key === 'END_STATE' && req.hard)); });
test('unsupported hard capability is incompatible and never auto-selected', () => { const item = buildProviderRouting({ specification: spec(), registry: registry(model('fixture:unsupported')), capturedAt: null }); assert.equal(item.decisions[0].recommendedModelId, null); assert.equal(item.decisions[0].blockers[0].code, 'NO_COMPATIBLE_PROVIDER'); assert.equal(item.decisions[0].rejectedModels[0].state, 'INCOMPATIBLE'); });
test('unknown hard capability is UNVERIFIED rather than compatible', () => { const unknown = model('fixture:unknown', { verification: 'UNVERIFIED', capabilities: { TEXT_TO_IMAGE: { support: 'UNKNOWN', verification: 'UNKNOWN' } } }); const item = buildProviderRouting({ specification: spec(), registry: registry(unknown) }); assert.equal(item.decisions[0].recommendedModelId, null); assert.equal(item.decisions[0].rejectedModels[0].state, 'UNVERIFIED'); });
test('soft style lock can degrade with an explicit risk', () => { const item = spec({ preserveUnchanged: [{ constraintId: 'style-1', type: 'STYLE', description: 'keep style', strength: 'SOFT', sourceLockId: null }] }); const candidate = model('fixture:soft', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const result = buildProviderRouting({ specification: item, registry: registry(candidate) }); assert.equal(result.decisions[0].recommendedModelId, candidate.modelId); assert.equal(result.decisions[0].compatibleModels[0].state, 'COMPATIBLE_WITH_DEGRADATION'); assert.ok(result.decisions[0].risks.some(risk => risk.code === 'CONTINUITY_DEGRADATION')); });
test('non-generative evidence does not route to a provider', () => { const item = spec({ generationRoute: 'SCREEN_CAPTURE', evidenceSemantics: { mode: 'REAL_SOURCE_REQUIRED', claimIds: [], evidenceIds: ['e-1'], requiredSourceAssetIds: ['asset-1'], note: 'real' } }); const result = buildProviderRouting({ specification: item, registry: registry(model('fixture:video', { capabilities: withCaps(['TEXT_TO_VIDEO']) })) }); assert.equal(result.decisions[0].recommendedModelId, null); assert.equal(result.decisions[0].fallbackChain[0].state, 'NOT_APPLICABLE'); });
test('manual compatible MiniMax override is accepted and preserved', () => { const candidate = model('provider:minimax:model:h3', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const result = buildProviderRouting({ specification: spec(), registry: registry(candidate), mode: 'USER_SELECTED', selectedModelId: candidate.modelId }); assert.equal(result.decisions[0].userOverride.result, 'ACCEPTED'); assert.equal(result.decisions[0].recommendedModelId, candidate.modelId); });
test('manual compatible Seedance override is accepted and preserved', () => { const candidate = model('provider:seedance:model:2', { providerId: 'seedance', adapterId: ADAPTER_VERSION.seedance, capabilities: withCaps(['TEXT_TO_IMAGE']) }); const result = buildProviderRouting({ specification: spec(), registry: registry(candidate), mode: 'USER_SELECTED', selectedModelId: candidate.modelId }); assert.equal(result.decisions[0].userOverride.result, 'ACCEPTED'); });
test('manual incompatible override is rejected without changing the specification', () => { const candidate = model('provider:minimax:model:h3'); const result = buildProviderRouting({ specification: spec(), registry: registry(candidate), mode: 'USER_SELECTED', selectedModelId: candidate.modelId }); assert.equal(result.decisions[0].userOverride.result, 'OVERRIDE_INCOMPATIBLE'); assert.equal(result.decisions[0].recommendedModelId, null); assert.equal(spec().generationRoute, 'TEXT_TO_IMAGE'); });
test('fallback chain records accepted and rejected candidates explicitly', () => { const primary = model('fixture:primary'); const fallback = model('fixture:fallback', { providerId: 'seedance', adapterId: ADAPTER_VERSION.seedance, capabilities: withCaps(['TEXT_TO_IMAGE']) }); const result = buildProviderRouting({ specification: spec(), registry: registry(primary, fallback), mode: 'FALLBACK', selectedModelId: fallback.modelId, fallbackModelIds: [primary.modelId, fallback.modelId] }); assert.equal(result.decisions[0].fallbackChain[0].state, 'REJECTED'); assert.equal(result.decisions[0].fallbackChain[1].state, 'AVAILABLE'); assert.ok(result.decisions[0].fallbackChain[1].changes.includes('MODEL_CHANGED')); });
test('hard-loss fallback is rejected by compatibility', () => { const candidate = model('fixture:no-route'); const result = buildProviderRouting({ specification: spec(), registry: registry(candidate), mode: 'FALLBACK', selectedModelId: candidate.modelId, fallbackModelIds: [candidate.modelId] }); assert.equal(result.decisions[0].fallbackChain[0].state, 'REJECTED'); });
test('multi-stage units produce independent decisions with lineage', () => { const first = model('fixture:first', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const second = model('fixture:second', { providerId: 'seedance', adapterId: ADAPTER_VERSION.seedance, capabilities: withCaps(['IMAGE_TO_VIDEO', 'START_FRAME']) }); const item = spec({ generationRoute: 'MULTI_STAGE_GENERATION', complexity: { ...spec().complexity, state: 'MULTI_STAGE', requiresEndState: false }, units: [{ ...spec().units[0], unitId: 'vgs:fixture:unit:1', route: 'TEXT_TO_IMAGE' }, { ...spec().units[0], unitId: 'vgs:fixture:unit:2', route: 'IMAGE_TO_VIDEO', inputState: 'START_FRAME', dependsOnUnitIds: ['vgs:fixture:unit:1'] }] }); const result = buildProviderRouting({ specification: item, registry: registry(first, second) }); assert.equal(result.provenance.generationUnitIds.length, 2); });
test('provider adapter serialization retains lineage and canonical state references', () => { const candidate = model('fixture:adapter', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const routing = buildProviderRouting({ specification: spec(), registry: registry(candidate) }); const request = routing.requests[0]; assert.equal(request.metadata.sourceSpecificationId, 'vgs:fixture'); assert.equal(request.metadata.sourceGenerationUnitId, 'vgs:fixture:unit:1'); assert.equal(request.metadata.routingDecisionId, routing.decisions[0].decisionId); assert.ok(request.payload.semanticPrompt); assert.equal(request.providerId, 'minimax'); });
test('serialization hard loss blocks readiness', () => { const candidate = model('fixture:loss', { capabilities: withCaps(['TEXT_TO_IMAGE', 'END_FRAME']) }); const endState = { subjects: [], assetIds: [], environment: null, time: null, objectStates: [], positions: [], expressions: [], actionsAtState: [], evidenceContent: [], composition: null, styleReferenceIds: [] }; const item = spec({ endState, complexity: { ...spec().complexity, requiresEndState: true } }); const routing = buildProviderRouting({ specification: item, registry: registry(candidate) }); const request = { ...routing.requests[0], metadata: { ...routing.requests[0].metadata, representation: { ...routing.requests[0].metadata.representation, endState: 'UNKNOWN' } } }; const validation = PROVIDER_ADAPTERS.minimax.validateSerializedRequest(request, item); assert.equal(validation.state, 'HARD_LOSS'); assert.equal(validation.ready, false); });
test('serialization soft loss is visible without becoming hard loss', () => { const candidate = model('fixture:soft-loss', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const item = spec({ preserveUnchanged: [{ constraintId: 'style-1', type: 'STYLE', description: 'keep style', strength: 'SOFT', sourceLockId: null }] }); const routing = buildProviderRouting({ specification: item, registry: registry(candidate) }); const request = { ...routing.requests[0], metadata: { ...routing.requests[0].metadata, representation: { ...routing.requests[0].metadata.representation, styleLocks: 'UNKNOWN' } } }; const validation = PROVIDER_ADAPTERS.minimax.validateSerializedRequest(request, item); assert.equal(validation.state, 'SOFT_LOSS'); assert.equal(validation.ready, true); });
test('grounded registry keeps model configuration separate from capability verification', () => { const minimax = PROVIDER_ROUTING_REGISTRY.models.find(item => item.providerId === 'minimax'); const seedance = PROVIDER_ROUTING_REGISTRY.models.find(item => item.providerId === 'seedance'); assert.equal(minimax.verification, 'CONFIGURED'); assert.equal(seedance.verification, 'CONFIGURED'); assert.equal(minimax.availability, 'DISABLED'); assert.equal(minimax.capabilities.find(item => item.key === 'IMAGE_TO_VIDEO').verification, 'UNKNOWN'); });
test('routing report is deterministic and versioned', () => { const report = buildProviderRoutingReport({ specifications: [spec()], capturedAt: '2026-09-02T00:00:00.000Z', snapshotId: 'snap-1' }); const again = buildProviderRoutingReport({ specifications: [spec()], capturedAt: '2026-09-02T00:00:00.000Z', snapshotId: 'snap-1' }); assert.deepEqual(report, again); assert.equal(report.algorithmVersion, PROVIDER_ROUTING_ALGORITHM_VERSION); assert.equal(report.scope, 'LONG_FORM'); });
test('provider secrets are absent from request payloads', () => { const candidate = model('fixture:secret-check', { capabilities: withCaps(['TEXT_TO_IMAGE']) }); const routing = buildProviderRouting({ specification: spec(), registry: registry(candidate) }); const json = JSON.stringify(routing.requests[0]); assert.equal(json.includes('API_KEY'), false); assert.equal(json.includes('Authorization'), false); assert.equal(json.includes('token'), false); });
