import test from 'node:test';
import assert from 'node:assert/strict';
import { buildVisualAssetIntelligence } from '../src/lib/visual-asset-intelligence.ts';
import { buildVisualGenerationSpecifications, VISUAL_GENERATION_SPECIFICATION_ALGORITHM_VERSION } from '../src/lib/visual-generation-specification.ts';

const storyboard = (overrides = {}) => ({
  storyboardId: 'storyboard-gs-1', storyboardVersion: 'storyboard-planning-v1', scriptId: 'script-1', confidence: 'HIGH', readiness: 'READY_FOR_PRODUCTION_PLANNING', blockers: [],
  scenes: [{ semanticScene: { sceneId: 'scene-1' }, shots: [{ shotId: 'shot-1', sceneId: 'scene-1', purpose: 'SHOW_SUBJECT', subjectRequirement: 'Host at the workbench', environmentRequirement: 'Workshop', actionRequirement: 'Host picks up the tool and turns toward the camera', compositionRequirement: 'Establish clear subject, subtle push', continuityRequirement: 'Keep host and workshop consistent', evidenceRequirement: null, visualMode: 'BROLL', estimatedDuration: { minSeconds: 4, maxSeconds: 8, calibrationStatus: 'CALIBRATION_REQUIRED' }, productionSource: 'CREATOR_CAPTURE', confidence: 'HIGH', risks: [] }, { shotId: 'shot-2', sceneId: 'scene-1', purpose: 'SHOW_EVIDENCE', subjectRequirement: 'Analytics screenshot', environmentRequirement: null, actionRequirement: 'Reveal the retention chart', compositionRequirement: 'Screen focus', continuityRequirement: null, evidenceRequirement: 'Use the real screenshot', visualMode: 'SCREEN_CAPTURE', estimatedDuration: { minSeconds: 3, maxSeconds: 6, calibrationStatus: 'CALIBRATION_REQUIRED' }, productionSource: 'PUBLIC_EVIDENCE', confidence: 'MEDIUM', risks: [] }], assetIds: ['char-host', 'env-workshop', 'prop-tool', 'screen-1'], evidenceVisualizationIds: ['ev-1'] }],
  assetRequirements: [
    { assetId: 'char-host', type: 'CHARACTER', label: 'Host', availability: 'REQUIRES_ASSET', source: 'USER_PROVIDED', rightsStatus: 'IP_DEPENDENCY_UNKNOWN', usedBySceneIds: ['scene-1'], notes: [] },
    { assetId: 'env-workshop', type: 'LOCATION', label: 'Workshop', availability: 'REQUIRES_ASSET', source: 'USER_PROVIDED', rightsStatus: 'IP_DEPENDENCY_UNKNOWN', usedBySceneIds: ['scene-1'], notes: [] },
    { assetId: 'prop-tool', type: 'PROP', label: 'Tool', availability: 'REQUIRES_ASSET', source: 'AI_GENERATABLE', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1'], notes: [] },
    { assetId: 'screen-1', type: 'SCREENSHOT', label: 'Analytics screenshot', availability: 'REQUIRES_ASSET', source: 'CREATOR_CAPTURE', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', usedBySceneIds: ['scene-1'], notes: [] },
  ],
  evidenceVisualizations: [{ visualizationId: 'ev-1', claimId: 'claim-1', evidenceId: 'evidence-1', sceneId: 'scene-1', shotId: 'shot-2', visualizationType: 'SCREENSHOT', evidenceKind: 'EVIDENCE_VISUAL', requiredAsset: 'screen-1', source: 'PUBLIC_EVIDENCE', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', confidence: 'HIGH', availability: 'REQUIRES_ASSET', note: 'real source' }],
  provenance: { storyboardVersion: 'storyboard-planning-v1', evidenceIds: [], scriptVersion: 'script-writing-v1' }, ...overrides,
});
const packageFor = (input = {}) => { const report = buildVisualAssetIntelligence({ storyboard: storyboard(), ...input }); return report.packages[0] || report.blockedPackages[0]; };
const run = (story = storyboard(), pkg = packageFor()) => buildVisualGenerationSpecifications({ storyboard: story, assetPackage: pkg, capturedAt: '2026-09-02T00:00:00.000Z', snapshotId: 'snap-1' });

test('null storyboard stays insufficient', () => { const report = buildVisualGenerationSpecifications({ storyboard: null }); assert.equal(report.specifications.length, 0); assert.equal(report.dataAvailability.storyboard, 'UNAVAILABLE'); });
test('each relevant shot receives a structured canonical specification', () => { const report = run(); assert.equal(report.specifications.length, 2); assert.equal(report.specifications[0].specificationVersion, VISUAL_GENERATION_SPECIFICATION_ALGORITHM_VERSION); assert.equal(typeof report.specifications[0].startState, 'object'); assert.equal('prompt' in report.specifications[0], false); });
test('simple illustration keeps semantic START and CHANGE and derives END for a state change', () => { const item = run().specifications[0]; assert.ok(item.startState.subjects.length); assert.ok(item.desiredChange.length); assert.ok(item.endState); assert.equal(item.complexity.state, 'MODERATE'); });
test('recurring character without reference requires reference and hard identity lock', () => { const item = run().specifications[0]; assert.equal(item.generationRoute, 'USER_INPUT_REQUIRED'); assert.equal(item.readiness, 'NEEDS_REFERENCE'); assert.ok(item.continuityLocks.some(lock => lock.type === 'IDENTITY_LOCK' && lock.strength === 'HARD')); assert.ok(item.referenceDependencies.some(ref => ref.role === 'IDENTITY' && ref.required)); });
test('recurring character with supplied reference keeps identity dependency', () => { const pkg = packageFor({ existingAssets: [{ assetId: 'char-host', assetType: 'CHARACTER', source: 'USER_UPLOAD', availability: 'AVAILABLE', rights: 'USER_OWNED' }], existingReferences: [{ assetId: 'char-host', referenceId: 'host-ref', source: 'USER_UPLOAD', sourceAssetId: 'upload-1', suitability: 'SUITABLE', rights: 'USER_OWNED' }] }); const item = run(storyboard(), pkg).specifications[0]; assert.ok(item.referenceDependencies.some(ref => ref.referenceIds.includes('host-ref'))); assert.ok(item.continuityLocks.some(lock => lock.type === 'IDENTITY_LOCK')); });
test('local state edit is representable as reference image edit with END state', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], shots: [{ ...storyboard().scenes[0].shots[0], actionRequirement: 'Change the host expression to a smile', visualMode: 'STATIC_IMAGE' }] }] }); const item = run(story).specifications[0]; assert.ok(['REFERENCE_IMAGE_EDIT', 'USER_INPUT_REQUIRED'].includes(item.generationRoute)); assert.ok(item.endState || item.readiness === 'NEEDS_REFERENCE'); assert.ok(item.desiredChange.some(change => change.type === 'EXPRESSION_CHANGE')); });
test('image-to-video simple motion uses START plus motion semantics when references exist', () => { const pkg = packageFor({ existingAssets: [{ assetId: 'char-host', assetType: 'CHARACTER', source: 'USER_UPLOAD', availability: 'AVAILABLE', rights: 'USER_OWNED' }, { assetId: 'env-workshop', assetType: 'ENVIRONMENT', source: 'USER_UPLOAD', availability: 'AVAILABLE', rights: 'USER_OWNED' }], existingReferences: [{ assetId: 'char-host', referenceId: 'host-ref', source: 'USER_UPLOAD', sourceAssetId: 'host', suitability: 'SUITABLE', rights: 'USER_OWNED' }, { assetId: 'env-workshop', referenceId: 'env-ref', source: 'USER_UPLOAD', sourceAssetId: 'env', suitability: 'SUITABLE', rights: 'USER_OWNED' }] }); const item = run(storyboard(), pkg).specifications[0]; assert.equal(item.generationRoute, 'IMAGE_TO_VIDEO'); assert.ok(item.motion?.actions.length); assert.ok(item.endState); });
test('complex multi-action shot splits into units and links intermediate state', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], shots: [{ ...storyboard().scenes[0].shots[0], actionRequirement: 'Host walks to the desk, picks up the tool, opens the case, reacts, and turns to camera' }] }] }); const item = run(story).specifications[0]; assert.equal(item.complexity.state, 'MULTI_STAGE'); assert.equal(item.generationRoute, 'MULTI_STAGE_GENERATION'); assert.ok(item.units.length > 1); assert.ok(item.units[0].intermediateStateId); assert.ok(item.units[1].dependsOnUnitIds.includes(item.units[0].unitId)); });
test('evidence screenshot is non-generative and requires real source', () => { const item = run().specifications[1]; assert.equal(item.generationRoute, 'SCREEN_CAPTURE'); assert.equal(item.evidenceSemantics.mode, 'REAL_SOURCE_REQUIRED'); assert.ok(item.negativeConstraints.some(constraint => constraint.type === 'DO_NOT_INVENT_EVIDENCE')); assert.equal(item.generationEligibility, undefined); });
test('missing chart data is research-first rather than generated', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], shots: [{ ...storyboard().scenes[0].shots[0], shotId: 'chart-shot', purpose: 'SHOW_EVIDENCE', visualMode: 'CHART', actionRequirement: 'Reveal the retention chart', evidenceRequirement: 'Use real chart data' }] }], assetRequirements: [{ assetId: 'chart-1', type: 'CHART', label: 'Retention chart data', availability: 'REQUIRES_RESEARCH', source: 'REQUIRES_RESEARCH', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1'], notes: [] }], evidenceVisualizations: [] }); const pkg = buildVisualAssetIntelligence({ storyboard: story }).packages[0]; const item = run(story, pkg).specifications[0]; assert.equal(item.generationRoute, 'CHART_RENDER'); assert.equal(item.readiness, 'NEEDS_RESEARCH'); });
test('text fidelity adds an explicit hard constraint', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], shots: [{ ...storyboard().scenes[0].shots[0], actionRequirement: 'Show exact title text and labels' }] }] }); const item = run(story).specifications[0]; assert.ok(item.negativeConstraints.some(constraint => constraint.type === 'TEXT_FIDELITY_REQUIRED' && constraint.severity === 'HARD')); });
test('archive rights review remains non-AI route', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], assetIds: ['archive-1'], shots: [{ ...storyboard().scenes[0].shots[0], visualMode: 'ARCHIVE', purpose: 'SHOW_EVIDENCE' }] }], assetRequirements: [{ assetId: 'archive-1', type: 'ARCHIVE', label: 'Archive footage', availability: 'REQUIRES_RESEARCH', source: 'REQUIRES_RESEARCH', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', usedBySceneIds: ['scene-1'], notes: [] }], evidenceVisualizations: [] }); const pkg = buildVisualAssetIntelligence({ storyboard: story }).packages[0]; const item = run(story, pkg).specifications[0]; assert.equal(item.generationRoute, 'RIGHTS_REVIEW_FIRST'); assert.equal(item.readiness, 'NEEDS_RIGHTS_REVIEW'); });
test('narration-only shot has no unnecessary generation task', () => { const story = storyboard({ scenes: [{ ...storyboard().scenes[0], assetIds: [], shots: [{ ...storyboard().scenes[0].shots[0], visualMode: 'NARRATION_ONLY', actionRequirement: null, subjectRequirement: null }] }], assetRequirements: [], evidenceVisualizations: [] }); const item = run(story, packageFor({ storyboard: story })).specifications[0]; assert.equal(item.generationRoute, 'MANUAL_PRODUCTION'); assert.equal(item.units.length, 1); assert.equal(item.evidenceSemantics.mode, 'NON_GENERATIVE'); });
test('provider unknown does not change canonical semantics', () => { const item = run().specifications[0]; assert.equal(item.dataAvailability.providerCapabilities, 'UNAVAILABLE'); assert.equal('provider' in item, false); assert.equal('model' in item, false); });
test('hard locks become preserve-unchanged and negative constraints', () => { const item = run().specifications[0]; assert.ok(item.preserveUnchanged.some(lock => lock.strength === 'HARD')); assert.ok(item.negativeConstraints.some(constraint => constraint.type === 'NO_IDENTITY_DRIFT')); });
test('calibration remains explicit and no 0-100 generation score exists', () => { const item = run().specifications[0]; assert.equal(item.complexity.calibrationStatus, 'CALIBRATION_REQUIRED'); assert.equal('score' in item, false); });
test('blocked storyboard yields blocked specifications', () => { const story = storyboard({ readiness: 'BLOCKED', blockers: [{ code: 'SCRIPT_BLOCKED' }] }); const report = run(story); assert.equal(report.specifications.length, 0); assert.ok(report.blockedSpecifications.length); assert.equal(report.blockedSpecifications[0].readiness, 'BLOCKED'); });
test('replay is deterministic and provider independent', () => { const a = run(); const b = run(); assert.deepEqual(a, b); assert.equal(JSON.stringify(a).includes('minimax'), false); assert.equal(JSON.stringify(a).includes('seedance'), false); });
test('shorts and Canvas are not part of the report', () => { const report = run(); assert.equal(report.scope, 'LONG_FORM'); assert.equal('canvas' in report, false); assert.equal('shorts' in report, false); });
