import test from 'node:test';
import assert from 'node:assert/strict';
import { buildVisualAssetIntelligence, VISUAL_ASSET_INTELLIGENCE_ALGORITHM_VERSION } from '../src/lib/visual-asset-intelligence.ts';

const base = (overrides = {}) => ({
  storyboardId: 'storyboard-1', storyboardVersion: 'storyboard-planning-v1', scriptId: 'script-1',
  scenes: [
    { semanticScene: { sceneId: 'scene-1' }, shots: [{ shotId: 'shot-1' }], assetIds: ['char-host', 'env-workshop', 'prop-tool', 'screen-1', 'chart-1'], evidenceVisualizationIds: ['ev-1'] },
    { semanticScene: { sceneId: 'scene-2' }, shots: [{ shotId: 'shot-2' }], assetIds: ['char-host', 'env-workshop', 'prop-tool'], evidenceVisualizationIds: [] },
  ],
  assetRequirements: [
    { assetId: 'char-host', type: 'CHARACTER', label: 'Host', availability: 'REQUIRES_ASSET', source: 'USER_PROVIDED', rightsStatus: 'IP_DEPENDENCY_UNKNOWN', usedBySceneIds: ['scene-1', 'scene-2'], notes: [] },
    { assetId: 'env-workshop', type: 'LOCATION', label: 'Workshop', availability: 'REQUIRES_ASSET', source: 'REQUIRES_RESEARCH', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', usedBySceneIds: ['scene-1', 'scene-2'], notes: [] },
    { assetId: 'prop-tool', type: 'PROP', label: 'Key tool', availability: 'REQUIRES_ASSET', source: 'AI_GENERATABLE', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1', 'scene-2'], notes: [] },
    { assetId: 'screen-1', type: 'SCREENSHOT', label: 'Analytics screenshot', availability: 'REQUIRES_ASSET', source: 'CREATOR_CAPTURE', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', usedBySceneIds: ['scene-1'], notes: [] },
    { assetId: 'chart-1', type: 'CHART', label: 'Retention chart data', availability: 'REQUIRES_RESEARCH', source: 'REQUIRES_RESEARCH', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1'], notes: [] },
  ],
  evidenceVisualizations: [{ visualizationId: 'ev-1', claimId: 'claim-1', evidenceId: 'evidence-1', sceneId: 'scene-1', shotId: 'shot-1', visualizationType: 'SCREENSHOT', evidenceKind: 'EVIDENCE_VISUAL', requiredAsset: 'screen-1', source: 'CREATOR_CAPTURE', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', confidence: 'HIGH', availability: 'REQUIRES_ASSET', note: 'real source required' }],
  blockers: [], readiness: 'READY_FOR_PRODUCTION_PLANNING', confidence: 'HIGH', ...overrides,
});
const run = (storyboard, input = {}) => buildVisualAssetIntelligence({ storyboard, capturedAt: '2026-09-02T00:00:00.000Z', snapshotId: 'snap-1', ...input });
const pkg = (storyboard, input = {}) => run(storyboard, input).packages[0] || run(storyboard, input).blockedPackages[0];

test('null storyboard stays insufficient and does not invent assets', () => { const report = run(null); assert.equal(report.packages.length, 0); assert.deepEqual(report.gaps, ['STORYBOARD_REQUIRED']); });
test('blocked storyboard remains blocked', () => { const report = run(base({ readiness: 'BLOCKED', blockers: [{ code: 'SCRIPT_BLOCKED' }] })); assert.equal(report.blockedPackages[0].readiness, 'BLOCKED'); assert.ok(report.blockedPackages[0].blockers.includes('SCRIPT_BLOCKED')); });
test('canonical identities deduplicate recurring character, environment and prop', () => { const item = pkg(base()); assert.equal(item.assets.filter(asset => asset.assetType === 'CHARACTER').length, 1); assert.deepEqual(item.assets.find(asset => asset.assetType === 'CHARACTER').sceneIds, ['scene-1', 'scene-2']); assert.equal(item.continuityLocks.filter(lock => lock.type === 'IDENTITY_LOCK').length, 1); });
test('description-only recurring identities cannot produce complete reference packs', () => { const item = pkg(base()); const pack = item.referencePacks.find(pack => pack.packType === 'CHARACTER'); assert.equal(pack.state, 'DESCRIPTION_ONLY'); assert.equal(item.assets.find(asset => asset.assetType === 'CHARACTER').generationEligibility, 'REFERENCE_REQUIRED'); assert.ok(item.missingAssets.some(gap => gap.type === 'CRITICAL_REFERENCE_MISSING')); });
test('usable supplied reference links to the canonical asset and changes pack state', () => { const item = pkg(base(), { existingReferences: [{ assetId: 'char-host', referenceId: 'ref-host', referenceType: 'IDENTITY_REFERENCE', source: 'USER_UPLOAD', sourceAssetId: 'upload-1', suitability: 'SUITABLE', rights: 'USER_OWNED', version: '2.0' }] }); const host = item.assets.find(asset => asset.assetType === 'CHARACTER'); assert.equal(host.referenceState, 'SUITABLE'); assert.equal(item.referencePacks.find(pack => pack.canonicalAssetId === host.assetId).state, 'COMPLETE'); });
test('screenshot requires actual capture and is never generated', () => { const item = pkg(base()); const screen = item.assets.find(asset => asset.assetType === 'SCREENSHOT' || asset.assetType === 'EVIDENCE_IMAGE'); assert.equal(screen.generationEligibility, 'NOT_RECOMMENDED'); assert.ok(item.missingAssets.some(gap => gap.type === 'USER_INPUT_REQUIRED')); });
test('real evidence source can be reused without fabricating visual understanding', () => { const item = pkg(base(), { existingAssets: [{ assetId: 'screen-1', label: 'Analytics screenshot', assetType: 'SCREENSHOT', source: 'USER_CAPTURE', availability: 'AVAILABLE', rights: 'USER_OWNED', sourceAssetId: 'capture-1', sourceUrl: null }] }); const screen = item.assets.find(asset => asset.assetType === 'SCREENSHOT'); assert.equal(screen.availability, 'AVAILABLE'); assert.equal(screen.provenance.sourceAssetId, 'capture-1'); assert.equal(screen.generationEligibility, 'NOT_RECOMMENDED'); });
test('chart data and render stay separate', () => { const item = pkg(base()); const charts = item.assets.filter(asset => asset.assetType === 'CHART_DATA' || asset.assetType === 'CHART_RENDER'); assert.equal(charts.length, 1); assert.equal(charts[0].assetType, 'CHART_DATA'); assert.ok(item.researchRequirements.some(req => req.assetId === charts[0].assetId)); });
test('archive and stock requirements carry rights gates', () => { const archive = { ...base(), assetRequirements: [{ assetId: 'archive-1', type: 'ARCHIVE', label: 'Historical footage', availability: 'REQUIRES_RESEARCH', source: 'REQUIRES_RESEARCH', rightsStatus: 'RIGHTS_REVIEW_REQUIRED', usedBySceneIds: ['scene-1'], notes: [] }], scenes: [{ semanticScene: { sceneId: 'scene-1' }, shots: [{ shotId: 'shot-1' }], assetIds: ['archive-1'], evidenceVisualizationIds: [] }] }; const item = pkg(archive); assert.equal(item.assets[0].assetType, 'ARCHIVE_VIDEO'); assert.equal(item.readiness, 'NEEDS_RIGHTS_REVIEW'); assert.ok(item.rightsReviews.length); });
test('AI illustrative asset is eligible only as a later route with reference caveat', () => { const item = pkg({ ...base(), evidenceVisualizations: [], assetRequirements: [{ assetId: 'prop-1', type: 'PROP', label: 'Illustrative prop', availability: 'UNKNOWN', source: 'AI_GENERATABLE', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1'], notes: [] }], scenes: [{ semanticScene: { sceneId: 'scene-1' }, shots: [{ shotId: 'shot-1' }], assetIds: ['prop-1'], evidenceVisualizationIds: [] }] }); assert.equal(item.assets[0].generationEligibility, 'REFERENCE_REQUIRED'); assert.equal(item.continuityLocks[0].type, 'PROP_LOCK'); });
test('synthetic evidence attempt is blocked', () => { const item = pkg({ ...base(), assetRequirements: [{ assetId: 'ev-ai', type: 'IMAGE', label: 'Synthetic evidence', availability: 'UNKNOWN', source: 'AI_GENERATABLE', rightsStatus: 'LOW_KNOWN_RISK', usedBySceneIds: ['scene-1'], notes: [] }], evidenceVisualizations: [{ ...base().evidenceVisualizations[0], requiredAsset: 'ev-ai' }] }); assert.ok(item.blockers.includes('EVIDENCE_ASSET_REPLACED_BY_SYNTHETIC')); assert.equal(item.readiness, 'BLOCKED'); });
test('missing user asset is visible in scene and shot manifests', () => { const item = pkg(base()); assert.ok(item.sceneManifests[0].missingAssetIds.length); assert.ok(item.shotManifests[0].missingAssetIds.length); });
test('continuity locks cover recurring identity and wardrobe', () => { const item = pkg(base()); const lockTypes = item.continuityLocks.filter(lock => lock.assetId === item.assets.find(asset => asset.assetType === 'CHARACTER').assetId).map(lock => lock.type); assert.deepEqual(lockTypes, ['IDENTITY_LOCK', 'WARDROBE_LOCK']); });
test('duplicate references are deterministic and do not create embeddings', () => { const input = { existingReferences: [{ assetId: 'char-host', referenceId: 'ref-a', source: 'USER_UPLOAD', sourceAssetId: 'same', suitability: 'UNKNOWN' }, { assetId: 'char-host', referenceId: 'ref-b', source: 'USER_UPLOAD', sourceAssetId: 'same', suitability: 'UNKNOWN' }] }; const a = pkg(base(), input); const b = pkg(base(), input); assert.deepEqual(a, b); assert.equal(a.dataAvailability.embeddings, 'UNAVAILABLE'); });
test('rights uncertainty propagates to package review', () => { const item = pkg(base()); assert.ok(item.rightsReviews.length >= 1); assert.ok(['NEEDS_RIGHTS_REVIEW', 'NEEDS_ASSETS', 'READY_WITH_CAUTION'].includes(item.readiness)); });
test('version and provenance are explicit', () => { const item = pkg(base()); assert.equal(item.packageVersion, '1.0'); assert.equal(item.assets[0].assetVersion, '1.0'); assert.equal(item.provenance.algorithmVersion, VISUAL_ASSET_INTELLIGENCE_ALGORITHM_VERSION); assert.equal(item.provenance.storyboardId, 'storyboard-1'); });
test('shorts and canvas boundaries are absent from the report', () => { const item = pkg(base()); assert.equal('canvas' in item, false); assert.equal('shorts' in item, false); assert.equal(item.provenance.algorithmVersion, 'visual-asset-intelligence-v1'); });
test('replay returns byte-stable JSON', () => { const a = run(base()); const b = run(base()); assert.deepEqual(a, b); });
