'use client';

import { useState } from 'react';
import { diagnoseChannel, type ChannelDoctorReport, type DoctorFinding } from '@/src/lib/channel-doctor';

const compact=new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1});
const pct=(value?:number)=>value===undefined?'数据不足':`${value>0?'+':''}${Math.round(value)}%`;

const statusCopy={
  suspected_healthy:{title:'疑似正常',body:'近期公开信号没有发现明显的频道级异常。',tone:'good'},
  needs_attention:{title:'需要关注',body:'近期公开信号出现变化，建议先按行动计划验证。',tone:'watch'},
  insufficient_data:{title:'数据不足',body:'公开视频样本不足，暂时不应给出频道级结论。',tone:'neutral'},
} as const;

function Finding({finding}:{finding:DoctorFinding}){return <article className={`doctor-finding ${finding.severity}`}><div className="finding-top"><span className="severity-dot"/><div><span className="eyebrow">{finding.layer} · {finding.severity==='high'?'优先排查':finding.severity==='medium'?'值得关注':'参考信号'}</span><h3>{finding.title}</h3></div></div><p>{finding.statement}</p><div className="finding-evidence">{finding.evidence.map(item=><span key={item}>↗ {item}</span>)}</div><details><summary>依据、可能原因与下一步</summary><div className="doctor-detail"><b>可能原因（按证据强度排序）</b>{finding.causes.map(item=><p key={item.text}><em>{item.level}</em>{item.text}</p>)}<b>下一步</b><ol>{finding.actions.map(item=><li key={item}>{item}</li>)}</ol></div></details></article>}

function DoctorReport({report}:{report:ChannelDoctorReport}){const s=statusCopy[report.summary.status];const m=report.metrics;return <section className="doctor-report" aria-live="polite"><div className="doctor-hero"><div className={`health-orb ${s.tone}`} style={{'--health':`${report.summary.healthSignalScore * 3.6}deg`} as React.CSSProperties}><div><b>{report.summary.healthSignalScore}</b><small>/ 100</small></div></div><div className="doctor-hero-copy"><span className="eyebrow">公开频道快速体检 · 置信度 {report.summary.confidence}%</span><h1>{report.channel.title}</h1><div className={`health-status ${s.tone}`}>{s.title}</div><p>{report.summary.primaryFinding}</p><small>{s.body} 这不是“限流”或处罚判断，结论仅基于最近公开视频样本。</small></div><div className="doctor-channel-meta"><span>{compact.format(report.channel.subscriberCount)} 订阅</span><span>{report.metrics.sampleSize} 条样本</span><span>{compact.format(report.channel.videoCount)} 视频</span></div></div>

<section className="doctor-section"><div className="doctor-section-heading"><div><span className="eyebrow">先看问题在哪一层</span><h2>公开数据漏斗</h2></div><p>曝光、点击、留存与推荐扩大不能从公开数据可靠判断，需频道 OAuth 授权。</p></div><div className="doctor-funnel">{report.funnel.map((step,index)=><div key={step.key} className={`funnel-step ${step.status}`}><span>{index+1}</span><b>{step.label}</b><small>{step.status==='ok'?'公开信号正常':step.status==='watch'?'需要关注':'需授权'}</small><p>{step.reason}</p></div>)}</div></section>

<section className="doctor-section doctor-main-grid"><div><div className="doctor-section-heading"><div><span className="eyebrow">最重要的结论</span><h2>诊断与行动</h2></div></div><div className="doctor-findings">{report.findings.map(finding=><Finding finding={finding} key={finding.id}/>)}</div></div><aside className="doctor-evidence"><span className="eyebrow">公开信号面板</span><h2>证据概览</h2><div className="doctor-metric"><span>近期播放中位数</span><b>{compact.format(m.recentMedianViews ?? m.medianViews)}</b><small>减少单条爆款的干扰</small></div><div className="doctor-metric"><span>近期趋势</span><b className={(m.trendPercent||0)<0?'down':'up'}>{pct(m.trendPercent)}</b><small>{m.previousMedianViews?`对比上一组：${compact.format(m.previousMedianViews)}`:'样本不足，未计算'}</small></div><div className="doctor-metric"><span>主题一致性</span><b>{m.topicConsistency===undefined?'—':`${m.topicConsistency}/100`}</b><small>标题和描述推断，非 YouTube 官方指标</small></div><div className="doctor-metric"><span>发布间隔</span><b>{m.postingIntervalDays===undefined?'—':`${m.postingIntervalDays} 天`}</b><small>基于相邻样本发布时间</small></div><div className="topic-clusters"><b>近期主题簇</b>{report.topicClusters.length?report.topicClusters.map(item=><span key={item.name}>{item.name} <em>{item.percent}%</em></span>):<p>样本不足，无法形成主题簇。</p>}</div></aside></section>

<section className="doctor-section doctor-oauth"><div><span className="eyebrow">连接自己的频道后可用</span><h2>深度诊断：曝光 → 点击 → 观看 → 推荐</h2><p>获得授权后才读取 Impressions、CTR、留存、流量来源与 Shorts Feed，用于区分包装、内容与推荐测试问题。</p></div><button disabled title="OAuth 授权将在第二阶段开放">即将开放 · 连接 YouTube</button></section>

<details className="doctor-limitations"><summary>公开模式能看什么，不能看什么？</summary><ul>{report.dataLimitations.map(item=><li key={item}>{item}</li>)}</ul></details>
</section>}

export default function ChannelDoctor(){const [input,setInput]=useState('');const [limit,setLimit]=useState(20);const [report,setReport]=useState<ChannelDoctorReport|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const run=async(e:React.FormEvent)=>{e.preventDefault();if(!input.trim()){setError('请输入频道链接、@handle 或 Channel ID。');return}setLoading(true);setError('');try{setReport(await diagnoseChannel(input,limit))}catch(err){setError(err instanceof Error?err.message:'暂时无法完成体检。')}finally{setLoading(false)}};return <main className="doctor-page"><section className="doctor-intro"><div><span className="eyebrow">CHANNEL DOCTOR · PUBLIC BETA</span><h1>先判断频道是否正常，<em>再决定下一步。</em></h1><p>输入任意 YouTube 频道链接，基于最近公开视频样本识别趋势、波动、爆款率、内容一致性与发布稳定性。</p></div><div className="doctor-trust"><b>不猜测“限流”</b><span>公开模式只使用可验证数据；曝光、CTR、留存会明确标记为需授权。</span></div></section><form className="doctor-form" onSubmit={run}><label><span>频道链接、@handle 或 Channel ID</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder="如：https://www.youtube.com/@ChannelName" autoComplete="url"/></label><label className="doctor-limit"><span>分析样本</span><select value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value={10}>最近 10 条</option><option value={20}>最近 20 条</option><option value={30}>最近 30 条</option></select></label><button className="primary" disabled={loading}>{loading?'正在读取公开数据…':'开始频道体检'}</button></form>{error&&<div className="doctor-error" role="alert">{error}</div>}{loading&&<div className="doctor-skeleton"><i/><i/><i/></div>}{report?<DoctorReport report={report}/>:!loading&&!error&&<section className="doctor-empty"><span>✦</span><h2>用一个频道链接开始</h2><p>约 10–20 秒后，你会看到公开数据中可验证的最大问题、证据和下一步行动。</p></section>}</main>}
