'use client';

import { useEffect, useMemo, useState } from 'react';
import { channels, getOpportunity, initialAlerts, initialCollections, initialIdeas, initialTasks, promptTemplates, videos, watchRules } from '@/src/lib/mock';
import { parseFilters, serializeFilters } from '@/src/lib/scoring.mjs';
import type { Alert, Collection, Idea, IdeaStatus, Task, Video, WatchRule } from '@/src/lib/types';
import { searchYouTubeSignals } from '@/src/lib/youtube';

const BRAND = process.env.NEXT_PUBLIC_BRAND_NAME || 'SignalCraft';
const cn = (...names:(string|false|undefined)[]) => names.filter(Boolean).join(' ');
const num = new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1});
const date = (iso:string) => new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const channelFor = (v:Video) => channels.find(c=>c.id===v.channelId) || {id:v.channelId,title:'公开频道',handle:'',subscribers:v.snapshots.at(-1)?.subscribers||0,language:v.language,region:v.region,medianViews:1,health:0,tags:[],owner:'未分配',lastSync:'刚刚'};
const scoreFor = (v:Video) => getOpportunity(v);

type Toast = {message:string; kind?:'success'|'info'} | null;
type Persisted = { saved:string[]; collections:Collection[]; ideas:Idea[]; tasks:Task[]; alerts:Alert[]; rules:WatchRule[]; tags:Record<string,string[]> };
const defaultState:Persisted={saved:[],collections:initialCollections,ideas:initialIdeas,tasks:initialTasks,alerts:initialAlerts,rules:watchRules,tags:{}};

function usePersisted(){
  const [state,setState]=useState<Persisted>(()=>{if(typeof window==='undefined')return defaultState;const raw=localStorage.getItem('signalcraft-demo');try{return raw?{...defaultState,...JSON.parse(raw)}:defaultState}catch{return defaultState}});
  useEffect(()=>{localStorage.setItem('signalcraft-demo',JSON.stringify(state))},[state]);
  return [state,setState] as const;
}

function navigate(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new Event('signalcraft:navigate')); window.scrollTo({top:0,behavior:'smooth'}); }
function Sparkline({video}:{video:Video}){const data=video.snapshots.map(s=>s.views);const max=Math.max(...data),min=Math.min(...data);const pts=data.map((n,i)=>`${i*33},${30-((n-min)/(max-min||1))*25}`).join(' ');return <svg className="spark" viewBox="0 0 100 34" aria-label="播放量增长曲线"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" /></svg>}
function ScorePill({value}:{value:number}){return <span className={cn('score',value>=80?'excellent':value>=65?'good':'watch')}>{value}<small>/100</small></span>}
function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">◇</div><b>{title}</b><p>{body}</p>{action}</div>}

function Header({path,onTheme}:{path:string;onTheme:()=>void}){const isApp=path.startsWith('/app');return <><header className="site-header"><button className="brand" onClick={()=>navigate('/')} aria-label="返回首页"><span className="brand-glyph">SC</span><span>{BRAND}<small>CONTENT INTELLIGENCE</small></span></button><nav className="site-nav" aria-label="主导航">{isApp?<><button onClick={()=>navigate('/app')}>指挥台</button><button onClick={()=>navigate('/app/research')}>深度检索</button><button onClick={()=>navigate('/app/ideas')}>选题实验室</button></>:<><button onClick={()=>navigate('/discover')}>发现</button><button onClick={()=>navigate('/rankings')}>排行榜</button><button onClick={()=>navigate('/radar')}>机会雷达</button><button onClick={()=>navigate('/pricing')}>定价</button></>}</nav><div className="head-actions"><button className="icon-btn" onClick={onTheme} aria-label="切换颜色模式">◐</button><button className="ghost" onClick={()=>navigate(isApp?'/discover':'/app')}>{isApp?'公开发现':'进入工作室'}</button><button className="primary small" onClick={()=>navigate('/app')}>开始使用</button></div></header>{isApp&&<StudioNav path={path}/>}</>}
function StudioNav({path}:{path:string}){const items=[['/app','概览'],['/app/library/channels','频道资产'],['/app/library/videos','视频资产'],['/app/research','深度检索'],['/app/watchlists','监听'],['/app/benchmarks','对标组'],['/app/ideas','选题'],['/app/prompts','提示词'],['/app/settings','配置']];return <aside className="studio-nav"><p>工作室</p>{items.map(([href,label])=><button key={href} className={cn(path===href&&'active')} onClick={()=>navigate(href)}>{label}</button>)}</aside>}

function Filters({filters,setFilters}:{filters:ReturnType<typeof parseFilters>;setFilters:(v:ReturnType<typeof parseFilters>)=>void}){const patch=(key:string,value:string)=>{const next={...filters,[key]:value};setFilters(next);const q=serializeFilters(next);window.history.replaceState({},'',`${location.pathname}${q?`?${q}`:''}`)};return <div className="filters" aria-label="筛选器"><label>关键词<input value={filters.q} onChange={e=>patch('q',e.target.value)} placeholder="如：AI productivity"/></label><label>窗口<select value={filters.window} onChange={e=>patch('window',e.target.value)}><option value="24h">24 小时</option><option value="7d">近 7 天</option><option value="28d">近 28 天</option></select></label><label>语言<select value={filters.language} onChange={e=>patch('language',e.target.value)}><option value="all">全部语言</option><option value="英语">英语</option><option value="西班牙语">西班牙语</option><option value="葡萄牙语">葡萄牙语</option></select></label><label>形态<select value={filters.format} onChange={e=>patch('format',e.target.value)}><option value="all">短+长视频</option><option value="short">短视频</option><option value="long">长视频</option></select></label><label>订阅上限<select value={filters.maxSubs} onChange={e=>patch('maxSubs',e.target.value)}><option value="100000">10 万</option><option value="50000">5 万</option><option value="all">不限</option></select></label><label>最低评分<select value={filters.minScore} onChange={e=>patch('minScore',e.target.value)}><option value="70">70+</option><option value="80">80+</option><option value="0">不限</option></select></label></div>}

function VideoCard({video,state,setState,onDetail}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onDetail:(v:Video)=>void}){const o=scoreFor(video),channel=channelFor(video),saved=state.saved.includes(video.id);const toggle=()=>setState(s=>({...s,saved:s.saved.includes(video.id)?s.saved.filter(x=>x!==video.id):[...s.saved,video.id]}));return <article className="video-card"><div className="thumb" style={{backgroundImage:`linear-gradient(130deg,rgba(7,13,28,.18),rgba(11,102,110,.55)),url(${video.thumbnail})`}}><span>{video.format==='short'?'短视频':'长视频'} · {video.durationSeconds<60?`${video.durationSeconds}秒`:`${Math.round(video.durationSeconds/60)}分`}</span><ScorePill value={o.opportunityScore}/></div><div className="card-body"><div className="eyebrow">{video.topic} · {video.language} / {video.region}</div><button className="video-title" onClick={()=>onDetail(video)}>{video.title}</button><p className="channel-line">{channel.title} · {num.format(channel.subscribers)} 订阅</p><div className="metric-row"><b>{num.format(video.snapshots.at(-1)!.views)}<small>播放</small></b><b className="up">↑ {num.format(o.viewsPerHour)}<small>/小时</small></b><Sparkline video={video}/></div><div className="card-actions"><button onClick={toggle} aria-pressed={saved}>{saved?'已保存':'保存'}</button><button onClick={()=>onDetail(video)}>证据与行动</button></div></div></article>}

function DetailDrawer({video,state,setState,onClose,toast}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onClose:()=>void;toast:(t:string)=>void}){const o=scoreFor(video),channel=channelFor(video);const addIdea=()=>{const exists=state.ideas.some(i=>i.sourceVideoId===video.id);if(!exists)setState(s=>({...s,ideas:[...s.ideas,{id:`i${Date.now()}`,title:`拆解：${video.title.slice(0,24)}`,sourceVideoId:video.id,angle:'从异常表现中提取可验证的钩子',audience:'目标赛道的内容消费者',hypothesis:'明确收益 + 具体数字会提升点击',owner:'林语',status:'收集',note:'来自 SignalCraft 证据链',createdAt:new Date().toISOString()}]}));toast(exists?'该视频已有选题卡':'已创建选题卡，来源证据已带入');};const addBenchmark=()=>{setState(s=>({...s,collections:s.collections.map((c,i)=>i===0?{...c,items:[...new Set([...c.items,video.id])]}:c)}));toast('已加入「AI 效率工具」对标组');};return <div className="drawer-backdrop" role="presentation" onMouseDown={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label="视频证据详情" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="eyebrow">证据链 · {video.topic}</div><h2>{video.title}</h2><p className="channel-line">{channel.title} · 发布 {date(video.publishedAt)} · {video.risk==='low'?'低风险':'需复核风险'}</p><div className="score-hero"><ScorePill value={o.opportunityScore}/><div><b>机会评分</b><p>不是 AI 真相，而是基于公开样本的可复算信号。</p></div></div><div className="explain-grid"><div><span>VelocityScore</span><b>{o.velocityScore}</b><small>近时段播放增速</small></div><div><span>OutlierScore</span><b>{o.outlierScore}</b><small>相对频道中位数偏离</small></div><div><span>Confidence</span><b>{o.confidence}%</b><small>{video.snapshots.length} 个时间采样</small></div><div><span>相对表现</span><b>{o.viewsPerSubscriber}×</b><small>播放 / 频道订阅</small></div></div><section className="evidence"><h3>为什么值得看</h3>{o.reasons.map(r=><p key={r}>✓ {r}</p>)}<p>✓ 当前增长率为频道历史基线的 {o.growthRate}×；数据来源：演示快照。</p></section><section className="evidence"><h3>相似样本</h3>{videos.filter(v=>v.topic===video.topic&&v.id!==video.id).slice(0,3).map(v=><button className="similar" key={v.id} onClick={()=>toast(`可继续比较：${v.title.slice(0,20)}…`)}>{v.title}<ScorePill value={scoreFor(v).opportunityScore}/></button>)}</section><div className="drawer-actions"><button className="primary" onClick={addIdea}>创建选题</button><button onClick={addBenchmark}>加入对标组</button><button onClick={()=>toast('已创建监听规则（演示）')}>设置监听</button><button onClick={()=>navigator.clipboard?.writeText(`https://youtube.com/watch?v=${video.id}`).then(()=>toast('链接已复制'))}>复制链接</button></div></aside></div>}

function DemoDiscovery({mode,state,setState,openDetail}:{mode:'discover'|'rankings'|'radar';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){const [filters,setFilters]=useState(()=>typeof window==='undefined'?parseFilters(''):parseFilters(location.search));const [page,setPage]=useState(1);const rows=useMemo(()=>videos.filter(v=>{const o=scoreFor(v),c=channelFor(v),text=`${v.title} ${v.topic} ${v.tags.join(' ')}`.toLowerCase();return (!filters.q||text.includes(filters.q.toLowerCase()))&&(filters.language==='all'||v.language===filters.language)&&(filters.format==='all'||v.format===filters.format)&&(filters.maxSubs==='all'||c.subscribers<=Number(filters.maxSubs))&&o.opportunityScore>=Number(filters.minScore)}).sort((a,b)=>mode==='rankings'?b.snapshots.at(-1)!.views-a.snapshots.at(-1)!.views:scoreFor(b).opportunityScore-scoreFor(a).opportunityScore),[filters,mode]);const clusters=useMemo(()=>Object.entries(rows.reduce<Record<string,Video[]>>((acc,v)=>{(acc[v.topic]??=[]).push(v);return acc},{})),[rows]);if(mode==='radar')return <main className="page"><PageIntro label="机会雷达" title="不是更多卡片，而是可行动的机会簇" body="按新出现、加速中、低粉爆发和可复刻形式组织样本；每个结论都能回到证据。"/><Filters filters={filters} setFilters={setFilters}/><div className="radar-tabs"><button className="active">加速中</button><button>新出现</button><button>低粉爆发</button><button>可复刻形式</button></div><div className="cluster-list">{clusters.map(([topic,items])=>{const avg=Math.round(items.reduce((n,v)=>n+scoreFor(v).opportunityScore,0)/items.length);return <section className="cluster" key={topic}><div className="cluster-head"><div><span className="eyebrow">机会簇</span><h2>{topic}</h2><p>{items.length} 个样本 · 平均机会评分 {avg} · 以 {items[0].format==='short'?'短视频钩子':'长视频结构'} 为主</p></div><ScorePill value={avg}/></div><div className="cluster-evidence"><b>共同模式</b><span>{items.slice(0,3).map(v=>v.tags[0]).join(' · ')}</span><button onClick={()=>openDetail(items[0])}>查看证据链 →</button></div><div className="mini-grid">{items.slice(0,3).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div></section>})}</div></main>;return <main className="page"><PageIntro label={mode==='rankings'?'排行榜':'公开发现'} title={mode==='rankings'?'按信号强度筛出值得研究的样本':'今天值得关注的公开信号'} body="使用可分享筛选器，先找低订阅、高增长，再决定是否深入跟进。"/><Filters filters={filters} setFilters={setFilters}/><div className="result-toolbar"><span>找到 <b>{rows.length}</b> 个样本</span><span>排序：{mode==='rankings'?'播放量':'机会评分'}</span><button onClick={()=>navigator.clipboard?.writeText(location.href)}>复制筛选链接</button></div>{rows.length?<div className="video-grid">{rows.slice(0,page*6).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title="没有符合条件的样本" body="放宽评分或频道规模后再试。"/>}{rows.length>page*6&&<button className="load-more" onClick={()=>setPage(p=>p+1)}>加载更多样本</button>}</main>}

function Discovery({mode,state,setState,openDetail}:{mode:'discover'|'rankings'|'radar';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){
  const [filters,setFilters]=useState(()=>typeof window==='undefined'?parseFilters(''):parseFilters(location.search));
  const [page,setPage]=useState(1);
  const [remote,setRemote]=useState<Video[]|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const source=remote||videos;
  const runSearch=async()=>{
    if(!filters.q.trim()){setError('请先输入关键词，例如 AI productivity。');return;}
    setLoading(true);setError('');
    try{
      const result=await searchYouTubeSignals({query:filters.q,language:filters.language,window:filters.window});
      result.channels.forEach(channel=>{const inde�޶����k�w��@�ȗ��������ꘀ������𽑥��𽑥���͕�ѥ����͕�ѥ�������VÚ6���;�jC����������S���:���������R��r��rÞ�7��C�VÚ6���r��{�:�����S�k���e��QՉ���ф�A'��R��"ߚ:#�v�=�Ѡ��"[�B#�������'�Z�VÚ6���C��o��7�*O�>X�e��QՉ����צv���3��7��W���"[�>C�ꓞr��{���J������͕�ѥ����͕�ѥ���������fC���������J��R���{�V���ے�7��'��;�V��k��ߖ�"[�>���7�"ۚ���&#�v��V?������c��rÖ2�Z�2[���_��W�΋�*��J3�VÚ6����>��r�����ޗ��7�������͕�ѥ���𽵅����)�չ�ѥ���Aɥ������퍽��Ёɽ���ml������>G�:Ò�;��?�^����� ����rL����rL����rL�t�l��>�����+�r��k���"����P����rL����rL�t�l���w��c���皂��;�'��c�ޗ��s������P����rL����rL�t�l��n��b�"C�Fc�������;���*���Ö�T����P����P����rL�t�l�����k��'�nG�B���8�]��������6���4����P����P����rL�ut�ɕ��ɸ�񵅥�������9�����������A���%��ɼ������􋖺k��܈�ѥѱ��#���b;��ߖ��3�7�ϖ�k�6�꟎��������g�b���3�VӒꓒ�K��S����3��7�:����r��{�R���c�����r7�"[���*��&��������؁�����9�����ɥ������ɥ����ml�ɕ����
�������O��3�����>G�:Ò�;��;��'�"�����ߚr��t�l�Aɼ���
��䀼��r ����⫒��"o��s��j��3�VӞ�S��ۖޗ��s���t�l�Q������
���䀼��r ����n��b�6?��s���皂��;�nG�B���S���ut������m������ɥ�������t�����ѥ���������9����퍸���ɥ�����ɐ����������Aɼ���������ɕ���􁭕������������������������Aɼ����:��6@�蟢���"H������������������������ɥ��������퍽���������ѽ�������9�������������Aɼ����ɥ����蜝􁽹
�����젤����٥��є�������������������ɕ�����7������,�蟚~��r/��S���ޗ��s��������ѽ����ѥ������𽑥���؁�����9���􉙕���ɔ�х������؁�����9���􉙕���ɔ�ɽ܁������������*������ɕ�����Aɼ����Q�����𽑥���ɽ�̹��������؁�����9���􉙕���ɔ�ɽ܈�������l�u���ȹ�����౤����������������������������𽑥����𽑥��𽵅����()�չ�ѥ�����!������хє�͕�Mхє������х���ѽ�������хє�A��ͥ�ѕ��͕�Mхє�I���й����э��I���йM��Mхѕ�ѥ���A��ͥ�ѕ���������х�����Y�������ٽ���ѽ��������ɥ�����ٽ����퍽��Ё�����٥���̹���ѕȡ���͍�ɕ�ȡؤ�������չ���M��ɔ������ͱ������̤�ɕ��ɸ�񵅥�������9��������������A���%��ɼ��������+�^��2�2��>��
܃��S���ޗ��s�2舁ѥѱ��#���B��������>߾�3�7�:���o����Ϟ�[��������&�r'��w��c����*���'��c�J3�nG�B��v��w��c�r���O�&7��?��#�f���3�R���;��3�VӚ�S�������؁�����9���􉍽�������ɥ����͕�ѥ��������9���􉍽�������������؁�����9����͕�ѥ��������������������B����>�������ѽ����
�����젤����٥��є�����͍�ٕȜ�����o���>G�:æ�ԃ�H���ѽ��𽑥������������������ѽ�������9���􉅱��е��ɐ�������ع��􁽹
�����젤�������х���إ���M��ɕA����م�Ք��͍�ɕ�ȡؤ�������չ���M��ɕ���������عѥѱ��������͍�ɕ�ȡؤ�ɕ�ͽ��l�u����𽑥���������~��r,��H���������ѽ�����͕�ѥ����͕�ѥ��������9���􉍽������ͥ��������B3����*ۚ����؁�����9�����幌���������^<��������5����хAɽ٥������͵�����r��G�B3�����k�"k�"h�͵����𽑥���؁�����9�����սф����������S��릊w�����������Ȕ����񕴀�����͵�����r��x�A$���k�r���{�:��͵����𽑥�����ѽ�������9�����ɥ���䁙ձ�����
�����젤��ѽ��Р���˚���.�&���3������VÚ6��B3�����������.�B3������ѽ���͕�ѥ���𽑥���؁�����9���􉑅͡���ɐ��ɥ����͕�ѥ����؁�����9����͕�ѥ������������������*����6T������ѽ����
�����젤��͕�Mхє�����츸�̱хͭ��l���̹х̱ͭ����Б��є���ܠ����ѥѱ�蟚ZÖ����禪3�����*����х���蟖��*x���ݹ��蟚z_������Ք蟚r��F���u��������ZÖ�����ѽ��𽑥����хє�х̹ͭ����������ѽ�������9����хͬ�������й��􁽹
�����젤��͕�Mхє�����츸�̱хͭ��̹х̹ͭ�������๥����й���츸���х������х���������3�"@������*x�蟖�3�"@��������������������9����퍸���������й�х���������3�"@�������������rL������������йѥѱ�����͵�����й�ݹ���
܁�й�Օ��͵����𽑥�����й�х����𽕴����ѽ�����͕�ѥ����͕�ѥ����؁�����9����͕�ѥ����������������k�~��ⷖ�������ѽ����
�����젤��͕�Mхє�����츸�̱�������̹�����̹��������츸���ɕ�����Օ��������������ˢ�����ѽ��𽑥����хє������̹����������ѽ�������9����퍸����ѥ����ѥ�������ɕ�����չɕ����􁭕��턹��􁽹
�����젤����ͽ�ɍ�Y����%��������х���٥���̹��������ع�������ͽ�ɍ�Y����%�������������\�����������턹ѥѱ�����͵����턹������͵����𽑥���ѥ���푅є����ɕ�ѕ�Х��ѥ������ѽ�����͕�ѥ���𽑥��𽵅����()�չ�ѥ���1��Ʌ���������хє�͕�Mхє������х���������蝍������̝�٥���̜��хє�A��ͥ�ѕ��͕�Mхє�I���й����э��I���йM��Mхѕ�ѥ���A��ͥ�ѕ���������х�����Y�������ٽ�����������������������̜�ɕ��ɸ�񵅥�������9��������������A���%��ɼ������􋦊G�O���꜈�ѥѱ����⫖��_�V��r��S��۞j��G�O��������2'���ҏ����������;����ߖꛚ�'����G�O���꟎����؁�����9����х�����Ʌ����х�����ѡ���������Ѡ���G�L�Ѡ��Ѡ�������Ѡ��Ѡ�����b�Ѡ��Ѡ�����ߖ��Ѡ��Ѡ����ҏ����Ѡ��Ѡ��r��G�B3����Ѡ������ѡ�����щ����퍡�����̹���������ȁ����팹�����ѐ���팹ѥѱ�����͵����팹��������͵�����ѐ��ѐ�팹х�̹������������������9����х�����������������������ѐ��ѐ���մ���ɵ�С���Չ͍ɥ���̥��ѐ��ѐ������������9���􉡕��Ѡ�����屔���ݥ�Ѡ逑팹����ѡ������팹����ѡ��������ѐ��ѐ�팹�ݹ����ѐ��ѐ�팹����M幍��ѐ��������щ�����х����𽑥��𽵅����ɕ��ɸ�񵅥�������9��������������A���%��ɼ������􋢞��G���꜈�ѥѱ���w��c�j����>߾�3�&7���>c�"C�>���7�R��j��S��ۢ��꟎��������뢞��G�*��������g��S��Î�*����'��c�"[��皂��������хє�ٕͅ������Ѡ��؁�����9����٥�����ɥ����٥���̹���ѕȡ����хє�ٕͅ������Ց�̡ع�������������Y����
�ɐ������ع���٥��������хє���хѕ�͕�Mхє��͕�Mхѕ􁽹�х���������х�������𽑥��������ѥѱ���c�ʇ�r'��w��c����D�������r������>G�:Ú"[�nߢ����צv��
�s��w��c�w��3��g�3��k���*���:Î����ѥ�������ѽ�������9�����ɥ���䈁��
�����젤����٥��є�����͍�ٕȜ����:�>G�:Ú�ߚr����ѽ������𽵅����()�չ�ѥ���I�͕�ɍ����хє�͕�Mхє������х������хє�A��ͥ�ѕ��͕�Mхє�I���й����э��I���йM��Mхѕ�ѥ���A��ͥ�ѕ���������х�����Y�������ٽ�����ɕ��ɸ�񵅥�������9��������������A���%��ɼ��������ǖꛚ��҈��ѥѱ��R���k�⫚v���۾�3���?�"Ö>���3���j�������>ߎ������􋞶o�'��O�zs�>���7�"ۦN��:���ۖr���?��#�f����w�2�*ۚ������͍�ٕ�䁵���􉑥͍�ٕȈ��хє���хѕ�͕�Mхє��͕�Mхѕ�����х���������х�����𽵅����)�չ�ѥ���]�э�����̡��хє�͕�Mхє�ѽ�������хє�A��ͥ�ѕ��͕�Mхє�I���й����э��I���йM��Mхѕ�ѥ���A��ͥ�ѕ����ѽ��������ɥ�����ٽ�����ɕ��ɸ�񵅥�������9��������������A���%��ɼ�������nG�B����"d��ѥѱ�􋢺���������ǚv��&������������k�~��⃦O��;����>G��Ö�W�v����S���6���7��o�r��{�>G��r7�*��r��:��������؁�����9����݅э���ɥ�����хє��ձ�̹�����ձ�����ѥ���������9����݅э����ɐ��������ձ��������������������9����х�����ձ������������������ձ���������������ձ���ɕ�Օ����
܃�r��k���"��&����ձ��ѡɕ͡����
܁��ձ�������������𽑥��񱅉��������9����ѽ���������Ё����􉍡������������������ձ�����͕�􁽹
������젤��͕�Mхє�����츸�̱�ձ���̹�ձ�̹�������ȹ������ձ�����츸�ȱ���͕��ȹ���͕���ȥ��������������𽱅������ѥ������𽑥���؁�����9���􉥹�������ɴ�����Ё�������������/����k�.Ǣ���$��V#�:��;��'�"�>D������ձ�9�������͕���Ё����ձ�Q�������ѥ����ϦR���4��ѥ�����ѥ�����G�L��ѥ�����ѥ�����o�L��ѥ����͕��������ѽ�������9�����ɥ���䈁��
�����젤��퍽��Ё���������յ��й���������	�%����ձ�9�������́!Q51%����������퍽��Ё��������յ��й���������	�%����ձ�Q�������́!Q51M��������������������йم�Ք��ɥ����ɕ��ɸ�ѽ��Р���ߖ#����g���"g�B7������͕�Mхє�����츸�̱�ձ���l���̹�ձ�̱����ܑ��є���ܠ��������饹��йم�Ք�����������م�Ք��́]�э�Iձ�l������t�ѡɕ͡�����Ա�ɕ�Օ���蟚�<�؃��?�^؜��������蟞�g��k�~������͕�际�͕�u��������йم�Ք����ѽ��Р��nG�B����"g��˖"o��蜥����"o��뢞�"d���ѽ�����ѽ����
�����젤��퍽��Ёͽ�ɍ��٥����l�t�͕�Mхє�����츸�̱�������m���遄���є���ܠ����ѥѱ�蟚���.����>G��k��;��'�"�>D������逑�ͽ�ɍ��ѥѱ�����"����͍�ɕ�ȡͽ�ɍ���������չ���M��ɕ�"���ɕ�ѕ��鹕܁�є���ѽ%M=M�ɥ�����ɕ��际�͔�ͽ�ɍ�Y����%��ͽ�ɍ���������̹������u����ѽ��Р���˚���.���v�����>G��/��؜��������.����>D���ѽ��𽑥��𽵅����)�չ�ѥ���	������ɭ̡��хє�ѽ�������хє�A��ͥ�ѕ��ѽ��������ɥ�����ٽ����퍽��Ёm�����ɔ�͕�
����ɕt��͕Mхє���ɥ��mt��mt�퍽��Ё�������є�٥���̹���ѕȡ����хє�ٕͅ������Ց�̡ع�����ɕ��ɸ�񵅥�������9��������������A���%��ɼ������􋖾皂����;��S����ѥѱ�􋚾S���ˊLԃ�⫚�ߚr���3���&��ǖB3�����?��������&�r'��O������w�Vg�n{�"â���G����>ߒ�;�2���j���>������؁�����9���􉍽����ѥ����ɥ�����хє�������ѥ��̹���������ѥ���������9���􉍽����ѥ��������팹������������屔��퉅���ɽչ�錹��������������팹�����������팹�ѕ�̹����ѡ�⫦��n��
܁팹͡�ɕ�����˖ǒ꬜蟞��r$�����𽑥�����ѽ����
�����젤��ѽ��Р��ǒꯞ�S��Ú�S����k��˖�7�"ۖ"�ꯦN��:������"�����ѽ����ѥ������𽑥���؁�����9���􉍽���ɔ������Ȉ����������S���������'�.��ˊLԃ�⫖�˒�w��c�j����G����퍅�����є�����Ѡ��������є��������񱅉��������ع�������Ё����􉍡����������������퍽���ɔ�����Ց�̡ع���􁽹
������젤��͕�
����ɔ����๥���Ց�̡ع����๙��ѕȡ�������ع����๱���Ѡ���l����ع��t������عѥѱ��𽱅����������#�r��>G�:æ�ג�w��c�ϖ�G�ⓒ⫢���G�����𽑥��퍽���ɔ�����Ѡ��Ș��؁�����9���􉍽���ɔ�х������؁�����9���􉍽���ɔ�������������2����퍽���ɔ���������񈁭���������٥���̹��������ع����������ѥѱ��ͱ�������Х�������𽑥���ml��r��k���"�����Y�������͍�ɕ�ȡؤ�������չ���M��ɕt�l��J��R��������b�����Y����������͍�ɕ�ȡؤ�٥���A��MՉ͍ɥ����]�t�l���?��?�^ۚJ��R������Y��������մ���ɵ�С͍�ɕ�ȡؤ�٥���A��!��ȥt�l��>G���^ۦ^М����Y���������є�ع�Չ��͡��Хt�l��ǖB3����������Y�������عх�̹ͱ������Ȥ������������ut������m��������t����؁�����9���􉍽���ɔ�ɽ܈�������������́��ɥ������������������́��ɥ���������퍽���ɔ������������������������졙���̀���Y�������I���йI����9�����٥���̹��������ع�������������������𽑥����𽑥���𽵅����)�չ�ѥ���%���̡��хє�͕�Mхє�ѽ�������хє�A��ͥ�ѕ��͕�Mхє�I���й����э��I���йM��Mхѕ�ѥ���A��ͥ�ѕ����ѽ��������ɥ�����ٽ����퍽��Ё�х��͕��%���Mх���mt�l��Rۦn�����3������"ے�s�ⴜ����˖>G�������7�n`�t�ɕ��ɸ�񵅥�������9��������������A���%��ɼ�������'��c��{��3�����ѥѱ���;����>ߖ"Ö"ے�s��3�7�"Ö�7�nc�������􋚾?��'��c�6�����w�Vg�v���C����>߾�3���7�����'�Z����VÚ6������؁�����9���􉭅��������х��͕̹�����х������͕�ѥ���������х������؁�����9���􉭅���������������х��������������хє�����̹���ѕȡ������х�������х��̤�����ѡ�������𽑥����хє�����̹���ѕȡ������х�������х��̤��������퍽��Ё��٥���̹��������ع�������ͽ�ɍ�Y����%���ɕ��ɸ���ѥ���������9���􉥑��������������������������9����х����v���@����͍�ɕ�ȡؤ�������չ���M��ɔ蟊P��"������������ѥѱ���������������������͵��������ݹ���
܁푅є����ɕ�ѕ�Х��͵�����͕���Ёم�Ք�����х���􁽹
���������͕�Mхє�����츸�̱������̹����̹�������๥���������츸���х���锹хɝ�йم�Ք��́%���Mх�������������х��͕̹���������ѥ����������������ѥ������͕�������ѥ����������ѽ�������9���􉅑����������
�����젤���͕�Mхє�����츸�̱������l���̹����̱���遤���є���ܠ����ѥѱ�蟚r��F��B7�'��c��{��0��ͽ�ɍ�Y����%���Ĝ������蟖������"����K�ꘜ��Ց�����蟖���k��$������ѡ�ͥ�蟖���3�����ݹ��蟚z_������х��̱��є蜜��ɕ�ѕ��鹕܁�є���ѽ%M=M�ɥ�����u����ѽ��С���˖r��0���х�����7�"o���6��&�������,���ѽ���͕�ѥ�����𽑥��𽵅����)�չ�ѥ���Aɽ���̡�ѽ������ѽ��������ɥ�����ٽ�����ɕ��ɸ�񵅥�������9��������������A���%��ɼ�������>C��뢾7��L��ѥѱ��*+��S��ۚZ��W��'���"C�>���7�R�����v���������>c�?����v���k�r��r��x�$��:����B;�⛖��'��c��+��/�Z��o�n��&7�>���S��떒7�"ێ����؁�����9�����ɽ��е���Ј���ɽ���Q�����ѕ̹���������ѥ�����������������������������9����х��������ѕ�����������������ѥѱ��������������������͵�������ٕ�ͥ���
܁��������������˖B��R��蟖�˖s�R����͵����𽑥�����ѽ�������9�����ɥ���䈁��
�����젤����٥��ѽȹ�������ɐ���ɥѕQ��С�����䤹ѡ�������ѽ��Р��>C��뢾7����v���˖�7�"؜������7�"ۚ���v����ѽ����ѥ������𽑥��𽵅����)�չ�ѥ���M��ѥ��̠��ɕ��ɸ�񵅥�������9��������������A���%��ɼ�������7�����ѥѱ����r��{�r7�*����Vg���V3��3��7�r��&7�����w��c���J����������O�&7����S���7�����׾�3�&�r'�V?���_��זv��7�:��Rۚ"[�b����r��{���J������؁�����9����͕�ѥ��̵�ɥ����͕�ѥ�������VÚ6���@��������5����хAɽ٥������
܃��S���VÚ6���˖B��R�������ѽ����ͅ�������{�:��e��QՉ���ф�A'��#�r�r7�*������$���ѽ���͕�ѥ����͕�ѥ�������"ߚZâ���"H����͕���Ё����ձ�Y��Ք�؈���ѥ���م�Ք�؈���<�؃��?�^���ѥ�����ѥ���م�Ք��Ј���?�^���ѥ����͕���������r��{���*��b�"_��k�r��:��������͕�ѥ����͕�ѥ�������n��b�"C�F`�������z_����
܁=ݹ������������
܁��ѽ��������f#���
܁Y��ݕ�����͕�ѥ����͕�ѥ�������k�~��⃦L��������g��k�~���k��˖B��R��������
���ێM�����]��������k��S���6���4����͕�ѥ���𽑥��𽵅����()�����Ё����ձЁ�չ�ѥ���M�����
Ʌ������퍽��Ёm��Ѡ�͕�A�ѡt��͕Mхє�����퍽��Ёmѡ����͕�Q����t��͕Mхє������М�퍽��Ёm�хє�͕�Mхѕt��͕A��ͥ�ѕ���퍽��Ёm�Ʌݕȱ͕�Ʌݕ�t��͕Mхє�Y�����ձ����ձ��퍽��Ёmѽ��б͕�Q����t��͕Mхє�Q�������ձ����͕����Р����퍽��Ёɕ�������͕�A�Ѡ�����ѥ�����ѡ������ɕ����텑�ٕ��1��ѕ��Ƞ�����хє��ɕ���텑�ٕ��1��ѕ��Ƞ�ͥ�����Ʌ��鹅٥��є��ɕ����ɕ��ɸ�����ɕ��ٕٕ��1��ѕ��Ƞ�����хє��ɕ����ɕ��ٕٕ��1��ѕ��Ƞ�ͥ�����Ʌ��鹅٥��є��ɕ������mt���͕����Р����푽�յ��й���յ��������й��х͕йѡ����ѡ�����mѡ���t�퍽��Ё��ѥ�������ͅ�����ɥ������͕�Q���С����ͅ�����͕�Q�����Р����͕�Q���С�ձ���������퍽��Ё���ѕ�����Ѡ��������!���������х����͕�Ʌݕ�������Ѡ�������͍�ٕȜ���͍�ٕ�䁵���􉑥͍�ٕȈ��хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ�����Ʌ�����̜���͍�ٕ�䁵����Ʌ�����̈��хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ�����Ʌ��Ȝ���͍�ٕ�䁵����Ʌ��Ȉ��хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ�������ѡ���������5�ѡ�����������Ѡ������ɥ�������Aɥ���������Ѡ�������������!�����хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ��ѽ�������ѥ��������Ѡ������������Ʌ�位������̜��1��Ʌ�䁭���􉍡�����̈��хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ������������Ʌ��٥���̜��1��Ʌ�䁭����٥���̈��хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ���������ɕ͕�ɍ����I�͕�ɍ���хє���хѕ�͕�Mхє��͕�Mхѕ�����х����͕�Ʌݕ�������Ѡ���������݅э�����̜��]�э�����́�хє���хѕ�͕�Mхє��͕�Mхѕ�ѽ�������ѥ��������Ѡ����������������ɭ̝����Ѡ��������������ɔ���	������ɭ́�хє���хѕ�ѽ�������ѥ��������Ѡ�������������̜��%���́�хє���хѕ�͕�Mхє��͕�Mхѕ�ѽ�������ѥ��������Ѡ����������ɽ���̜��Aɽ���́ѽ�������ѥ��������Ѡ���������͕�ѥ��̜��M��ѥ��̼���!���������х����͕�Ʌݕ�����ɕ��ɸ��؁�����9�������͡������!����ȁ��Ѡ����ѡ􁽹Q�����젤��͕�Q�����������������М����ɬ�蝱���М����퍽�ѕ����ɅݕȘ���х��Ʌݕȁ٥�����Ʌݕ���хє���хѕ�͕�Mхє��͕�Mхѕ􁽹
��͔�젤��͕�Ʌݕȡ�ձ���ѽ�������ѥ�������ѽ��И��؁�����9����ѽ��Ј��rL��ѽ��й���ͅ���𽑥���𽑥���(
