'use client';

import { useEffect, useMemo, useState } from 'react';
import { channels, getOpportunity, initialAlerts, initialCollections, initialIdeas, initialTasks, promptTemplates, videos, watchRules } from '@/src/lib/mock';
import { parseFilters, serializeFilters } from '@/src/lib/scoring.mjs';
import type { Alert, Collection, Idea, IdeaStatus, Task, Video, WatchRule } from '@/src/lib/types';

const BRAND = process.env.NEXT_PUBLIC_BRAND_NAME || 'SignalCraft';
const cn = (...names:(string|false|undefined)[]) => names.filter(Boolean).join(' ');
const num = new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1});
const date = (iso:string) => new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const channelFor = (v:Video) => channels.find(c=>c.id===v.channelId)!;
const scoreFor = (v:Video) => getOpportunity(v);

type Toast = {message:string; kind?:'success'|'info'} | null;
type Persisted = { saved:string[]; collections:Collection[]; ideas:Idea[]; tasks:Task[]; alerts:Alert[]; rules:WatchRule[]; tags:Record<string,string[]> };
const defaultState:Persisted={saved:[],collections:initialCollections,ideas:initialIdeas,tasks:initialTasks,alerts:initialAlerts,rules:watchRules,tags:{}};

function usePersisted(){
  const [state,setState]=useState<Persisted>(()=>{if(typeof window==='undefined')return defaultState;const raw=localStorage.getItem('signalcraft-demo');try{return raw?{...defaultState,...JSON.parse(raw)}:defaultState}catch{return defaultState}});
  useEffect(()=>{localStorage.setItem('signalcraft-demo',JSON.stringify(state))},[state]);
  return [state,setState] as const;
}

function navigate(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new Event('signalcraft:navigate')); window.scrollTo({top:0,behavior:'smooth'}); }
function Sparkline({video}:{video:Video}){const data=video.snapshots.map(s=>s.views);const max=Math.max(...data),min=Math.min(...data);const pts=data.map((n,i)=>`${i*33},${30-((n-min)/(max-min||1))*25}`).join(' ');return <svg className="spark" viewBox="0 0 100 34" aria-label="播放量增长曲线"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" /></svg>}
function ScorePill({value}:{value:number}){return <span className={cn('score',value>=80?'excellent':value>=65?'good':'watch')}>{value}<small>/100</small></span>}
function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">◇</div><b>{title}</b><p>{body}</p>{action}</div>}

function Header({path,onTheme}:{path:string;onTheme:()=>void}){const isApp=path.startsWith('/app');return <><header className="site-header"><button className="brand" onClick={()=>navigate('/')} aria-label="返回首页"><span className="brand-glyph">SC</span><span>{BRAND}<small>CONTENT INTELLIGENCE</small></span></button><nav className="site-nav" aria-label="主导航">{isApp?<><button onClick={()=>navigate('/app')}>指挥台</button><button onClick={()=>navigate('/app/research')}>深度检索</button><button onClick={()=>navigate('/app/ideas')}>选题实验室</button></>:<><button onClick={()=>navigate('/discover')}>发现</button><button onClick={()=>navigate('/rankings')}>排行榜</button><button onClick={()=>navigate('/radar')}>机会雷达</button><button onClick={()=>navigate('/pricing')}>定价</button></>}</nav><div className="head-actions"><button className="icon-btn" onClick={onTheme} aria-label="切换颜色模式">◐</button><button className="ghost" onClick={()=>navigate(isApp?'/discover':'/app')}>{isApp?'公开发现':'进入工作室'}</button><button className="primary small" onClick={()=>navigate('/app')}>开始使用</button></div></header>{isApp&&<StudioNav path={path}/>}</>}
function StudioNav({path}:{path:string}){const items=[['/app','概览'],['/app/library/channels','频道资产'],['/app/library/videos','视频资产'],['/app/research','深度检索'],['/app/watchlists','监听'],['/app/benchmarks','对标组'],['/app/ideas','选题'],['/app/prompts','提示词'],['/app/settings','配置']];return <aside className="studio-nav"><p>工作室</p>{items.map(([href,label])=><button key={href} className={cn(path===href&&'active')} onClick={()=>navigate(href)}>{label}</button>)}</aside>}

function Filters({filters,setFilters}:{filters:ReturnType<typeof parseFilters>;setFilters:(v:ReturnType<typeof parseFilters>)=>void}){const patch=(key:string,value:string)=>{const next={...filters,[key]:value};setFilters(next);const q=serializeFilters(next);window.history.replaceState({},'',`${location.pathname}${q?`?${q}`:''}`)};return <div className="filters" aria-label="筛选器"><label>关键词<input value={filters.q} onChange={e=>patch('q',e.target.value)} placeholder="如：AI productivity"/></label><label>窗口<select value={filters.window} onChange={e=>patch('window',e.target.value)}><option value="24h">24 小时</option><option value="7d">近 7 天</option><option value="28d">近 28 天</option></select></label><label>语言<select value={filters.language} onChange={e=>patch('language',e.target.value)}><option value="all">全部语言</option><option value="英语">英语</option><option value="西班牙语">西班牙语</option><option value="葡萄牙语">葡萄牙语</option></select></label><label>形态<select value={filters.format} onChange={e=>patch('format',e.target.value)}><option value="all">短+长视频</option><option value="short">短视频</option><option value="long">长视频</option></select></label><label>订阅上限<select value={filters.maxSubs} onChange={e=>patch('maxSubs',e.target.value)}><option value="100000">10 万</option><option value="50000">5 万</option><option value="all">不限</option></select></label><label>最低评分<select value={filters.minScore} onChange={e=>patch('minScore',e.target.value)}><option value="70">70+</option><option value="80">80+</option><option value="0">不限</option></select></label></div>}

function VideoCard({video,state,setState,onDetail}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onDetail:(v:Video)=>void}){const o=scoreFor(video),channel=channelFor(video),saved=state.saved.includes(video.id);const toggle=()=>setState(s=>({...s,saved:s.saved.includes(video.id)?s.saved.filter(x=>x!==video.id):[...s.saved,video.id]}));return <article className="video-card"><div className="thumb" style={{backgroundImage:`linear-gradient(130deg,rgba(7,13,28,.18),rgba(11,102,110,.55)),url(${video.thumbnail})`}}><span>{video.format==='short'?'短视频':'长视频'} · {video.durationSeconds<60?`${video.durationSeconds}秒`:`${Math.round(video.durationSeconds/60)}分`}</span><ScorePill value={o.opportunityScore}/></div><div className="card-body"><div className="eyebrow">{video.topic} · {video.language} / {video.region}</div><button className="video-title" onClick={()=>onDetail(video)}>{video.title}</button><p className="channel-line">{channel.title} · {num.format(channel.subscribers)} 订阅</p><div className="metric-row"><b>{num.format(video.snapshots.at(-1)!.views)}<small>播放</small></b><b className="up">↑ {num.format(o.viewsPerHour)}<small>/小时</small></b><Sparkline video={video}/></div><div className="card-actions"><button onClick={toggle} aria-pressed={saved}>{saved?'已保存':'保存'}</button><button onClick={()=>onDetail(video)}>证据与行动</button></div></div></article>}

function DetailDrawer({video,state,setState,onClose,toast}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onClose:()=>void;toast:(t:string)=>void}){const o=scoreFor(video),channel=channelFor(video);const addIdea=()=>{const exists=state.ideas.some(i=>i.sourceVideoId===video.id);if(!exists)setState(s=>({...s,ideas:[...s.ideas,{id:`i${Date.now()}`,title:`拆解：${video.title.slice(0,24)}`,sourceVideoId:video.id,angle:'从异常表现中提取可验证的钩子',audience:'目标赛道的内容消费者',hypothesis:'明确收益 + 具体数字会提升点击',owner:'林语',status:'收集',note:'来自 SignalCraft 证据链',createdAt:new Date().toISOString()}]}));toast(exists?'该视频已有选题卡':'已创建选题卡，来源证据已带入');};const addBenchmark=()=>{setState(s=>({...s,collections:s.collections.map((c,i)=>i===0?{...c,items:[...new Set([...c.items,video.id])]}:c)}));toast('已加入「AI 效率工具」对标组');};return <div className="drawer-backdrop" role="presentation" onMouseDown={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label="视频证据详情" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="eyebrow">证据链 · {video.topic}</div><h2>{video.title}</h2><p className="channel-line">{channel.title} · 发布 {date(video.publishedAt)} · {video.risk==='low'?'低风险':'需复核风险'}</p><div className="score-hero"><ScorePill value={o.opportunityScore}/><div><b>机会评分</b><p>不是 AI 真相，而是基于公开样本的可复算信号。</p></div></div><div className="explain-grid"><div><span>VelocityScore</span><b>{o.velocityScore}</b><small>近时段播放增速</small></div><div><span>OutlierScore</span><b>{o.outlierScore}</b><small>相对频道中位数偏离</small></div><div><span>Confidence</span><b>{o.confidence}%</b><small>{video.snapshots.length} 个时间采样</small></div><div><span>相对表现</span><b>{o.viewsPerSubscriber}×</b><small>播放 / 频道订阅</small></div></div><section className="evidence"><h3>为什么值得看</h3>{o.reasons.map(r=><p key={r}>✓ {r}</p>)}<p>✓ 当前增长率为频道历史基线的 {o.growthRate}×；数据来源：演示快照。</p></section><section className="evidence"><h3>相似样本</h3>{videos.filter(v=>v.topic===video.topic&&v.id!==video.id).slice(0,3).map(v=><button className="similar" key={v.id} onClick={()=>toast(`可继续比较：${v.title.slice(0,20)}…`)}>{v.title}<ScorePill value={scoreFor(v).opportunityScore}/></button>)}</section><div className="drawer-actions"><button className="primary" onClick={addIdea}>创建选题</button><button onClick={addBenchmark}>加入对标组</button><button onClick={()=>toast('已创建监听规则（演示）')}>设置监听</button><button onClick={()=>navigator.clipboard?.writeText(`https://youtube.com/watch?v=${video.id}`).then(()=>toast('链接已复制'))}>复制链接</button></div></aside></div>}

function Discovery({mode,state,setState,openDetail}:{mode:'discover'|'rankings'|'radar';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){const [filters,setFilters]=useState(()=>typeof window==='undefined'?parseFilters(''):parseFilters(location.search));const [page,setPage]=useState(1);const rows=useMemo(()=>videos.filter(v=>{const o=scoreFor(v),c=channelFor(v),text=`${v.title} ${v.topic} ${v.tags.join(' ')}`.toLowerCase();return (!filters.q||text.includes(filters.q.toLowerCase()))&&(filters.language==='all'||v.language===filters.language)&&(filters.format==='all'||v.format===filters.format)&&(filters.maxSubs==='all'||c.subscribers<=Number(filters.maxSubs))&&o.opportunityScore>=Number(filters.minScore)}).sort((a,b)=>mode==='rankings'?b.snapshots.at(-1)!.views-a.snapshots.at(-1)!.views:scoreFor(b).opportunityScore-scoreFor(a).opportunityScore),[filters,mode]);const clusters=useMemo(()=>Object.entries(rows.reduce<Record<string,Video[]>>((acc,v)=>{(acc[v.topic]??=[]).push(v);return acc},{})),[rows]);if(mode==='radar')return <main className="page"><PageIntro label="机会雷达" title="不是更多卡片，而是可行动的机会簇" body="按新出现、加速中、低粉爆发和可复刻形式组织样本；每个结论都能回到证据。"/><Filters filters={filters} setFilters={setFilters}/><div className="radar-tabs"><button className="active">加速中</button><button>新出现</button><button>低粉爆发</button><button>可复刻形式</button></div><div className="cluster-list">{clusters.map(([topic,items])=>{const avg=Math.round(items.reduce((n,v)=>n+scoreFor(v).opportunityScore,0)/items.length);return <section className="cluster" key={topic}><div className="cluster-head"><div><span className="eyebrow">机会簇</span><h2>{topic}</h2><p>{items.length} 个样本 · 平均机会评分 {avg} · 以 {items[0].format==='short'?'短视频钩子':'长视频结构'} 为主</p></div><ScorePill value={avg}/></div><div className="cluster-evidence"><b>共同模式</b><span>{items.slice(0,3).map(v=>v.tags[0]).join(' · ')}</span><button onClick={()=>openDetail(items[0])}>查看证据链 →</button></div><div className="mini-grid">{items.slice(0,3).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div></section>})}</div></main>;return <main className="page"><PageIntro label={mode==='rankings'?'排行榜':'公开发现'} title={mode==='rankings'?'按信号强度筛出值得研究的样本':'今天值得关注的公开信号'} body="使用可分享筛选器，先找低订阅、高增长，再决定是否深入跟进。"/><Filters filters={filters} setFilters={setFilters}/><div className="result-toolbar"><span>找到 <b>{rows.length}</b> 个样本</span><span>排序：{mode==='rankings'?'播放量':'机会评分'}</span><button onClick={()=>navigator.clipboard?.writeText(location.href)}>复制筛选链接</button></div>{rows.length?<div className="video-grid">{rows.slice(0,page*6).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title="没有符合条件的样本" body="放宽评分或频道规模后再试。"/>}{rows.length>page*6&&<button className="load-more" onClick={()=>setPage(p=>p+1)}>加载更多样本</button>}</main>}

function PageIntro({label,title,body}:{label:string;title:string;body:string}){return <section className="page-intro"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{body}</p></section>}
function Home({openDetail}:{openDetail:(v:Video)=>void}){const picks=[...videos].sort((a,b)=>scoreFor(b).opportunityScore-scoreFor(a).opportunityScore).slice(0,3);return <main><section className="hero"><div><span className="eyebrow">YOUTUBE CONTENT INTELLIGENCE</span><h1>每天知道什么正在起势，<em>以及下一步该做什么。</em></h1><p>SignalCraft 将公开信号、可解释评分和行动工作流连接起来。3 分钟找到值得做的赛道与样本。</p><div className="hero-actions"><button className="primary" onClick={()=>navigate('/discover')}>免费查看今日信号</button><button onClick={()=>navigate('/methodology')}>了解评分方法 →</button></div><div className="proof"><span><b>18</b> 演示样本</span><span><b>4</b> 可复算评分维度</span><span><b>7 天</b> 低粉爆发窗口</span></div></div><div className="hero-panel"><div className="panel-top"><span>今日情报摘要</span><span className="live">● 模拟同步完成</span></div><div className="signal-number">6<span>个</span></div><p>出现异常表现的低订阅频道视频</p><div className="hero-list">{picks.map(v=><button key={v.id} onClick={()=>openDetail(v)}><ScorePill value={scoreFor(v).opportunityScore}/><span>{v.title}</span><b>↑</b></button>)}</div></div></section><section className="home-section"><div className="section-heading"><div><span className="eyebrow">TODAY&apos;S SIGNALS</span><h2>免费榜单预览</h2></div><button onClick={()=>navigate('/rankings')}>查看全部 →</button></div><div className="home-signal-grid">{picks.map(v=><button key={v.id} className="signal-row" onClick={()=>openDetail(v)}><span className="rank">0{picks.indexOf(v)+1}</span><div><b>{v.title}</b><small>{channelFor(v).title} · {v.topic}</small></div><ScorePill value={scoreFor(v).opportunityScore}/><Sparkline video={v}/></button>)}</div></section><section className="steps"><div><span>01</span><h3>公开发现</h3><p>按时间、语言、频道规模、增长表现快速筛选。</p></div><div><span>02</span><h3>判断证据</h3><p>看到增速、相对表现、置信度与风险提示。</p></div><div><span>03</span><h3>形成行动</h3><p>保存、对标、监听、创建选题并回看结果。</p></div></section><section className="cta-band"><div><span className="eyebrow">FROM SIGNAL TO SHIP</span><h2>发现不是终点，形成决策才是。</h2></div><button className="primary" onClick={()=>navigate('/app')}>打开我的工作室</button></section></main>}

function Methodology(){return <main className="page prose"><PageIntro label="方法与边界" title="清晰解释，才能让数据成为判断的辅助。" body="SignalCraft 不把评分伪装成结论；它只是让你更快找到值得验证的公开信号。"/><section><h2>评分如何组成</h2><div className="method-grid"><div><b>VelocityScore</b><p>根据最近快照间的每小时新增播放估计，不等同实时播放。</p></div><div><b>OutlierScore</b><p>播放相对订阅数与频道历史中位数的偏离。</p></div><div><b>Confidence</b><p>采样次数与数据完整程度。低样本明确降置信度。</p></div><div><b>OpportunityScore</b><p>增速 30%、异常 32%、新鲜度 18%、互动代理 12%、置信度 8%。</p></div></div></section><section><h2>数据与隐私</h2><p>演示环境仅使用本地种子数据。真实接入应通过 YouTube Data API、用户授权 OAuth 或合规第三方数据源；不抓取 YouTube 页面，不展示或提交真实密钥。</p></section><section><h2>局限性</h2><p>播放增长并不等于商业价值或可复制性。版权、敏感议题、地区文化、算法波动和数据缺口需要人工复核。</p></section></main>}
function Pricing(){const rows=[['公开发现与每日预览','✓','✓','✓'],['可解释机会评分','—','✓','✓'],['保存、对标与选题工作流','—','✓','✓'],['团队成员、评论与活动记录','—','—','✓'],['自定义监听与 Webhook 占位','—','—','✓']];return <main className="page"><PageIntro label="定价" title="先证明价值，再决定升级。" body="这是完整交互演示，不接入真实支付、客服或自动扣费。"/><div className="pricing-grid">{[['Free','¥0','体验公开发现与低粉爆款样本'],['Pro','¥39 / 月','个人创作者的完整研究工作流'],['Team','¥299 / 月','团队协作、对标与监听演示']].map(([name,price,copy])=><article className={cn('price-card',name==='Pro'&&'featured')} key={name}><span>{name==='Pro'?'推荐':'计划'}</span><h2>{name}</h2><b>{price}</b><p>{copy}</p><button className={name==='Pro'?'primary':''} onClick={()=>navigate('/app')}>{name==='Free'?'免费开始':'查看演示工作室'}</button></article>)}</div><div className="feature-table"><div className="feature-row heading"><b>功能</b><b>Free</b><b>Pro</b><b>Team</b></div>{rows.map(r=><div className="feature-row" key={r[0]}>{r.map((x,i)=><span key={i}>{x}</span>)}</div>)}</div></main>}

function AppHome({state,setState,openDetail,toast}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void;toast:(t:string)=>void}){const high=videos.filter(v=>scoreFor(v).opportunityScore>=80).slice(0,3);return <main className="app-page"><PageIntro label="今日指挥台 · 演示工作区" title="先处理异常信号，再推进内容决策。" body="所有保存、任务、选题和监听均保存在当前浏览器，用于完整演示。"/><div className="command-grid"><section className="command-main"><div className="section-heading"><h2>待处理信号</h2><button onClick={()=>navigate('/discover')}>进入发现页 →</button></div>{high.map(v=><button className="alert-card" key={v.id} onClick={()=>openDetail(v)}><ScorePill value={scoreFor(v).opportunityScore}/><div><b>{v.title}</b><p>{scoreFor(v).reasons[0]}</p></div><span>查看 →</span></button>)}</section><section className="command-side"><h2>同步状态</h2><div className="sync"><span>●</span><b>MockDataProvider</b><small>最近同步：刚刚</small></div><div className="quota"><span>演示额度</span><b>82%</b><i><em /></i><small>真实 API 尚未连接</small></div><button className="primary full" onClick={()=>toast('已模拟执行一次数据同步')}>模拟同步</button></section></div><div className="dashboard-grid"><section><div className="section-heading"><h2>任务清单</h2><button onClick={()=>setState(s=>({...s,tasks:[...s.tasks,{id:`t${Date.now()}`,title:'新建内容验证任务',status:'待办',owner:'林语',due:'本周'}]}))}>+ 新建</button></div>{state.tasks.map(t=><button className="task" key={t.id} onClick={()=>setState(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,status:x.status==='完成'?'待办':'完成'}:x)}))}><span className={cn('check',t.status==='完成'&&'done')}>✓</span><div><b>{t.title}</b><small>{t.owner} · {t.due}</small></div><em>{t.status}</em></button>)}</section><section><div className="section-heading"><h2>通知中心</h2><button onClick={()=>setState(s=>({...s,alerts:s.alerts.map(a=>({...a,read:true}))}))}>全部已读</button></div>{state.alerts.map(a=><button className={cn('notification',!a.read&&'unread')} key={a.id} onClick={()=>a.sourceVideoId&&openDetail(videos.find(v=>v.id===a.sourceVideoId)!)}><span>↗</span><div><b>{a.title}</b><small>{a.body}</small></div><time>{date(a.createdAt)}</time></button>)}</section></div></main>}

function Library({kind,state,setState,openDetail}:{kind:'channels'|'videos';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){if(kind==='channels')return <main className="app-page"><PageIntro label="频道资产" title="跟踪值得长期研究的频道。" body="按负责人、标签与健康度沉淀频道资产。"/><div className="table-wrap"><table><thead><tr><th>频道</th><th>标签</th><th>订阅</th><th>健康度</th><th>负责人</th><th>最近同步</th></tr></thead><tbody>{channels.map(c=><tr key={c.id}><td><b>{c.title}</b><small>{c.handle}</small></td><td>{c.tags.map(t=><span className="tag" key={t}>{t}</span>)}</td><td>{num.format(c.subscribers)}</td><td><span className="health"><i style={{width:`${c.health}%`}} />{c.health}</span></td><td>{c.owner}</td><td>{c.lastSync}</td></tr>)}</tbody></table></div></main>;return <main className="app-page"><PageIntro label="视频资产" title="保存的信号，才能变成可复用的研究资产。" body="为视频加标签、写笔记、加入选题或对标组。"/>{state.saved.length?<div className="video-grid">{videos.filter(v=>state.saved.includes(v.id)).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title="还没有保存视频" body="在公开发现或雷达页面点“保存”，这里会自动出现。" action={<button className="primary" onClick={()=>navigate('/discover')}>去发现样本</button>}/>}</main>}

function Research({state,setState,openDetail}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){return <main className="app-page"><PageIntro label="深度检索" title="用多个条件，缩小到可验证的内容信号。" body="筛选结果可复制链接并在浏览器内保持状态。"/><Discovery mode="discover" state={state} setState={setState} openDetail={openDetail}/></main>}
function Watchlists({state,setState,toast}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;toast:(t:string)=>void}){return <main className="app-page"><PageIntro label="监听规则" title="让异常自己来找你。" body="通知渠道与触发记录均为演示占位；真实发送服务未接入。"/><div className="watch-grid">{state.rules.map(rule=><article className="watch-card" key={rule.id}><div><span className="tag">{rule.type}</span><h2>{rule.name}</h2><p>{rule.frequency} · 机会评分 ≥ {rule.threshold} · {rule.channel}</p></div><label className="toggle"><input type="checkbox" checked={!rule.paused} onChange={()=>setState(s=>({...s,rules:s.rules.map(r=>r.id===rule.id?{...r,paused:!r.paused}:r)}))}/><span /></label></article>)}</div><div className="inline-form"><input placeholder="例如：英语 AI 效率低粉爆发" id="ruleName"/><select id="ruleType"><option>关键词</option><option>频道</option><option>赛道</option></select><button className="primary" onClick={()=>{const input=document.getElementById('ruleName') as HTMLInputElement;const type=document.getElementById('ruleType') as HTMLSelectElement;if(!input.value.trim())return toast('请先填写规则名称');setState(s=>({...s,rules:[...s.rules,{id:`w${Date.now()}`,name:input.value,type:type.value as WatchRule['type'],threshold:75,frequency:'每 6 小时',channel:'站内通知',paused:false}]}));input.value='';toast('监听规则已创建')}}>创建规则</button><button onClick={()=>{const source=videos[4];setState(s=>({...s,alerts:[{id:`a${Date.now()}`,title:'模拟触发：低粉爆发',body:`${source.title} 达到 ${scoreFor(source).opportunityScore} 分`,createdAt:new Date().toISOString(),read:false,sourceVideoId:source.id},...s.alerts]}));toast('已模拟一条触发事件')}}>模拟触发</button></div></main>}
function Benchmarks({state,toast}:{state:Persisted;toast:(t:string)=>void}){const [compare,setCompare]=useState<string[]>([]);const candidate=videos.filter(v=>state.saved.includes(v.id));return <main className="app-page"><PageIntro label="对标组与比较" title="比较 2–5 个样本，寻找共同模式。" body="所有结论都保留回到视频信号与指标的入口。"/><div className="collection-grid">{state.collections.map(c=><article className="collection" key={c.id}><span style={{background:c.color}} /><div><h2>{c.name}</h2><p>{c.items.length} 个项目 · {c.shared?'已共享':'私有'}</p></div><button onClick={()=>toast('共享笔记演示：已复制分享链接')}>分享</button></article>)}</div><div className="compare-picker"><h2>快速比较</h2><p>选择 2–5 个已保存的视频。</p>{candidate.length?candidate.map(v=><label key={v.id}><input type="checkbox" checked={compare.includes(v.id)} onChange={()=>setCompare(x=>x.includes(v.id)?x.filter(i=>i!==v.id):x.length<5?[...x,v.id]:x)}/>{v.title}</label>):<p>先在发现页保存至少两个视频。</p>}</div>{compare.length>=2&&<div className="compare-table"><div className="compare-heading"><b>指标</b>{compare.map(id=><b key={id}>{videos.find(v=>v.id===id)!.title.slice(0,14)}…</b>)}</div>{[['机会评分',(v:Video)=>scoreFor(v).opportunityScore],['播放 / 订阅',(v:Video)=>`${scoreFor(v).viewsPerSubscriber}×`],['每小时播放',(v:Video)=>num.format(scoreFor(v).viewsPerHour)],['发布时间',(v:Video)=>date(v.publishedAt)],['共同标签',(v:Video)=>v.tags.slice(0,2).join(' / ')]].map(([label,fn])=><div className="compare-row" key={label as string}><span>{label as string}</span>{compare.map(id=><span key={id}>{(fn as (v:Video)=>React.ReactNode)(videos.find(v=>v.id===id)!)}</span>)}</div>)}</div>}</main>}
function Ideas({state,setState,toast}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;toast:(t:string)=>void}){const statuses:IdeaStatus[]=['收集','验证','制作中','已发布','复盘'];return <main className="app-page"><PageIntro label="选题实验室" title="从信号到制作，再到复盘。" body="每张选题卡都保留来源信号，避免凭感觉断开数据。"/><div className="kanban">{statuses.map(status=><section key={status}><div className="kanban-head"><b>{status}</b><span>{state.ideas.filter(i=>i.status===status).length}</span></div>{state.ideas.filter(i=>i.status===status).map(i=>{const v=videos.find(v=>v.id===i.sourceVideoId);return <article className="idea" key={i.id}><span className="tag">来源 {v?scoreFor(v).opportunityScore:'—'} 分</span><h3>{i.title}</h3><p>{i.angle}</p><small>{i.owner} · {date(i.createdAt)}</small><select value={i.status} onChange={e=>setState(s=>({...s,ideas:s.ideas.map(x=>x.id===i.id?{...x,status:e.target.value as IdeaStatus}:x)}))}>{statuses.map(x=><option key={x}>{x}</option>)}</select></article>})}<button className="add-idea" onClick={()=>{setState(s=>({...s,ideas:[...s.ideas,{id:`i${Date.now()}`,title:'未命名选题实验',sourceVideoId:'v1',angle:'待补充切入角度',audience:'待定义',hypothesis:'待验证',owner:'林语',status,note:'',createdAt:new Date().toISOString()}]}));toast(`已在「${status}」创建卡片`)}}>＋</button></section>)}</div></main>}
function Prompts({toast}:{toast:(t:string)=>void}){return <main className="app-page"><PageIntro label="提示词库" title="把研究方法沉淀成可复用模板。" body="变量模板会在真实 AI 接入后带入选题上下文；目前只演示复制。"/><div className="prompt-list">{promptTemplates.map(p=><article key={p.id}><div><span className="tag">{p.category}</span><h2>{p.title}</h2><p>{p.body}</p><small>{p.version} · {p.enabled?'已启用':'已停用'}</small></div><button className="primary" onClick={()=>navigator.clipboard?.writeText(p.body).then(()=>toast('提示词模板已复制'))}>复制模板</button></article>)}</div></main>}
function Settings(){return <main className="app-page"><PageIntro label="配置" title="为真实服务预留边界，不在前端保存密钥。" body="当前为演示配置页，所有敏感字段均不接收或显示真实密钥。"/><div className="settings-grid"><section><h2>数据源</h2><p><b>MockDataProvider</b> · 演示数据已启用</p><button disabled>连接 YouTube Data API（需服务端）</button></section><section><h2>刷新计划</h2><select defaultValue="6"><option value="6">每 6 小时</option><option value="24">每日</option></select><p>真实任务队列尚未接入。</p></section><section><h2>团队成员</h2><p>林语 · Owner</p><p>Alex · Editor</p><p>陈帆 · Viewer</p></section><section><h2>通知渠道</h2><p>站内通知：已启用</p><p>邮件、Slack、Webhook：演示占位</p></section></div></main>}

export default function SignalCraftApp(){const [path,setPath]=useState('/');const [theme,setTheme]=useState('light');const [state,setState]=usePersisted();const [drawer,setDrawer]=useState<Video|null>(null);const [toast,setToast]=useState<Toast>(null);useEffect(()=>{const read=()=>setPath(location.pathname);read();addEventListener('popstate',read);addEventListener('signalcraft:navigate',read);return()=>{removeEventListener('popstate',read);removeEventListener('signalcraft:navigate',read)}},[]);useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);const notify=(message:string)=>{setToast({message});setTimeout(()=>setToast(null),2400)};const content=path==='/'?<Home openDetail={setDrawer}/>:path==='/discover'?<Discovery mode="discover" state={state} setState={setState} openDetail={setDrawer}/>:path==='/rankings'?<Discovery mode="rankings" state={state} setState={setState} openDetail={setDrawer}/>:path==='/radar'?<Discovery mode="radar" state={state} setState={setState} openDetail={setDrawer}/>:path==='/methodology'?<Methodology/>:path==='/pricing'?<Pricing/>:path==='/app'?<AppHome state={state} setState={setState} openDetail={setDrawer} toast={notify}/>:path==='/app/library/channels'?<Library kind="channels" state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/library/videos'?<Library kind="videos" state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/research'?<Research state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/watchlists'?<Watchlists state={state} setState={setState} toast={notify}/>:path==='/app/benchmarks'||path==='/app/compare'?<Benchmarks state={state} toast={notify}/>:path==='/app/ideas'?<Ideas state={state} setState={setState} toast={notify}/>:path==='/app/prompts'?<Prompts toast={notify}/>:path==='/app/settings'?<Settings/>:<Home openDetail={setDrawer}/>;return <div className="app-shell"><Header path={path} onTheme={()=>setTheme(t=>t==='light'?'dark':'light')}/>{content}{drawer&&<DetailDrawer video={drawer} state={state} setState={setState} onClose={()=>setDrawer(null)} toast={notify}/>} {toast&&<div className="toast">✓ {toast.message}</div>}</div>}
