'use client';

import { useEffect, useMemo, useState } from 'react';
import { channels, getOpportunity, initialAlerts, initialCollections, initialIdeas, initialTasks, promptTemplates, videos, watchRules } from '@/src/lib/mock';
import { parseFilters, serializeFilters } from '@/src/lib/scoring.mjs';
import type { Alert, Collection, Idea, IdeaStatus, Task, Video, WatchRule } from '@/src/lib/types';
import { searchYouTubeSignals } from '@/src/lib/youtube';
import ChannelDoctor from './channel-doctor';

const BRAND = process.env.NEXT_PUBLIC_BRAND_NAME || 'SignalCraft';
const cn = (...names:(string|false|undefined)[]) => names.filter(Boolean).join(' ');
const num = new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1});
const date = (iso:string) => new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const channelFor = (v:Video) => channels.find(c=>c.id===v.channelId) || {id:v.channelId,title:'公开频道',handle:'',subscribers:v.snapshots.at(-1)?.subscribers||0,language:v.language,region:v.region,medianViews:1,health:0,tags:[],owner:'未分配',lastSync:'刚刚'};
const scoreFor = (v:Video) => getOpportunity(v);

type Toast = {message:string; kind?:'success'|'info'} | null;
type Persisted = { saved:Video[]; collections:Collection[]; ideas:Idea[]; tasks:Task[]; alerts:Alert[]; rules:WatchRule[]; tags:Record<string,string[]> };
const defaultState:Persisted={saved:[],collections:initialCollections,ideas:initialIdeas,tasks:initialTasks,alerts:initialAlerts,rules:watchRules,tags:{}};

function usePersisted(){
  const [state,setState]=useState<Persisted>(()=>{if(typeof window==='undefined')return defaultState;const raw=localStorage.getItem('signalcraft-workspace-v2');try{return raw?{...defaultState,...JSON.parse(raw)}:defaultState}catch{return defaultState}});
  useEffect(()=>{localStorage.setItem('signalcraft-workspace-v2',JSON.stringify(state))},[state]);
  return [state,setState] as const;
}

function navigate(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new Event('signalcraft:navigate')); window.scrollTo({top:0,behavior:'smooth'}); }
function Sparkline({video}:{video:Video}){const data=video.snapshots.map(s=>s.views);const max=Math.max(...data),min=Math.min(...data);const pts=data.map((n,i)=>`${i*33},${30-((n-min)/(max-min||1))*25}`).join(' ');return <svg className="spark" viewBox="0 0 100 34" aria-label="播放量增长曲线"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" /></svg>}
function ScorePill({value}:{value:number}){return <span className={cn('score',value>=80?'excellent':value>=65?'good':'watch')}>{value}<small>/100</small></span>}
function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">◇</div><b>{title}</b><p>{body}</p>{action}</div>}

function Header({path,onTheme}:{path:string;onTheme:()=>void}){const isApp=path.startsWith('/app');return <><header className="site-header"><button className="brand" onClick={()=>navigate('/')} aria-label="返回首页"><span className="brand-glyph">SC</span><span>{BRAND}<small>CONTENT INTELLIGENCE</small></span></button><nav className="site-nav" aria-label="主导航">{isApp?<><button onClick={()=>navigate('/app')}>指挥台</button><button onClick={()=>navigate('/app/research')}>深度检索</button><button onClick={()=>navigate('/app/ideas')}>选题实验室</button></>:<><button onClick={()=>navigate('/discover')}>发现</button><button onClick={()=>navigate('/rankings')}>排行榜</button><button onClick={()=>navigate('/radar')}>机会雷达</button><button onClick={()=>navigate('/doctor')}>频道诊断</button><button onClick={()=>navigate('/pricing')}>定价</button></>}</nav><div className="head-actions"><button className="icon-btn" onClick={onTheme} aria-label="切换颜色模式">◐</button><button className="ghost" onClick={()=>navigate(isApp?'/discover':'/app')}>{isApp?'公开发现':'进入工作室'}</button><button className="primary small" onClick={()=>navigate('/app')}>开始使用</button></div></header>{isApp&&<StudioNav path={path}/>}</>}
function StudioNav({path}:{path:string}){const items=[['/app','概览'],['/app/doctor','频道诊断'],['/app/library/channels','频道资产'],['/app/library/videos','视频资产'],['/app/research','深度检索'],['/app/watchlists','监听'],['/app/benchmarks','对标组'],['/app/ideas','选题'],['/app/prompts','提示词'],['/app/settings','配置']];return <aside className="studio-nav"><p>工作室</p>{items.map(([href,label])=><button key={href} className={cn(path===href&&'active')} onClick={()=>navigate(href)}>{label}</button>)}</aside>}

function Filters({filters,setFilters,hideKeyword=false}:{filters:ReturnType<typeof parseFilters>;setFilters:(v:ReturnType<typeof parseFilters>)=>void;hideKeyword?:boolean}){const patch=(key:string,value:string)=>{const next={...filters,[key]:value};setFilters(next);const q=serializeFilters(next);window.history.replaceState({},'',`${location.pathname}${q?`?${q}`:''}`)};return <div className="filters" aria-label="筛选器">{!hideKeyword&&<label>关键词<input value={filters.q} onChange={e=>patch('q',e.target.value)} placeholder="如：AI productivity"/></label>}<label>窗口<select value={filters.window} onChange={e=>patch('window',e.target.value)}><option value="24h">24 小时</option><option value="7d">近 7 天</option><option value="28d">近 28 天</option></select></label><label>市场<select value={filters.region} onChange={e=>patch('region',e.target.value)}><option value="US">美国</option><option value="GB">英国</option><option value="JP">日本</option><option value="BR">巴西</option><option value="MX">墨西哥</option><option value="IN">印度</option><option value="ID">印度尼西亚</option></select></label><label>语言<select value={filters.language} onChange={e=>patch('language',e.target.value)}><option value="all">全部语言</option><option value="英语">英语</option><option value="西班牙语">西班牙语</option><option value="葡萄牙语">葡萄牙语</option></select></label><label>形态<select value={filters.format} onChange={e=>patch('format',e.target.value)}><option value="all">短+长视频</option><option value="short">短视频</option><option value="long">长视频</option></select></label><label>订阅上限<select value={filters.maxSubs} onChange={e=>patch('maxSubs',e.target.value)}><option value="100000">10 万</option><option value="50000">5 万</option><option value="all">不限</option></select></label><label>最低评分<select value={filters.minScore} onChange={e=>patch('minScore',e.target.value)}><option value="70">70+</option><option value="80">80+</option><option value="0">不限</option></select></label></div>}

function RankingFilters({filters,setFilters}:{filters:ReturnType<typeof parseFilters>;setFilters:(v:ReturnType<typeof parseFilters>)=>void}){
  const patch=(key:string,value:string)=>{const next={...filters,[key]:value};setFilters(next);const query=serializeFilters({...next,q:''});window.history.replaceState({},'',`${location.pathname}${query?`?${query}`:''}`)};
  return <aside className="ranking-filters" aria-label="排行榜筛选"><div><span className="eyebrow">榜单筛选</span><h2>全站趋势</h2><p>不需要填写关键词，直接按近期播放表现取样。</p></div><label>内容形态<select value={filters.format} onChange={event=>patch('format',event.target.value)}><option value="all">短 + 长视频</option><option value="short">只看短视频</option><option value="long">只看长视频</option></select></label><label>时间窗口<select value={filters.window} onChange={event=>patch('window',event.target.value)}><option value="24h">24 小时</option><option value="7d">近 7 天</option><option value="28d">近 28 天</option></select></label><label>市场<select value={filters.region} onChange={event=>patch('region',event.target.value)}><option value="US">美国</option><option value="GB">英国</option><option value="JP">日本</option><option value="BR">巴西</option><option value="MX">墨西哥</option><option value="IN">印度</option><option value="ID">印度尼西亚</option></select></label><label>订阅规模<select value={filters.maxSubs} onChange={event=>patch('maxSubs',event.target.value)}><option value="100000">10 万以内</option><option value="50000">5 万以内</option><option value="all">不限</option></select></label><label>内容语言<select value={filters.language} onChange={event=>patch('language',event.target.value)}><option value="all">全部语言</option><option value="英语">英语</option><option value="西班牙语">西班牙语</option><option value="葡萄牙语">葡萄牙语</option></select></label><button onClick={()=>patch('format','all')}>重置内容形态</button><small>数据为 YouTube 公开 API 单次快照，不等同平台官方热榜。</small></aside>
}

function VideoCard({video,state,setState,onDetail}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onDetail:(v:Video)=>void}){const o=scoreFor(video),channel=channelFor(video),saved=state.saved.some(item=>item.id===video.id);const toggle=()=>setState(s=>({...s,saved:s.saved.some(item=>item.id===video.id)?s.saved.filter(item=>item.id!==video.id):[...s.saved,video]}));const watch=()=>video.sourceUrl?window.location.assign(video.sourceUrl):onDetail(video);return <article className="video-card"><div className="thumb" role="link" tabIndex={0} onClick={watch} onKeyDown={event=>event.key==='Enter'&&watch()} title="打开并观看此视频" style={{position:'relative',overflow:'hidden',background:'linear-gradient(130deg,#15233b,#16777b)',cursor:'pointer'}}>{video.thumbnail&&<img src={video.thumbnail} alt={`${video.title} 视频缩略图`} loading="lazy" onError={event=>{event.currentTarget.style.display='none'}} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',zIndex:1}}/>}<div aria-hidden="true" style={{position:'absolute',inset:0,display:'grid',placeContent:'center',gap:4,textAlign:'center',zIndex:0,background:'radial-gradient(circle at 32% 28%,rgba(61,224,218,.45),transparent 31%),linear-gradient(130deg,#162444,#087f84)'}}><b style={{fontSize:28}}>▶</b><span style={{fontSize:12,fontWeight:800,letterSpacing:1}}>{video.topic}</span></div><i aria-hidden="true" style={{position:'absolute',inset:0,zIndex:2,background:'linear-gradient(130deg,rgba(7,13,28,.14),rgba(11,102,110,.45))',pointerEvents:'none'}}/><span style={{position:'relative',zIndex:3}}>{video.format==='short'?'短视频':'长视频'} · {video.durationSeconds<60?`${video.durationSeconds}秒`:`${Math.round(video.durationSeconds/60)}分`}</span><span style={{position:'relative',zIndex:3}}><ScorePill value={o.opportunityScore}/></span></div><div className="card-body"><div className="eyebrow">{video.topic} · {video.language} / {video.region}</div><button className="video-title" onClick={watch}>{video.title}</button><p className="channel-line">{channel.title} · {num.format(channel.subscribers)} 订阅</p><div className="metric-row"><b>{num.format(video.snapshots.at(-1)!.views)}<small>播放</small></b><b className="up">↑ {num.format(o.viewsPerHour)}<small>/小时</small></b><Sparkline video={video}/></div><div className="card-actions"><button onClick={toggle} aria-pressed={saved}>{saved?'已保存':'保存'}</button><button onClick={()=>onDetail(video)}>证据与行动</button>{video.sourceUrl&&<button onClick={watch}>观看原视频 ↗</button>}</div></div></article>}

function DetailDrawer({video,state,setState,onClose,toast}:{video:Video;state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;onClose:()=>void;toast:(t:string)=>void}){const o=scoreFor(video),channel=channelFor(video);const addIdea=()=>{const exists=state.ideas.some(i=>i.sourceVideoId===video.id);if(!exists)setState(s=>({...s,ideas:[...s.ideas,{id:`i${Date.now()}`,title:`拆解：${video.title.slice(0,24)}`,sourceVideoId:video.id,angle:'从异常表现中提取可验证的钩子',audience:'目标赛道的内容消费者',hypothesis:'明确收益 + 具体数字会提升点击',owner:'当前用户',status:'收集',note:'来自 SignalCraft 证据链',createdAt:new Date().toISOString()}]}));toast(exists?'该视频已有选题卡':'已创建选题卡，来源证据已带入');};const addBenchmark=()=>{setState(s=>{const first=s.collections[0];return {...s,collections:first?s.collections.map((c,i)=>i===0?{...c,items:[...new Set([...c.items,video.id])]}:c):[{id:`c${Date.now()}`,name:'未命名对标组',type:'对标组',color:'#ff3b30',items:[video.id],shared:false}]}});toast('已加入对标组');};const openDoctor=()=>{if(!channel.url){toast('该视频没有可用的公开频道链接，暂不能自动诊断。');return}navigate(`/doctor?channel=${encodeURIComponent(channel.url)}`)};return <div className="drawer-backdrop" role="presentation" onMouseDown={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label="视频证据详情" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="eyebrow">证据链 · {video.topic}</div><h2>{video.title}</h2><p className="channel-line">{channel.title} · 发布 {date(video.publishedAt)} · {video.risk==='low'?'低风险':'需复核风险'}</p><div className="score-hero"><ScorePill value={o.opportunityScore}/><div><b>机会评分</b><p>不是 AI 真相，而是基于公开样本的可复算信号。</p></div></div><div className="explain-grid"><div><span>VelocityScore</span><b>{o.velocityScore}</b><small>当前快照平均播放速度</small></div><div><span>OutlierScore</span><b>{o.outlierScore}</b><small>相对频道公开订阅规模偏离</small></div><div><span>Confidence</span><b>{o.confidence}%</b><small>{video.snapshots.length} 个时间采样</small></div><div><span>相对表现</span><b>{o.viewsPerSubscriber}×</b><small>播放 / 频道订阅</small></div></div><section className="evidence"><h3>为什么值得看</h3>{o.reasons.map(r=><p key={r}>✓ {r}</p>)}<p>✓ 当前增长率为频道历史基线的 {o.growthRate}×；数据来源：当前 YouTube 公开数据单次快照。</p></section><section className="evidence"><h3>相似样本</h3><p>需要对公开视频持续采样后，才会给出相似表现判断。</p></section><div className="drawer-actions"><button className="primary" onClick={addIdea}>创建选题</button><button onClick={addBenchmark}>加入对标组</button><button onClick={openDoctor}>频道诊断</button><button onClick={()=>navigate('/app/watchlists')}>设置监听</button><button onClick={()=>navigator.clipboard?.writeText(video.sourceUrl||`https://youtube.com/watch?v=${video.id}`).then(()=>toast('链接已复制'))}>复制链接</button></div></aside></div>}

function DemoDiscovery({mode,state,setState,openDetail}:{mode:'discover'|'rankings'|'radar';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){const [filters,setFilters]=useState(()=>typeof window==='undefined'?parseFilters(''):parseFilters(location.search));const [page,setPage]=useState(1);const rows=useMemo(()=>videos.filter(v=>{const o=scoreFor(v),c=channelFor(v),text=`${v.title} ${v.topic} ${v.tags.join(' ')}`.toLowerCase();return (!filters.q||text.includes(filters.q.toLowerCase()))&&(filters.language==='all'||v.language===filters.language)&&(filters.format==='all'||v.format===filters.format)&&(filters.maxSubs==='all'||c.subscribers<=Number(filters.maxSubs))&&o.opportunityScore>=Number(filters.minScore)}).sort((a,b)=>mode==='rankings'?b.snapshots.at(-1)!.views-a.snapshots.at(-1)!.views:scoreFor(b).opportunityScore-scoreFor(a).opportunityScore),[filters,mode]);const clusters=useMemo(()=>Object.entries(rows.reduce<Record<string,Video[]>>((acc,v)=>{(acc[v.topic]??=[]).push(v);return acc},{})),[rows]);if(mode==='radar')return <main className="page"><PageIntro label="机会雷达" title="不是更多卡片，而是可行动的机会簇" body="按新出现、加速中、低粉爆发和可复刻形式组织样本；每个结论都能回到证据。"/><Filters filters={filters} setFilters={setFilters}/><div className="radar-tabs"><button className="active">加速中</button><button>新出现</button><button>低粉爆发</button><button>可复刻形式</button></div><div className="cluster-list">{clusters.map(([topic,items])=>{const avg=Math.round(items.reduce((n,v)=>n+scoreFor(v).opportunityScore,0)/items.length);return <section className="cluster" key={topic}><div className="cluster-head"><div><span className="eyebrow">机会簇</span><h2>{topic}</h2><p>{items.length} 个样本 · 平均机会评分 {avg} · 以 {items[0].format==='short'?'短视频钩子':'长视频结构'} 为主</p></div><ScorePill value={avg}/></div><div className="cluster-evidence"><b>共同模式</b><span>{items.slice(0,3).map(v=>v.tags[0]).join(' · ')}</span><button onClick={()=>openDetail(items[0])}>查看证据链 →</button></div><div className="mini-grid">{items.slice(0,3).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div></section>})}</div></main>;return <main className="page"><PageIntro label={mode==='rankings'?'排行榜':'公开发现'} title={mode==='rankings'?'按信号强度筛出值得研究的样本':'今天值得关注的公开信号'} body="使用可分享筛选器，先找低订阅、高增长，再决定是否深入跟进。"/><Filters filters={filters} setFilters={setFilters}/><div className="result-toolbar"><span>找到 <b>{rows.length}</b> 个样本</span><span>排序：{mode==='rankings'?'播放量':'机会评分'}</span><button onClick={()=>navigator.clipboard?.writeText(location.href)}>复制筛选链接</button></div>{rows.length?<div className="video-grid">{rows.slice(0,page*6).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title="没有符合条件的样本" body="放宽评分或频道规模后再试。"/>}{mode!=='rankings'&&rows.length>page*6&&<button className="load-more" onClick={()=>setPage(p=>p+1)}>加载更多样本</button>}</main>}

function RankingBoard({longRows,shortRows,selectedFormat,onDetail}:{longRows:Video[];shortRows:Video[];selectedFormat:'all'|'short'|'long';onDetail:(v:Video)=>void}){
  const longVideos=longRows.slice(0,10);
  const shortVideos=shortRows.slice(0,10);
  const renderList=(items:Video[],format:'long'|'short')=>items.length?items.map((video,index)=>{const score=scoreFor(video),channel=channelFor(video);const watch=()=>video.sourceUrl?window.location.assign(video.sourceUrl):onDetail(video);return <button className="ranking-row" key={video.id} onClick={watch} title="打开并观看此视频"><span className={cn('ranking-position',index<3&&'top')}>{String(index+1).padStart(2,'0')}</span><span className="ranking-thumb" style={{backgroundImage:`url(${video.thumbnail})`}}><em>{format==='short'?'短':'长'}</em></span><span className="ranking-title"><b>{video.title}</b><small>{channel.title} · {video.topic} · {num.format(channel.subscribers)} 订阅</small></span><span className="ranking-stat"><b>{num.format(video.snapshots.at(-1)!.views)}</b><small>播放</small></span><span className="ranking-stat velocity"><b>↑ {num.format(score.viewsPerHour)}</b><small>/小时</small></span><ScorePill value={score.opportunityScore}/><span className="ranking-open">观看 ↗</span></button>}):<div className="ranking-empty">当前筛选范围内还没有{format==='short'?'短视频':'长视频'}样本。调整内容形态或关键词后再试。</div>;
  const section=(format:'long'|'short',items:Video[])=> <section className={cn('ranking-section',format)} key={format}><div className="ranking-section-head"><div><span className="eyebrow">TOP 10 · 公开样本</span><h2>{format==='long'?'长视频榜单':'短视频榜单'}</h2><p>{format==='long'?'适合拆解叙事、结构和选题深度。':'适合研究开头钩子、节奏和传播形式。'}</p></div><b>{items.length}<small>/10</small></b></div><div className="ranking-list">{renderList(items,format)}</div></section>;
  return <div className="ranking-board">{selectedFormat!=='short'&&section('long',longVideos)}{selectedFormat!=='long'&&section('short',shortVideos)}</div>
}

function Discovery({mode,state,setState,openDetail}:{mode:'discover'|'rankings'|'radar'|'research';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){
  const [filters,setFilters]=useState(()=>{const selected=typeof window==='undefined'?parseFilters(''):parseFilters(location.search);if(mode==='rankings')return {...selected,q:'',maxSubs:'all',minScore:'0'};if(mode==='discover'||mode==='radar')return {...selected,q:''};return selected});
  const [page,setPage]=useState(1);
  const [remote,setRemote]=useState<Video[]|null>(null);
  const [rankingData,setRankingData]=useState<{short:Video[];long:Video[]}|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const [radarView,setRadarView]=useState<'velocity'|'new'|'breakout'|'repeatable'>('velocity');
  // Discover and Radar are real-data surfaces. Never silently replace a
  // failed API response with attractive demo cards, otherwise users cannot
  // tell that the current YouTube quota has no usable samples.
  const source=remote||[];
  const runSearch=async()=>{
    if(mode==='research'&&!filters.q.trim()){setRemote(null);setError('请输入一个赛道关键词，例如 AI productivity。');return;}
    setLoading(true);setError('');
    try{
      const selectedFormat=filters.format==='short'||filters.format==='long'?filters.format:undefined;
      const result=await searchYouTubeSignals({query:mode==='research'?filters.q:'',language:filters.language,region:filters.region,window:filters.window,maxSubscribers:filters.maxSubs,format:selectedFormat,ranking:mode!=='research'});
      result.channels.forEach(channel=>{const index=channels.findIndex(item=>item.id===channel.id);if(index>=0)Object.assign(channels[index],channel);else channels.push(channel)});
      setRemote(result.videos);setPage(1);
    }catch(reason){setError(reason instanceof Error?reason.message:'YouTube 公开数据暂时无法读取。');}
    finally{setLoading(false);}
  };
  const runRankingSearch=async()=>{
    const query='';
    const formats=(filters.format==='all'?['short','long']:[filters.format]) as Array<'short'|'long'>;
    setLoading(true);setError('');
    try{
      const results=await Promise.all(formats.map(async format=>[format,await searchYouTubeSignals({query,language:filters.language,region:filters.region,window:filters.window,maxSubscribers:filters.maxSubs,format,ranking:true})] as const));
      const next:{short:Video[];long:Video[]}={short:[],long:[]};
      results.forEach(([format,result])=>{
        result.channels.forEach(channel=>{const index=channels.findIndex(item=>item.id===channel.id);if(index>=0)Object.assign(channels[index],channel);else channels.push(channel)});
        next[format]=result.videos;
      });
      setRankingData(next);setRemote(null);setPage(1);
    }catch(reason){setRankingData(null);setError(reason instanceof Error?reason.message:'YouTube 公开数据暂时无法读取。');}
    finally{setLoading(false);}
  };
  useEffect(()=>{if(mode==='discover'||mode==='radar')void runSearch();},[mode,filters.window,filters.region,filters.language,filters.format,filters.maxSubs]);
  useEffect(()=>{if(mode==='rankings')void runRankingSearch();},[mode,filters.window,filters.region,filters.language,filters.format,filters.maxSubs]);
  const rows=useMemo(()=>source.filter(v=>{
    const o=scoreFor(v),c=channelFor(v),text=`${v.title} ${v.topic} ${v.tags.join(' ')}`.toLowerCase();
    const matchesQuery=mode==='discover'||mode==='radar'||Boolean(remote)||!filters.q||text.includes(filters.q.toLowerCase());
    return matchesQuery&&(filters.language==='all'||v.language===filters.language)&&(filters.format==='all'||v.format===filters.format)&&(filters.maxSubs==='all'||c.subscribers<=Number(filters.maxSubs))&&o.opportunityScore>=Number(filters.minScore);
  }).sort((a,b)=>mode==='rankings'?b.snapshots.at(-1)!.views-a.snapshots.at(-1)!.views:scoreFor(b).opportunityScore-scoreFor(a).opportunityScore),[filters,mode,remote,source]);
  const rankingLongRows=rankingData?.long||rows.filter(video=>video.format==='long');
  const rankingShortRows=rankingData?.short||rows.filter(video=>video.format==='short');
  const resultCount=mode==='rankings'?rankingLongRows.length+rankingShortRows.length:rows.length;
  const radarRows=useMemo(()=>{const now=Date.now();const ageHours=(video:Video)=>Math.max(1,(now-new Date(video.publishedAt).getTime())/3600000);const byVelocity=(a:Video,b:Video)=>scoreFor(b).viewsPerHour-scoreFor(a).viewsPerHour;const byNewest=(a:Video,b:Video)=>new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime();if(radarView==='new')return rows.filter(video=>ageHours(video)<=72).sort(byNewest);if(radarView==='breakout')return rows.filter(video=>channelFor(video).subscribers<=100000&&scoreFor(video).viewsPerSubscriber>=1).sort((a,b)=>scoreFor(b).viewsPerSubscriber-scoreFor(a).viewsPerSubscriber);if(radarView==='repeatable')return rows.filter(video=>video.format==='long'&&video.durationSeconds>=180&&video.durationSeconds<=1800).sort((a,b)=>scoreFor(b).opportunityScore-scoreFor(a).opportunityScore);return [...rows].sort(byVelocity)},[radarView,rows]);
  if(mode==='radar'){const clusters=Object.entries(radarRows.reduce<Record<string,Video[]>>((acc,video)=>{(acc[video.topic]??=[]).push(video);return acc},{}));const radarCopy={velocity:['加速中','按发布至今的平均播放速度排序；单次快照不能证明实时加速。'],new:['新出现','只展示最近 72 小时发布的公开样本。'],breakout:['低粉爆发','订阅不超过 10 万且播放 / 订阅 ≥ 1 的样本。'],repeatable:['可复刻形式','优先展示 3–30 分钟、便于拆解结构的长视频；仍需人工复核。']} as const;return <main className="page"><PageIntro label="机会雷达" title="把公开信号变成可观看、可行动的样本" body="无需关键词，按时间、语言、频道规模和内容形态自动加载真实 YouTube 公开视频；点击缩略图或标题可直接打开原视频。"/><Filters filters={filters} setFilters={setFilters} hideKeyword/><div className="result-toolbar"><span>当前视图找到 <b>{radarRows.length}</b> 个公开样本</span><span>{remote?'真实 YouTube 公开数据 · 单次快照':'正在加载公开视频'}</span><button className="primary" onClick={runSearch} disabled={loading}>{loading?'正在更新…':'更新机会雷达'}</button></div>{error&&<p className="api-error">{error}</p>}{remote&&<p className="api-note">筛选项改变时会自动重新取样；缩略图由服务端代理，点击缩略图或标题会直接打开对应 YouTube 视频。</p>}<div className="radar-tabs" role="tablist" aria-label="机会雷达视图">{(['velocity','new','breakout','repeatable'] as const).map(view=><button key={view} role="tab" aria-selected={radarView===view} className={radarView===view?'active':''} onClick={()=>setRadarView(view)}>{radarCopy[view][0]}</button>)}</div><p className="api-note">{radarCopy[radarView][1]}</p><div className="cluster-list">{clusters.length?clusters.map(([topic,items])=>{const average=Math.round(items.reduce((sum,video)=>sum+scoreFor(video).opportunityScore,0)/items.length);return <section className="cluster" key={topic}><div className="cluster-head"><div><span className="eyebrow">机会簇</span><h2>{topic||'公开视频机会簇'}</h2><p>{items.length} 个样本 · 平均机会评分 {average}</p></div><ScorePill value={average}/></div><div className="mini-grid">{items.slice(0,6).map(video=><VideoCard key={video.id} video={video} state={state} setState={setState} onDetail={openDetail}/>)}</div></section>}):<Empty title="当前视图没有符合条件的公开视频" body="可切换雷达视图、扩大时间窗口、切换内容形态或放宽频道订阅上限后自动重新取样。"/>}</div></main>}
  if(mode==='rankings'){const selectedFormat=filters.format==='short'||filters.format==='long'?filters.format:'all';return <main className="page rankings-page"><PageIntro label="排行榜" title="全站近期趋势榜单" body="无需搜索关键词；按发布时间、频道规模和内容形态筛出值得研究的公开视频。"/><div className="rankings-layout"><RankingFilters filters={filters} setFilters={setFilters}/><div className="rankings-content"><div className="result-toolbar"><span>找到 <b>{resultCount}</b> 个公开样本</span><span>{rankingData?'真实 YouTube 公开数据 · 单次快照':'正在加载公开样本'}</span><button className="primary" onClick={runRankingSearch} disabled={loading}>{loading?'正在更新榜单…':'更新排行榜'}</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}>复制筛选链接</button></div>{error&&<p className="api-error">{error}</p>}{rankingData&&<p className="api-note">筛选项改变后会自动按该发布时间窗口重新取样；短、长视频分别取样，不会互相重复。</p>}<RankingBoard longRows={rankingLongRows} shortRows={rankingShortRows} selectedFormat={selectedFormat} onDetail={openDetail}/></div></div></main>;}
  const isResearch=mode==='research';return <main className={isResearch?'app-page':'page'}><PageIntro label={isResearch?'深度检索':'公开发现'} title={isResearch?'把一个赛道缩小到可验证的公开样本':'自动发现近期值得关注的视频'} body={isResearch?'输入关键词后，按时间、语言、频道规模和内容形态检索真实 YouTube 公开数据。':'无需关键词；按时间、语言、频道规模和内容形态自动筛出真实 YouTube 公开视频。'}/><Filters filters={filters} setFilters={setFilters} hideKeyword={!isResearch}/><div className="result-toolbar"><span>找到 <b>{resultCount}</b> 个样本</span><span>{remote?'真实 YouTube 公开数据 · 单次快照':isResearch?'输入关键词后开始检索':'正在加载公开视频'}</span><button className="primary" onClick={runSearch} disabled={loading}>{loading?(isResearch?'正在检索…':'正在更新…'):(isResearch?'检索公开数据':'更新公开发现')}</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}>复制筛选链接</button></div>{error&&<p className="api-error">{error}</p>}{remote&&<p className="api-note">真实 API 当前返回单次快照：播放/小时表示“发布至今平均播放”，增长趋势与置信度需持续采样后才会更准确。</p>}{rows.length?<div className="video-grid">{rows.slice(0,page*6).map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title={isResearch?'输入关键词开始检索':'当前条件没有公开视频样本'} body={isResearch?'例如输入 AI productivity、history documentary 或 fitness tips。':'可扩大时间窗口、切换内容形态或放宽频道订阅上限后自动重新取样。'}/>} {rows.length>page*6&&<button className="load-more" onClick={()=>setPage(p=>p+1)}>加载更多样本</button>}</main>
}

function PageIntro({label,title,body}:{label:string;title:string;body:string}){return <section className="page-intro"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{body}</p></section>}
function Home(){return <main><section className="hero"><div><span className="eyebrow">YOUTUBE CONTENT INTELLIGENCE</span><h1>每天知道什么正在起势，<em>以及下一步该做什么。</em></h1><p>SignalCraft 将 YouTube 公开信号、可解释评分和行动工作流连接起来。3 分钟找到值得研究的赛道与样本。</p><div className="hero-actions"><button className="primary" onClick={()=>navigate('/discover')}>查看实时公开信号</button><button onClick={()=>navigate('/methodology')}>了解评分方法 →</button></div><div className="proof"><span><b>实时</b> YouTube 公开数据</span><span><b>4</b> 可解释评分维度</span><span><b>多市场</b> 地区与语言筛选</span></div></div><div className="hero-panel"><div className="panel-top"><span>数据状态</span><span className="live">● YouTube API 已连接</span></div><div className="signal-number">实时</div><p>按市场、时间和频道规模加载最新公开样本</p><div className="hero-list"><button onClick={()=>navigate('/discover')}><span>打开公开发现，查看当前市场样本</span><b>→</b></button></div></div></section><section className="home-section"><div className="section-heading"><div><span className="eyebrow">TODAY&apos;S SIGNALS</span><h2>公开榜单与机会雷达</h2></div><button onClick={()=>navigate('/rankings')}>查看全部 →</button></div><div className="home-signal-grid"><button className="signal-row" onClick={()=>navigate('/discover')}><span className="rank">01</span><div><b>自动发现</b><small>无需关键词，按当前市场取样</small></div><span>打开 →</span></button><button className="signal-row" onClick={()=>navigate('/radar')}><span className="rank">02</span><div><b>机会雷达</b><small>按类别与可行动性聚合公开样本</small></div><span>打开 →</span></button></div></section><section className="steps"><div><span>01</span><h3>公开发现</h3><p>按时间、语言、市场、频道规模和表现快速筛选。</p></div><div><span>02</span><h3>判断证据</h3><p>看到增速、相对表现、置信度与风险提示。</p></div><div><span>03</span><h3>形成行动</h3><p>保存、对标、创建选题并回看结果。</p></div></section><section className="cta-band"><div><span className="eyebrow">FROM SIGNAL TO SHIP</span><h2>发现不是终点，形成决策才是。</h2></div><button className="primary" onClick={()=>navigate('/app')}>打开我的工作室</button></section></main>}

function Methodology(){return <main className="page prose"><PageIntro label="方法与边界" title="清晰解释，才能让数据成为判断的辅助。" body="SignalCraft 不把评分伪装成结论；它只是让你更快找到值得验证的公开信号。"/><section><h2>评分如何组成</h2><div className="method-grid"><div><b>VelocityScore</b><p>根据当前公开播放量与发布时间计算平均速度，不等同实时播放。</p></div><div><b>OutlierScore</b><p>播放相对订阅数与频道公开规模的偏离。</p></div><div><b>Confidence</b><p>采样次数与数据完整程度。单次公开快照会明确降低置信度。</p></div><div><b>OpportunityScore</b><p>增速 30%、异常 32%、新鲜度 18%、互动代理 12%、置信度 8%。</p></div></div></section><section><h2>数据与隐私</h2><p>公开发现、排行榜、机会雷达和频道诊断均通过服务端 YouTube Data API 读取当前公开信息；不抓取 YouTube 页面，不在浏览器展示或提交密钥。</p></section><section><h2>局限性</h2><p>单次快照无法证明持续增长。播放表现也不等于商业价值或可复制性；版权、敏感议题、地区文化与算法波动仍需人工复核。</p></section></main>}
function Pricing(){const rows=[['公开发现与市场榜单','✓','✓','✓'],['可解释机会评分','—','✓','✓'],['保存、对标与选题工作流','—','✓','✓'],['团队成员、评论与活动记录','—','—','✓'],['自定义监听与 Webhook','—','—','规划中']];return <main className="page"><PageIntro label="定价" title="先证明价值，再决定升级。" body="价格仅作产品方案说明；在线支付与会员权益系统尚未接入，不会产生自动扣费。"/><div className="pricing-grid">{[['Free','¥0','查看当前 YouTube 公开发现与榜单'],['Pro','¥39 / 月','个人创作者的完整研究工作流'],['Team','¥299 / 月','团队协作、对标与监听能力']].map(([name,price,copy])=><article className={cn('price-card',name==='Pro'&&'featured')} key={name}><span>{name==='Pro'?'推荐':'计划'}</span><h2>{name}</h2><b>{price}</b><p>{copy}</p><button className={name==='Pro'?'primary':''} onClick={()=>navigate('/app')}>{name==='Free'?'免费开始':'进入工作室'}</button></article>)}</div><div className="feature-table"><div className="feature-row heading"><b>功能</b><b>Free</b><b>Pro</b><b>Team</b></div>{rows.map(r=><div className="feature-row" key={r[0]}>{r.map((x,i)=><span key={i}>{x}</span>)}</div>)}</div></main>}

function AppHome({state,setState,openDetail}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){const high=state.saved.filter(v=>scoreFor(v).opportunityScore>=80).slice(0,3);return <main className="app-page"><PageIntro label="今日指挥台" title="先处理已保存的真实信号，再推进内容决策。" body="公开发现数据来自 YouTube Data API；你的保存、任务与选题仅保存在当前设备，尚未启用跨设备同步。"/><div className="command-grid"><section className="command-main"><div className="section-heading"><h2>待处理信号</h2><button onClick={()=>navigate('/discover')}>进入发现页 →</button></div>{high.length?high.map(v=><button className="alert-card" key={v.id} onClick={()=>openDetail(v)}><ScorePill value={scoreFor(v).opportunityScore}/><div><b>{v.title}</b><p>{scoreFor(v).reasons[0]}</p></div><span>查看 →</span></button>):<Empty title="还没有已保存的高分信号" body="先在公开发现或机会雷达中保存真实公开视频。" action={<button className="primary" onClick={()=>navigate('/discover')}>去发现真实样本</button>}/>}</section><section className="command-side"><h2>数据状态</h2><div className="sync"><span>●</span><b>YouTube Data API</b><small>公开发现、排行榜、雷达与频道诊断已连接</small></div><button className="primary full" onClick={()=>navigate('/discover')}>刷新公开发现</button></section></div><div className="dashboard-grid"><section><div className="section-heading"><h2>任务清单</h2><button onClick={()=>setState(s=>({...s,tasks:[...s.tasks,{id:`t${Date.now()}`,title:'新建内容验证任务',status:'待办',owner:'当前用户',due:'待设置'}]}))}>+ 新建</button></div>{state.tasks.length?state.tasks.map(t=><button className="task" key={t.id} onClick={()=>setState(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,status:x.status==='完成'?'待办':'完成'}:x)}))}><span className={cn('check',t.status==='完成'&&'done')}>✓</span><div><b>{t.title}</b><small>{t.owner} · {t.due}</small></div><em>{t.status}</em></button>):<Empty title="尚无任务" body="创建第一条验证任务，形成从信号到行动的记录。"/>}</section><section><div className="section-heading"><h2>通知中心</h2><button onClick={()=>setState(s=>({...s,alerts:s.alerts.map(a=>({...a,read:true}))}))}>全部已读</button></div>{state.alerts.length?state.alerts.map(a=>{const source=a.sourceVideoId?state.saved.find(v=>v.id===a.sourceVideoId):undefined;return <button className={cn('notification',!a.read&&'unread')} key={a.id} onClick={()=>source&&openDetail(source)}><span>↗</span><div><b>{a.title}</b><small>{a.body}</small></div><time>{date(a.createdAt)}</time></button>}):<Empty title="尚无通知" body="创建监听规则后，真实触发记录会显示在这里。"/>}</section></div></main>}

function Library({kind,state,setState,openDetail}:{kind:'channels'|'videos';state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){if(kind==='channels')return <main className="app-page"><PageIntro label="频道资产" title="跟踪值得长期研究的频道。" body="频道资产将在你保存公开视频并建立对标组后逐步沉淀。"/>{state.saved.length?<div className="table-wrap"><table><thead><tr><th>频道</th><th>已保存样本</th><th>订阅</th><th>最近样本</th></tr></thead><tbody>{Array.from(new Map(state.saved.map(v=>[v.channelId,v])).values()).map(v=><tr key={v.channelId}><td><b>{v.channelTitle}</b><small>{v.channelId}</small></td><td>{state.saved.filter(x=>x.channelId===v.channelId).length}</td><td>{num.format(v.snapshots.at(-1)?.subscribers||0)}</td><td><button onClick={()=>openDetail(v)}>查看真实样本 →</button></td></tr>)}</tbody></table></div>:<Empty title="还没有频道资产" body="保存真实公开视频后，频道会自动出现在这里。" action={<button className="primary" onClick={()=>navigate('/discover')}>去发现真实样本</button>}/>}</main>;return <main className="app-page"><PageIntro label="视频资产" title="保存的信号，才能变成可复用的研究资产。" body="为真实公开视频加标签、写笔记、加入选题或对标组。"/>{state.saved.length?<div className="video-grid">{state.saved.map(v=><VideoCard key={v.id} video={v} state={state} setState={setState} onDetail={openDetail}/>)}</div>:<Empty title="还没有保存视频" body="在公开发现或雷达页面点“保存”，这里会自动出现。" action={<button className="primary" onClick={()=>navigate('/discover')}>去发现真实样本</button>}/>}</main>}

function Research({state,setState,openDetail}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;openDetail:(v:Video)=>void}){return <Discovery mode="research" state={state} setState={setState} openDetail={openDetail}/>}
function Watchlists({state,setState,toast}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>;toast:(t:string)=>void}){return <main className="app-page"><PageIntro label="监听规则" title="让异常自己来找你。" body="规则保存在当前设备。后台定时检测和邮件、Webhook 发送将在账户与数据库接入后开放。"/>{state.rules.length?<div className="watch-grid">{state.rules.map(rule=><article className="watch-card" key={rule.id}><div><span className="tag">{rule.type}</span><h2>{rule.name}</h2><p>{rule.frequency} · 机会评分 ≥ {rule.threshold} · {rule.channel}</p></div><label className="toggle"><input type="checkbox" checked={!rule.paused} onChange={()=>setState(s=>({...s,rules:s.rules.map(r=>r.id===rule.id?{...r,paused:!r.paused}:r)}))}/><span /></label></article>)}</div>:<Empty title="还没有监听规则" body="创建规则后会保存在当前设备，等待服务器定时检测接入。"/>}<div className="inline-form"><input placeholder="例如：英语 AI 效率低粉爆发" id="ruleName"/><select id="ruleType"><option>关键词</option><option>频道</option><option>赛道</option></select><button className="primary" onClick={()=>{const input=document.getElementById('ruleName') as HTMLInputElement;const type=document.getElementById('ruleType') as HTMLSelectElement;if(!input.value.trim())return toast('请先填写规则名称');setState(s=>({...s,rules:[...s.rules,{id:`w${Date.now()}`,name:input.value,type:type.value as WatchRule['type'],threshold:75,frequency:'每 6 小时',channel:'站内通知',paused:false}]}));input.value='';toast('监听规则已创建')}}>创建规则</button></div></main>}
function Benchmarks({state,toast}:{state:Persisted;toast:(t:string)=>void}){const [compare,setCompare]=useState<string[]>([]);const candidate=state.saved;const selected=compare.map(id=>candidate.find(v=>v.id===id)).filter(Boolean) as Video[];return <main className="app-page"><PageIntro label="对标组与比较" title="比较 2–5 个样本，寻找共同模式。" body="所有结论都保留回到真实公开视频信号与指标的入口。"/>{state.collections.length?<div className="collection-grid">{state.collections.map(c=><article className="collection" key={c.id}><span style={{background:c.color}} /><div><h2>{c.name}</h2><p>{c.items.length} 个项目 · 当前设备</p></div><button onClick={()=>toast('跨设备分享将在账户与数据库接入后开放')}>分享</button></article>)}</div>:<Empty title="还没有对标组" body="在真实视频的证据页点击“加入对标组”即可创建。"/>}<div className="compare-picker"><h2>快速比较</h2><p>选择 2–5 个已保存的真实视频。</p>{candidate.length?candidate.map(v=><label key={v.id}><input type="checkbox" checked={compare.includes(v.id)} onChange={()=>setCompare(x=>x.includes(v.id)?x.filter(i=>i!==v.id):x.length<5?[...x,v.id]:x)}/>{v.title}</label>):<p>先在发现页保存至少两个视频。</p>}</div>{selected.length>=2&&<div className="compare-table"><div className="compare-heading"><b>指标</b>{selected.map(v=><b key={v.id}>{v.title.slice(0,14)}…</b>)}</div>{[['机会评分',(v:Video)=>scoreFor(v).opportunityScore],['播放 / 订阅',(v:Video)=>`${scoreFor(v).viewsPerSubscriber}×`],['每小时播放',(v:Video)=>num.format(scoreFor(v).viewsPerHour)],['发布时间',(v:Video)=>date(v.publishedAt)],['共同标签',(v:Video)=>v.tags.slice(0,2).join(' / ')]].map(([label,fn])=><div className="compare-row" key={label as string}><span>{label as string}</span>{selected.map(v=><span key={v.id}>{(fn as (v:Video)=>React.ReactNode)(v)}</span>)}</div>)}</div>}</main>}
function Ideas({state,setState}:{state:Persisted;setState:React.Dispatch<React.SetStateAction<Persisted>>}){const statuses:IdeaStatus[]=['收集','验证','制作中','已发布','复盘'];return <main className="app-page"><PageIntro label="选题实验室" title="从信号到制作，再到复盘。" body="每张选题卡都保留真实来源视频，避免凭感觉断开数据。"/><div className="kanban">{statuses.map(status=><section key={status}><div className="kanban-head"><b>{status}</b><span>{state.ideas.filter(i=>i.status===status).length}</span></div>{state.ideas.filter(i=>i.status===status).map(i=>{const v=state.saved.find(v=>v.id===i.sourceVideoId);return <article className="idea" key={i.id}><span className="tag">来源 {v?scoreFor(v).opportunityScore:'数据已不可用'} </span><h3>{i.title}</h3><p>{i.angle}</p><small>{i.owner} · {date(i.createdAt)}</small><select value={i.status} onChange={e=>setState(s=>({...s,ideas:s.ideas.map(x=>x.id===i.id?{...x,status:e.target.value as IdeaStatus}:x)}))}>{statuses.map(x=><option key={x}>{x}</option>)}</select></article>})}{!state.ideas.some(i=>i.status===status)&&<p className="muted">请从真实视频的证据页创建选题。</p>}</section>)}</div></main>}
function Prompts({toast}:{toast:(t:string)=>void}){return <main className="app-page"><PageIntro label="提示词库" title="把研究方法沉淀成可复用模板。" body="提示词会在真实 AI 接入后带入选题上下文。"/>{promptTemplates.length?<div className="prompt-list">{promptTemplates.map(p=><article key={p.id}><div><span className="tag">{p.category}</span><h2>{p.title}</h2><p>{p.body}</p><small>{p.version} · {p.enabled?'已启用':'已停用'}</small></div><button className="primary" onClick={()=>navigator.clipboard?.writeText(p.body).then(()=>toast('提示词模板已复制'))}>复制模板</button></article>)}</div>:<Empty title="暂无自定义提示词" body="创建与保存提示词需要账户数据库接入，暂不展示预置样本。"/>}</main>}
function Settings(){return <main className="app-page"><PageIntro label="配置" title="为真实服务保留安全边界。" body="敏感密钥仅配置在服务器环境变量中，不会显示在浏览器或保存到当前设备。"/><div className="settings-grid"><section><h2>数据源</h2><p><b>YouTube Data API</b> · 服务端已连接</p><p>公开发现、排行榜、机会雷达与频道诊断均读取当前公开数据。</p></section><section><h2>刷新计划</h2><p>当前为用户打开页面时按需获取公开数据。</p><p>后台定时采样与增长曲线需要数据库和任务队列后启用。</p></section><section><h2>团队成员</h2><p>登录、成员角色与跨设备数据同步需要接入认证和数据库。</p></section><section><h2>通知渠道</h2><p>规则暂存当前设备；邮件、Slack、Webhook 尚未启用。</p></section></div></main>}

export default function SignalCraftApp(){const [path,setPath]=useState('/');const [theme,setTheme]=useState('light');const [state,setState]=usePersisted();const [drawer,setDrawer]=useState<Video|null>(null);const [toast,setToast]=useState<Toast>(null);useEffect(()=>{const read=()=>setPath(location.pathname);read();addEventListener('popstate',read);addEventListener('signalcraft:navigate',read);return()=>{removeEventListener('popstate',read);removeEventListener('signalcraft:navigate',read)}},[]);useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);const notify=(message:string)=>{setToast({message});setTimeout(()=>setToast(null),2400)};const content=path==='/'?<Home/>:path==='/discover'?<Discovery mode="discover" state={state} setState={setState} openDetail={setDrawer}/>:path==='/rankings'?<Discovery mode="rankings" state={state} setState={setState} openDetail={setDrawer}/>:path==='/radar'?<Discovery mode="radar" state={state} setState={setState} openDetail={setDrawer}/>:path==='/doctor'||path==='/app/doctor'?<ChannelDoctor/>:path==='/methodology'?<Methodology/>:path==='/pricing'?<Pricing/>:path==='/app'?<AppHome state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/library/channels'?<Library kind="channels" state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/library/videos'?<Library kind="videos" state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/research'?<Research state={state} setState={setState} openDetail={setDrawer}/>:path==='/app/watchlists'?<Watchlists state={state} setState={setState} toast={notify}/>:path==='/app/benchmarks'||path==='/app/compare'?<Benchmarks state={state} toast={notify}/>:path==='/app/ideas'?<Ideas state={state} setState={setState}/>:path==='/app/prompts'?<Prompts toast={notify}/>:path==='/app/settings'?<Settings/>:<Home/>;return <div className="app-shell"><Header path={path} onTheme={()=>setTheme(t=>t==='light'?'dark':'light')}/>{content}{drawer&&<DetailDrawer video={drawer} state={state} setState={setState} onClose={()=>setDrawer(null)} toast={notify}/>} {toast&&<div className="toast">✓ {toast.message}</div>}</div>}
